/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AgentBotsResponse,
    AgentBotsResponseFromJSON,
    AgentBotsResponseToJSON,
} from '../models/AgentBotsResponse';
import {
    type AgentTrafficResponse,
    AgentTrafficResponseFromJSON,
    AgentTrafficResponseToJSON,
} from '../models/AgentTrafficResponse';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';

export interface GetAgentTrafficRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    bot?: string;
    company?: string;
    groupBy?: GetAgentTrafficGroupByEnum;
    granularity?: GetAgentTrafficGranularityEnum;
}

export interface GetAiTrafficRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    source?: string;
    granularity?: GetAiTrafficGranularityEnum;
}

export interface ListAgentBotsRequest {
    projectId: number;
    output?: ListAgentBotsOutputEnum;
}

/**
 * AIAgentTrafficApi - interface
 * 
 * @export
 * @interface AIAgentTrafficApiInterface
 */
export interface AIAgentTrafficApiInterface {
    /**
     * Creates request options for getAgentTraffic without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
     * @param {string} [bot] Filter by bot slug (e.g. gptbot, claudebot, perplexitybot)
     * @param {string} [company] Filter by company (e.g. openai, anthropic, google)
     * @param {'bot' | 'company'} [groupBy] 
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    getAgentTrafficRequestOpts(requestParameters: GetAgentTrafficRequest): Promise<runtime.RequestOpts>;

    /**
     * Aggregated AI bot traffic hitting the project\'s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
     * @summary AI bot crawler traffic (Scale plan or above, Beta)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
     * @param {string} [bot] Filter by bot slug (e.g. gptbot, claudebot, perplexitybot)
     * @param {string} [company] Filter by company (e.g. openai, anthropic, google)
     * @param {'bot' | 'company'} [groupBy] 
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    getAgentTrafficRaw(requestParameters: GetAgentTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentTrafficResponse>>;

    /**
     * Aggregated AI bot traffic hitting the project\'s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
     * AI bot crawler traffic (Scale plan or above, Beta)
     */
    getAgentTraffic(requestParameters: GetAgentTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentTrafficResponse>;

    /**
     * Creates request options for getAiTraffic without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
     * @param {string} [source] Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude)
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    getAiTrafficRequestOpts(requestParameters: GetAiTrafficRequest): Promise<runtime.RequestOpts>;

    /**
     * AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * @summary AI referral traffic (Scale plan or above)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
     * @param {string} [source] Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude)
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    getAiTrafficRaw(requestParameters: GetAiTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * AI referral traffic (Scale plan or above)
     */
    getAiTraffic(requestParameters: GetAiTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listAgentBots without sending the request
     * @param {number} projectId Project ID
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    listAgentBotsRequestOpts(requestParameters: ListAgentBotsRequest): Promise<runtime.RequestOpts>;

    /**
     * Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
     * @summary AI bot catalog (Scale plan or above)
     * @param {number} projectId Project ID
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIAgentTrafficApiInterface
     */
    listAgentBotsRaw(requestParameters: ListAgentBotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentBotsResponse>>;

    /**
     * Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
     * AI bot catalog (Scale plan or above)
     */
    listAgentBots(requestParameters: ListAgentBotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentBotsResponse>;

}

/**
 * 
 */
export class AIAgentTrafficApi extends runtime.BaseAPI implements AIAgentTrafficApiInterface {

    /**
     * Creates request options for getAgentTraffic without sending the request
     */
    async getAgentTrafficRequestOpts(requestParameters: GetAgentTrafficRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getAgentTraffic().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['bot'] != null) {
            queryParameters['bot'] = requestParameters['bot'];
        }

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['groupBy'] != null) {
            queryParameters['group_by'] = requestParameters['groupBy'];
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/metrics/agent_traffic`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Aggregated AI bot traffic hitting the project\'s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
     * AI bot crawler traffic (Scale plan or above, Beta)
     */
    async getAgentTrafficRaw(requestParameters: GetAgentTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentTrafficResponse>> {
        const requestOptions = await this.getAgentTrafficRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentTrafficResponseFromJSON(jsonValue));
    }

    /**
     * Aggregated AI bot traffic hitting the project\'s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
     * AI bot crawler traffic (Scale plan or above, Beta)
     */
    async getAgentTraffic(requestParameters: GetAgentTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentTrafficResponse> {
        const response = await this.getAgentTrafficRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAiTraffic without sending the request
     */
    async getAiTrafficRequestOpts(requestParameters: GetAiTrafficRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getAiTraffic().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/metrics/ai_traffic`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * AI referral traffic (Scale plan or above)
     */
    async getAiTrafficRaw(requestParameters: GetAiTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getAiTrafficRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * AI referral traffic (Scale plan or above)
     */
    async getAiTraffic(requestParameters: GetAiTrafficRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAiTrafficRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listAgentBots without sending the request
     */
    async listAgentBotsRequestOpts(requestParameters: ListAgentBotsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listAgentBots().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dimensions/agent_bots`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
     * AI bot catalog (Scale plan or above)
     */
    async listAgentBotsRaw(requestParameters: ListAgentBotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentBotsResponse>> {
        const requestOptions = await this.listAgentBotsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentBotsResponseFromJSON(jsonValue));
    }

    /**
     * Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
     * AI bot catalog (Scale plan or above)
     */
    async listAgentBots(requestParameters: ListAgentBotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentBotsResponse> {
        const response = await this.listAgentBotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAgentTrafficGroupByEnum = {
    Bot: 'bot',
    Company: 'company'
} as const;
export type GetAgentTrafficGroupByEnum = typeof GetAgentTrafficGroupByEnum[keyof typeof GetAgentTrafficGroupByEnum];
/**
 * @export
 */
export const GetAgentTrafficGranularityEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;
export type GetAgentTrafficGranularityEnum = typeof GetAgentTrafficGranularityEnum[keyof typeof GetAgentTrafficGranularityEnum];
/**
 * @export
 */
export const GetAiTrafficGranularityEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;
export type GetAiTrafficGranularityEnum = typeof GetAiTrafficGranularityEnum[keyof typeof GetAiTrafficGranularityEnum];
/**
 * @export
 */
export const ListAgentBotsOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type ListAgentBotsOutputEnum = typeof ListAgentBotsOutputEnum[keyof typeof ListAgentBotsOutputEnum];
