/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type IntelligenceTask,
    IntelligenceTaskFromJSON,
    IntelligenceTaskToJSON,
} from '../models/IntelligenceTask';
import {
    type IntelligenceTaskCreateRequest,
    IntelligenceTaskCreateRequestFromJSON,
    IntelligenceTaskCreateRequestToJSON,
} from '../models/IntelligenceTaskCreateRequest';

export interface CreateIntelligenceTaskRequest {
    intelligenceTaskCreateRequest: IntelligenceTaskCreateRequest;
}

export interface GetIntelligenceTaskRequest {
    projectId: number;
    id: string;
}

export interface ListIntelligenceTasksRequest {
    projectId: number;
    taskType?: ListIntelligenceTasksTaskTypeEnum;
    status?: string;
    page?: number;
    perPage?: number;
}

/**
 * GEOWriterApi - interface
 * 
 * @export
 * @interface GEOWriterApiInterface
 */
export interface GEOWriterApiInterface {
    /**
     * Creates request options for createIntelligenceTask without sending the request
     * @param {IntelligenceTaskCreateRequest} intelligenceTaskCreateRequest 
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    createIntelligenceTaskRequestOpts(requestParameters: CreateIntelligenceTaskRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a GEO Writer task
     * @param {IntelligenceTaskCreateRequest} intelligenceTaskCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    createIntelligenceTaskRaw(requestParameters: CreateIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntelligenceTask>>;

    /**
     * Create a GEO Writer task
     */
    createIntelligenceTask(requestParameters: CreateIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntelligenceTask>;

    /**
     * Creates request options for getIntelligenceTask without sending the request
     * @param {number} projectId Project ID
     * @param {string} id Numeric task ID or public_id string token
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    getIntelligenceTaskRequestOpts(requestParameters: GetIntelligenceTaskRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a GEO Writer task
     * @param {number} projectId Project ID
     * @param {string} id Numeric task ID or public_id string token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    getIntelligenceTaskRaw(requestParameters: GetIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntelligenceTask>>;

    /**
     * Get a GEO Writer task
     */
    getIntelligenceTask(requestParameters: GetIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntelligenceTask>;

    /**
     * Creates request options for listIntelligenceTasks without sending the request
     * @param {number} projectId Project ID
     * @param {'brief' | 'create' | 'update' | 'pr_insights' | 'custom'} [taskType] 
     * @param {string} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    listIntelligenceTasksRequestOpts(requestParameters: ListIntelligenceTasksRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List GEO Writer tasks
     * @param {number} projectId Project ID
     * @param {'brief' | 'create' | 'update' | 'pr_insights' | 'custom'} [taskType] 
     * @param {string} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GEOWriterApiInterface
     */
    listIntelligenceTasksRaw(requestParameters: ListIntelligenceTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List GEO Writer tasks
     */
    listIntelligenceTasks(requestParameters: ListIntelligenceTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class GEOWriterApi extends runtime.BaseAPI implements GEOWriterApiInterface {

    /**
     * Creates request options for createIntelligenceTask without sending the request
     */
    async createIntelligenceTaskRequestOpts(requestParameters: CreateIntelligenceTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['intelligenceTaskCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'intelligenceTaskCreateRequest',
                'Required parameter "intelligenceTaskCreateRequest" was null or undefined when calling createIntelligenceTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelligence_tasks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IntelligenceTaskCreateRequestToJSON(requestParameters['intelligenceTaskCreateRequest']),
        };
    }

    /**
     * Create a GEO Writer task
     */
    async createIntelligenceTaskRaw(requestParameters: CreateIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntelligenceTask>> {
        const requestOptions = await this.createIntelligenceTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntelligenceTaskFromJSON(jsonValue));
    }

    /**
     * Create a GEO Writer task
     */
    async createIntelligenceTask(requestParameters: CreateIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntelligenceTask> {
        const response = await this.createIntelligenceTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIntelligenceTask without sending the request
     */
    async getIntelligenceTaskRequestOpts(requestParameters: GetIntelligenceTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getIntelligenceTask().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntelligenceTask().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelligence_tasks/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a GEO Writer task
     */
    async getIntelligenceTaskRaw(requestParameters: GetIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntelligenceTask>> {
        const requestOptions = await this.getIntelligenceTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntelligenceTaskFromJSON(jsonValue));
    }

    /**
     * Get a GEO Writer task
     */
    async getIntelligenceTask(requestParameters: GetIntelligenceTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntelligenceTask> {
        const response = await this.getIntelligenceTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listIntelligenceTasks without sending the request
     */
    async listIntelligenceTasksRequestOpts(requestParameters: ListIntelligenceTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listIntelligenceTasks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['taskType'] != null) {
            queryParameters['task_type'] = requestParameters['taskType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/intelligence_tasks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List GEO Writer tasks
     */
    async listIntelligenceTasksRaw(requestParameters: ListIntelligenceTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listIntelligenceTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List GEO Writer tasks
     */
    async listIntelligenceTasks(requestParameters: ListIntelligenceTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listIntelligenceTasksRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ListIntelligenceTasksTaskTypeEnum = {
    Brief: 'brief',
    Create: 'create',
    Update: 'update',
    PrInsights: 'pr_insights',
    Custom: 'custom'
} as const;
export type ListIntelligenceTasksTaskTypeEnum = typeof ListIntelligenceTasksTaskTypeEnum[keyof typeof ListIntelligenceTasksTaskTypeEnum];
