/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type Ping200Response,
    Ping200ResponseFromJSON,
    Ping200ResponseToJSON,
} from '../models/Ping200Response';

export interface PingRequest {
    projectId?: number;
}

/**
 * HealthApi - interface
 * 
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
    /**
     * Creates request options for ping without sending the request
     * @param {number} [projectId] Optional project to verify access for
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    pingRequestOpts(requestParameters: PingRequest): Promise<runtime.RequestOpts>;

    /**
     * Validates the API key and optionally pings a project. Returns the authenticated user_id, project (if project_id is supplied), and a request_id.
     * @summary Health check
     * @param {number} [projectId] Optional project to verify access for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    pingRaw(requestParameters: PingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ping200Response>>;

    /**
     * Validates the API key and optionally pings a project. Returns the authenticated user_id, project (if project_id is supplied), and a request_id.
     * Health check
     */
    ping(requestParameters: PingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ping200Response>;

}

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {

    /**
     * Creates request options for ping without sending the request
     */
    async pingRequestOpts(requestParameters: PingRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ping`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Validates the API key and optionally pings a project. Returns the authenticated user_id, project (if project_id is supplied), and a request_id.
     * Health check
     */
    async pingRaw(requestParameters: PingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ping200Response>> {
        const requestOptions = await this.pingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Ping200ResponseFromJSON(jsonValue));
    }

    /**
     * Validates the API key and optionally pings a project. Returns the authenticated user_id, project (if project_id is supplied), and a request_id.
     * Health check
     */
    async ping(requestParameters: PingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ping200Response> {
        const response = await this.pingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
