/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.51.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateProjectDraftRequest,
    CreateProjectDraftRequestFromJSON,
    CreateProjectDraftRequestToJSON,
} from '../models/CreateProjectDraftRequest';
import {
    type FinalizeProjectDraftRequest,
    FinalizeProjectDraftRequestFromJSON,
    FinalizeProjectDraftRequestToJSON,
} from '../models/FinalizeProjectDraftRequest';
import {
    type ListProjects200Response,
    ListProjects200ResponseFromJSON,
    ListProjects200ResponseToJSON,
} from '../models/ListProjects200Response';
import {
    type ProjectCreateRequest,
    ProjectCreateRequestFromJSON,
    ProjectCreateRequestToJSON,
} from '../models/ProjectCreateRequest';
import {
    type ProjectCreateResponse,
    ProjectCreateResponseFromJSON,
    ProjectCreateResponseToJSON,
} from '../models/ProjectCreateResponse';
import {
    type ProjectDetails,
    ProjectDetailsFromJSON,
    ProjectDetailsToJSON,
} from '../models/ProjectDetails';
import {
    type UpdateProjectDraftRequest,
    UpdateProjectDraftRequestFromJSON,
    UpdateProjectDraftRequestToJSON,
} from '../models/UpdateProjectDraftRequest';
import {
    type UpdateProjectRequest,
    UpdateProjectRequestFromJSON,
    UpdateProjectRequestToJSON,
} from '../models/UpdateProjectRequest';

export interface CreateProjectRequest {
    projectCreateRequest: ProjectCreateRequest;
}

export interface CreateProjectDraftOperationRequest {
    createProjectDraftRequest: CreateProjectDraftRequest;
}

export interface FinalizeProjectDraftOperationRequest {
    id: string;
    finalizeProjectDraftRequest?: FinalizeProjectDraftRequest;
}

export interface GetProjectDetailsRequest {
    id: number;
}

export interface GetProjectDraftRequest {
    id: string;
    includeSuggestions?: boolean;
}

export interface ListLocalesRequest {
    projectId: number;
}

export interface ListModelsRequest {
    projectId: number;
}

export interface ListProjectsRequest {
    output?: ListProjectsOutputEnum;
}

export interface UpdateProjectOperationRequest {
    id: number;
    updateProjectRequest: UpdateProjectRequest;
}

export interface UpdateProjectDraftOperationRequest {
    id: string;
    updateProjectDraftRequest: UpdateProjectDraftRequest;
}

/**
 * ProjectsApi - interface
 * 
 * @export
 * @interface ProjectsApiInterface
 */
export interface ProjectsApiInterface {
    /**
     * Creates request options for createProject without sending the request
     * @param {ProjectCreateRequest} projectCreateRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectRequestOpts(requestParameters: CreateProjectRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), collections tagging those prompts, competitors, weekly email subscription. The response lists same_domain_projects so an accidental duplicate is visible; it never blocks the create. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * @summary Create a project (fast mode)
     * @param {ProjectCreateRequest} projectCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectCreateResponse>>;

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), collections tagging those prompts, competitors, weekly email subscription. The response lists same_domain_projects so an accidental duplicate is visible; it never blocks the create. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectCreateResponse>;

    /**
     * Creates request options for createProjectDraft without sending the request
     * @param {CreateProjectDraftRequest} createProjectDraftRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectDraftRequestOpts(requestParameters: CreateProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * @summary Start a project draft (wizard step 1)
     * @param {CreateProjectDraftRequest} createProjectDraftRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectDraftRaw(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    createProjectDraft(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for finalizeProjectDraft without sending the request
     * @param {string} id 
     * @param {FinalizeProjectDraftRequest} [finalizeProjectDraftRequest] 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    finalizeProjectDraftRequestOpts(requestParameters: FinalizeProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * @summary Finalize a draft into a real project
     * @param {string} id 
     * @param {FinalizeProjectDraftRequest} [finalizeProjectDraftRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    finalizeProjectDraftRaw(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    finalizeProjectDraft(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getProjectDetails without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDetailsRequestOpts(requestParameters: GetProjectDetailsRequest): Promise<runtime.RequestOpts>;

    /**
     * Detailed info for one project: matching_names, industry, business model, primary products, target audience, brand voice, locale, app store IDs, stats (incl. prompts_by_brand_kind counts) and data_coverage (models, countries and languages with data).
     * @summary Project details
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDetailsRaw(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetails>>;

    /**
     * Detailed info for one project: matching_names, industry, business model, primary products, target audience, brand voice, locale, app store IDs, stats (incl. prompts_by_brand_kind counts) and data_coverage (models, countries and languages with data).
     * Project details
     */
    getProjectDetails(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetails>;

    /**
     * Creates request options for getProjectDraft without sending the request
     * @param {string} id Draft id (draft_...)
     * @param {boolean} [includeSuggestions] Cache-only: returns suggestions for the current step if already generated, never triggers AI
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDraftRequestOpts(requestParameters: GetProjectDraftRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Read a project draft
     * @param {string} id Draft id (draft_...)
     * @param {boolean} [includeSuggestions] Cache-only: returns suggestions for the current step if already generated, never triggers AI
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDraftRaw(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Read a project draft
     */
    getProjectDraft(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listLocales without sending the request
     * @param {number} projectId Project ID
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listLocalesRequestOpts(requestParameters: ListLocalesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List locales with data
     * @param {number} projectId Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listLocalesRaw(requestParameters: ListLocalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List locales with data
     */
    listLocales(requestParameters: ListLocalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listModels without sending the request
     * @param {number} projectId Project ID
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listModelsRequestOpts(requestParameters: ListModelsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List models with data
     * @param {number} projectId Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * List models with data
     */
    listModels(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listProjects without sending the request
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listProjectsRequestOpts(requestParameters: ListProjectsRequest): Promise<runtime.RequestOpts>;

    /**
     * All projects accessible with your API key.
     * @summary List projects
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    listProjectsRaw(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProjects200Response>>;

    /**
     * All projects accessible with your API key.
     * List projects
     */
    listProjects(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProjects200Response>;

    /**
     * Creates request options for updateProject without sending the request
     * @param {number} id 
     * @param {UpdateProjectRequest} updateProjectRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectRequestOpts(requestParameters: UpdateProjectOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates the project name and profile, the same fields as Project Settings: name, brand_name, description, industry, business_model (plus business_model_other when it is OTHER), target_audience, brand_voice, goals, primary_products, matching_names. Send only the fields to change; unknown fields are rejected. All seven Brand Book fields feed every GEO Writer task and prompt suggestions; only industry, description, and target_audience help Recommendations. A matching_names change re-runs mention/citation matching over the project history in the background (rematching=true); further edits are rejected while that runs. Requires a `read_write` scope API key.
     * @summary Update a project profile (Brand Book)
     * @param {number} id 
     * @param {UpdateProjectRequest} updateProjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates the project name and profile, the same fields as Project Settings: name, brand_name, description, industry, business_model (plus business_model_other when it is OTHER), target_audience, brand_voice, goals, primary_products, matching_names. Send only the fields to change; unknown fields are rejected. All seven Brand Book fields feed every GEO Writer task and prompt suggestions; only industry, description, and target_audience help Recommendations. A matching_names change re-runs mention/citation matching over the project history in the background (rematching=true); further edits are rejected while that runs. Requires a `read_write` scope API key.
     * Update a project profile (Brand Book)
     */
    updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateProjectDraft without sending the request
     * @param {string} id 
     * @param {UpdateProjectDraftRequest} updateProjectDraftRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectDraftRequestOpts(requestParameters: UpdateProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * @summary Submit a wizard step
     * @param {string} id 
     * @param {UpdateProjectDraftRequest} updateProjectDraftRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectDraftRaw(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    updateProjectDraft(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI implements ProjectsApiInterface {

    /**
     * Creates request options for createProject without sending the request
     */
    async createProjectRequestOpts(requestParameters: CreateProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'projectCreateRequest',
                'Required parameter "projectCreateRequest" was null or undefined when calling createProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateRequestToJSON(requestParameters['projectCreateRequest']),
        };
    }

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), collections tagging those prompts, competitors, weekly email subscription. The response lists same_domain_projects so an accidental duplicate is visible; it never blocks the create. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    async createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectCreateResponse>> {
        const requestOptions = await this.createProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), collections tagging those prompts, competitors, weekly email subscription. The response lists same_domain_projects so an accidental duplicate is visible; it never blocks the create. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    async createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectCreateResponse> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectDraft without sending the request
     */
    async createProjectDraftRequestOpts(requestParameters: CreateProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProjectDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectDraftRequest',
                'Required parameter "createProjectDraftRequest" was null or undefined when calling createProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectDraftRequestToJSON(requestParameters['createProjectDraftRequest']),
        };
    }

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    async createProjectDraftRaw(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    async createProjectDraft(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for finalizeProjectDraft without sending the request
     */
    async finalizeProjectDraftRequestOpts(requestParameters: FinalizeProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling finalizeProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}/finalize`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FinalizeProjectDraftRequestToJSON(requestParameters['finalizeProjectDraftRequest']),
        };
    }

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    async finalizeProjectDraftRaw(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.finalizeProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    async finalizeProjectDraft(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.finalizeProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getProjectDetails without sending the request
     */
    async getProjectDetailsRequestOpts(requestParameters: GetProjectDetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProjectDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dimensions/projects/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detailed info for one project: matching_names, industry, business model, primary products, target audience, brand voice, locale, app store IDs, stats (incl. prompts_by_brand_kind counts) and data_coverage (models, countries and languages with data).
     * Project details
     */
    async getProjectDetailsRaw(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetails>> {
        const requestOptions = await this.getProjectDetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailsFromJSON(jsonValue));
    }

    /**
     * Detailed info for one project: matching_names, industry, business model, primary products, target audience, brand voice, locale, app store IDs, stats (incl. prompts_by_brand_kind counts) and data_coverage (models, countries and languages with data).
     * Project details
     */
    async getProjectDetails(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetails> {
        const response = await this.getProjectDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectDraft without sending the request
     */
    async getProjectDraftRequestOpts(requestParameters: GetProjectDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProjectDraft().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeSuggestions'] != null) {
            queryParameters['include_suggestions'] = requestParameters['includeSuggestions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a project draft
     */
    async getProjectDraftRaw(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Read a project draft
     */
    async getProjectDraft(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listLocales without sending the request
     */
    async listLocalesRequestOpts(requestParameters: ListLocalesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listLocales().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dimensions/locales`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List locales with data
     */
    async listLocalesRaw(requestParameters: ListLocalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listLocalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List locales with data
     */
    async listLocales(requestParameters: ListLocalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listLocalesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listModels without sending the request
     */
    async listModelsRequestOpts(requestParameters: ListModelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listModels().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dimensions/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List models with data
     */
    async listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listModelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List models with data
     */
    async listModels(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listModelsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listProjects without sending the request
     */
    async listProjectsRequestOpts(requestParameters: ListProjectsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dimensions/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * All projects accessible with your API key.
     * List projects
     */
    async listProjectsRaw(requestParameters: ListProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProjects200Response>> {
        const requestOptions = await this.listProjectsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProjects200ResponseFromJSON(jsonValue));
    }

    /**
     * All projects accessible with your API key.
     * List projects
     */
    async listProjects(requestParameters: ListProjectsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProjects200Response> {
        const response = await this.listProjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProject without sending the request
     */
    async updateProjectRequestOpts(requestParameters: UpdateProjectOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProject().'
            );
        }

        if (requestParameters['updateProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectRequest',
                'Required parameter "updateProjectRequest" was null or undefined when calling updateProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectRequestToJSON(requestParameters['updateProjectRequest']),
        };
    }

    /**
     * Updates the project name and profile, the same fields as Project Settings: name, brand_name, description, industry, business_model (plus business_model_other when it is OTHER), target_audience, brand_voice, goals, primary_products, matching_names. Send only the fields to change; unknown fields are rejected. All seven Brand Book fields feed every GEO Writer task and prompt suggestions; only industry, description, and target_audience help Recommendations. A matching_names change re-runs mention/citation matching over the project history in the background (rematching=true); further edits are rejected while that runs. Requires a `read_write` scope API key.
     * Update a project profile (Brand Book)
     */
    async updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates the project name and profile, the same fields as Project Settings: name, brand_name, description, industry, business_model (plus business_model_other when it is OTHER), target_audience, brand_voice, goals, primary_products, matching_names. Send only the fields to change; unknown fields are rejected. All seven Brand Book fields feed every GEO Writer task and prompt suggestions; only industry, description, and target_audience help Recommendations. A matching_names change re-runs mention/citation matching over the project history in the background (rematching=true); further edits are rejected while that runs. Requires a `read_write` scope API key.
     * Update a project profile (Brand Book)
     */
    async updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateProjectDraft without sending the request
     */
    async updateProjectDraftRequestOpts(requestParameters: UpdateProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProjectDraft().'
            );
        }

        if (requestParameters['updateProjectDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectDraftRequest',
                'Required parameter "updateProjectDraftRequest" was null or undefined when calling updateProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectDraftRequestToJSON(requestParameters['updateProjectDraftRequest']),
        };
    }

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    async updateProjectDraftRaw(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    async updateProjectDraft(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProjectDraftRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ListProjectsOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type ListProjectsOutputEnum = typeof ListProjectsOutputEnum[keyof typeof ListProjectsOutputEnum];
