/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type CreateProjectDraftRequest,
    CreateProjectDraftRequestFromJSON,
    CreateProjectDraftRequestToJSON,
} from '../models/CreateProjectDraftRequest';
import {
    type FinalizeProjectDraftRequest,
    FinalizeProjectDraftRequestFromJSON,
    FinalizeProjectDraftRequestToJSON,
} from '../models/FinalizeProjectDraftRequest';
import {
    type ProjectCreateRequest,
    ProjectCreateRequestFromJSON,
    ProjectCreateRequestToJSON,
} from '../models/ProjectCreateRequest';
import {
    type ProjectCreateResponse,
    ProjectCreateResponseFromJSON,
    ProjectCreateResponseToJSON,
} from '../models/ProjectCreateResponse';
import {
    type UpdateProjectDraftRequest,
    UpdateProjectDraftRequestFromJSON,
    UpdateProjectDraftRequestToJSON,
} from '../models/UpdateProjectDraftRequest';

export interface CreateProjectRequest {
    projectCreateRequest: ProjectCreateRequest;
}

export interface CreateProjectDraftOperationRequest {
    createProjectDraftRequest: CreateProjectDraftRequest;
}

export interface FinalizeProjectDraftOperationRequest {
    id: string;
    finalizeProjectDraftRequest?: FinalizeProjectDraftRequest;
}

export interface GetProjectDraftRequest {
    id: string;
    includeSuggestions?: boolean;
}

export interface UpdateProjectDraftOperationRequest {
    id: string;
    updateProjectDraftRequest: UpdateProjectDraftRequest;
}

/**
 * ProjectsApi - interface
 * 
 * @export
 * @interface ProjectsApiInterface
 */
export interface ProjectsApiInterface {
    /**
     * Creates request options for createProject without sending the request
     * @param {ProjectCreateRequest} projectCreateRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectRequestOpts(requestParameters: CreateProjectRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), competitors, weekly email subscription. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * @summary Create a project (fast mode)
     * @param {ProjectCreateRequest} projectCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectCreateResponse>>;

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), competitors, weekly email subscription. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectCreateResponse>;

    /**
     * Creates request options for createProjectDraft without sending the request
     * @param {CreateProjectDraftRequest} createProjectDraftRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectDraftRequestOpts(requestParameters: CreateProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * @summary Start a project draft (wizard step 1)
     * @param {CreateProjectDraftRequest} createProjectDraftRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectDraftRaw(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    createProjectDraft(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for finalizeProjectDraft without sending the request
     * @param {string} id 
     * @param {FinalizeProjectDraftRequest} [finalizeProjectDraftRequest] 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    finalizeProjectDraftRequestOpts(requestParameters: FinalizeProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * @summary Finalize a draft into a real project
     * @param {string} id 
     * @param {FinalizeProjectDraftRequest} [finalizeProjectDraftRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    finalizeProjectDraftRaw(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    finalizeProjectDraft(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getProjectDraft without sending the request
     * @param {string} id Draft id (draft_...)
     * @param {boolean} [includeSuggestions] Cache-only: returns suggestions for the current step if already generated, never triggers AI
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDraftRequestOpts(requestParameters: GetProjectDraftRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Read a project draft
     * @param {string} id Draft id (draft_...)
     * @param {boolean} [includeSuggestions] Cache-only: returns suggestions for the current step if already generated, never triggers AI
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDraftRaw(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Read a project draft
     */
    getProjectDraft(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateProjectDraft without sending the request
     * @param {string} id 
     * @param {UpdateProjectDraftRequest} updateProjectDraftRequest 
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectDraftRequestOpts(requestParameters: UpdateProjectDraftOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * @summary Submit a wizard step
     * @param {string} id 
     * @param {UpdateProjectDraftRequest} updateProjectDraftRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectDraftRaw(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    updateProjectDraft(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI implements ProjectsApiInterface {

    /**
     * Creates request options for createProject without sending the request
     */
    async createProjectRequestOpts(requestParameters: CreateProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'projectCreateRequest',
                'Required parameter "projectCreateRequest" was null or undefined when calling createProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateRequestToJSON(requestParameters['projectCreateRequest']),
        };
    }

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), competitors, weekly email subscription. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    async createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectCreateResponse>> {
        const requestOptions = await this.createProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create a complete project in one call: project fields, prompts (queued for execution and categorization), competitors, weekly email subscription. Idempotent via `external_identifier` (embed-enabled accounts only; replay returns 200 with the existing project). Requires a `read_write` scope API key.
     * Create a project (fast mode)
     */
    async createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectCreateResponse> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProjectDraft without sending the request
     */
    async createProjectDraftRequestOpts(requestParameters: CreateProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProjectDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectDraftRequest',
                'Required parameter "createProjectDraftRequest" was null or undefined when calling createProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectDraftRequestToJSON(requestParameters['createProjectDraftRequest']),
        };
    }

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    async createProjectDraftRaw(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start the multi-step project-creation wizard. Returns a draft_id plus AI suggestions (name, description, industry, brand aliases) for the URL. Cold URLs can take up to ~2 minutes to analyze; pass suggest=false to skip AI and respond instantly. Drafts expire after 24h. Requires a `read_write` scope API key.
     * Start a project draft (wizard step 1)
     */
    async createProjectDraft(requestParameters: CreateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for finalizeProjectDraft without sending the request
     */
    async finalizeProjectDraftRequestOpts(requestParameters: FinalizeProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling finalizeProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}/finalize`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FinalizeProjectDraftRequestToJSON(requestParameters['finalizeProjectDraftRequest']),
        };
    }

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    async finalizeProjectDraftRaw(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.finalizeProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates the project with all accumulated draft data (same effects as POST /projects). Idempotent: finalizing an already-finalized draft returns 200 with the existing project. Optional overrides: weekly_email_subscribed, execute_prompts_immediately.
     * Finalize a draft into a real project
     */
    async finalizeProjectDraft(requestParameters: FinalizeProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.finalizeProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getProjectDraft without sending the request
     */
    async getProjectDraftRequestOpts(requestParameters: GetProjectDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProjectDraft().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeSuggestions'] != null) {
            queryParameters['include_suggestions'] = requestParameters['includeSuggestions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read a project draft
     */
    async getProjectDraftRaw(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Read a project draft
     */
    async getProjectDraft(requestParameters: GetProjectDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getProjectDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateProjectDraft without sending the request
     */
    async updateProjectDraftRequestOpts(requestParameters: UpdateProjectDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProjectDraft().'
            );
        }

        if (requestParameters['updateProjectDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProjectDraftRequest',
                'Required parameter "updateProjectDraftRequest" was null or undefined when calling updateProjectDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/project_drafts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectDraftRequestToJSON(requestParameters['updateProjectDraftRequest']),
        };
    }

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    async updateProjectDraftRaw(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateProjectDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit one step (details, prompts, competitors, owned_media). Strict forward gating: a step is only accepted when every previous step is complete (`ERR_DRAFT_STATE` otherwise); completed steps can be resubmitted. Responds with the updated draft plus AI suggestions for the next step.
     * Submit a wizard step
     */
    async updateProjectDraft(requestParameters: UpdateProjectDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProjectDraftRaw(requestParameters, initOverrides);
    }

}
