/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type LaunchRecommendationsRequest,
    LaunchRecommendationsRequestFromJSON,
    LaunchRecommendationsRequestToJSON,
} from '../models/LaunchRecommendationsRequest';
import {
    type RecommendationsResponse,
    RecommendationsResponseFromJSON,
    RecommendationsResponseToJSON,
} from '../models/RecommendationsResponse';

export interface GetRecommendationRequest {
    projectId: number;
    id: number;
    itemStatus?: GetRecommendationItemStatusEnum;
    resolveSourceRefs?: boolean;
}

export interface LaunchRecommendationsOperationRequest {
    launchRecommendationsRequest: LaunchRecommendationsRequest;
}

export interface ListRecommendationsRequest {
    projectId: number;
    recommendationType?: ListRecommendationsRecommendationTypeEnum;
    status?: ListRecommendationsStatusEnum;
    page?: number;
    perPage?: number;
}

/**
 * RecommendationsApi - interface
 * 
 * @export
 * @interface RecommendationsApiInterface
 */
export interface RecommendationsApiInterface {
    /**
     * Creates request options for getRecommendation without sending the request
     * @param {number} projectId Project ID
     * @param {number} id 
     * @param {'active' | 'completed' | 'archived'} [itemStatus] 
     * @param {boolean} [resolveSourceRefs] 
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    getRecommendationRequestOpts(requestParameters: GetRecommendationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get recommendation run with items
     * @param {number} projectId Project ID
     * @param {number} id 
     * @param {'active' | 'completed' | 'archived'} [itemStatus] 
     * @param {boolean} [resolveSourceRefs] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    getRecommendationRaw(requestParameters: GetRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get recommendation run with items
     */
    getRecommendation(requestParameters: GetRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for launchRecommendations without sending the request
     * @param {LaunchRecommendationsRequest} launchRecommendationsRequest 
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    launchRecommendationsRequestOpts(requestParameters: LaunchRecommendationsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Launches a full-scope recommendations generation (async job, 1-3 minutes; poll GET /recommendations/{id} until status is completed). Consumes the project weekly recommendation-item budget: returns ERR_LIMIT_REACHED when it is exhausted or when a generation of the same type is already pending/processing. sentiment_reputation requires the Scale plan or above. Requires a `read_write` scope API key.
     * @summary Launch a recommendations generation
     * @param {LaunchRecommendationsRequest} launchRecommendationsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    launchRecommendationsRaw(requestParameters: LaunchRecommendationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Launches a full-scope recommendations generation (async job, 1-3 minutes; poll GET /recommendations/{id} until status is completed). Consumes the project weekly recommendation-item budget: returns ERR_LIMIT_REACHED when it is exhausted or when a generation of the same type is already pending/processing. sentiment_reputation requires the Scale plan or above. Requires a `read_write` scope API key.
     * Launch a recommendations generation
     */
    launchRecommendations(requestParameters: LaunchRecommendationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listRecommendations without sending the request
     * @param {number} projectId Project ID
     * @param {'ai_visibility' | 'social_community' | 'brand_building' | 'sentiment_reputation'} [recommendationType] 
     * @param {'pending' | 'processing' | 'completed' | 'failed'} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    listRecommendationsRequestOpts(requestParameters: ListRecommendationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List recommendation runs
     * @param {number} projectId Project ID
     * @param {'ai_visibility' | 'social_community' | 'brand_building' | 'sentiment_reputation'} [recommendationType] 
     * @param {'pending' | 'processing' | 'completed' | 'failed'} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApiInterface
     */
    listRecommendationsRaw(requestParameters: ListRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecommendationsResponse>>;

    /**
     * List recommendation runs
     */
    listRecommendations(requestParameters: ListRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecommendationsResponse>;

}

/**
 * 
 */
export class RecommendationsApi extends runtime.BaseAPI implements RecommendationsApiInterface {

    /**
     * Creates request options for getRecommendation without sending the request
     */
    async getRecommendationRequestOpts(requestParameters: GetRecommendationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getRecommendation().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRecommendation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['itemStatus'] != null) {
            queryParameters['item_status'] = requestParameters['itemStatus'];
        }

        if (requestParameters['resolveSourceRefs'] != null) {
            queryParameters['resolve_source_refs'] = requestParameters['resolveSourceRefs'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recommendations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get recommendation run with items
     */
    async getRecommendationRaw(requestParameters: GetRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getRecommendationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get recommendation run with items
     */
    async getRecommendation(requestParameters: GetRecommendationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getRecommendationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for launchRecommendations without sending the request
     */
    async launchRecommendationsRequestOpts(requestParameters: LaunchRecommendationsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['launchRecommendationsRequest'] == null) {
            throw new runtime.RequiredError(
                'launchRecommendationsRequest',
                'Required parameter "launchRecommendationsRequest" was null or undefined when calling launchRecommendations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recommendations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LaunchRecommendationsRequestToJSON(requestParameters['launchRecommendationsRequest']),
        };
    }

    /**
     * Launches a full-scope recommendations generation (async job, 1-3 minutes; poll GET /recommendations/{id} until status is completed). Consumes the project weekly recommendation-item budget: returns ERR_LIMIT_REACHED when it is exhausted or when a generation of the same type is already pending/processing. sentiment_reputation requires the Scale plan or above. Requires a `read_write` scope API key.
     * Launch a recommendations generation
     */
    async launchRecommendationsRaw(requestParameters: LaunchRecommendationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.launchRecommendationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Launches a full-scope recommendations generation (async job, 1-3 minutes; poll GET /recommendations/{id} until status is completed). Consumes the project weekly recommendation-item budget: returns ERR_LIMIT_REACHED when it is exhausted or when a generation of the same type is already pending/processing. sentiment_reputation requires the Scale plan or above. Requires a `read_write` scope API key.
     * Launch a recommendations generation
     */
    async launchRecommendations(requestParameters: LaunchRecommendationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.launchRecommendationsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listRecommendations without sending the request
     */
    async listRecommendationsRequestOpts(requestParameters: ListRecommendationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listRecommendations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['recommendationType'] != null) {
            queryParameters['recommendation_type'] = requestParameters['recommendationType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recommendations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List recommendation runs
     */
    async listRecommendationsRaw(requestParameters: ListRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecommendationsResponse>> {
        const requestOptions = await this.listRecommendationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecommendationsResponseFromJSON(jsonValue));
    }

    /**
     * List recommendation runs
     */
    async listRecommendations(requestParameters: ListRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecommendationsResponse> {
        const response = await this.listRecommendationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetRecommendationItemStatusEnum = {
    Active: 'active',
    Completed: 'completed',
    Archived: 'archived'
} as const;
export type GetRecommendationItemStatusEnum = typeof GetRecommendationItemStatusEnum[keyof typeof GetRecommendationItemStatusEnum];
/**
 * @export
 */
export const ListRecommendationsRecommendationTypeEnum = {
    AiVisibility: 'ai_visibility',
    SocialCommunity: 'social_community',
    BrandBuilding: 'brand_building',
    SentimentReputation: 'sentiment_reputation'
} as const;
export type ListRecommendationsRecommendationTypeEnum = typeof ListRecommendationsRecommendationTypeEnum[keyof typeof ListRecommendationsRecommendationTypeEnum];
/**
 * @export
 */
export const ListRecommendationsStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type ListRecommendationsStatusEnum = typeof ListRecommendationsStatusEnum[keyof typeof ListRecommendationsStatusEnum];
