/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.49.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';

export interface GetReputationReportRequest {
    id: string;
    projectId: number;
    page?: number;
    perPage?: number;
    model?: GetReputationReportModelEnum;
    brand?: string;
    dimension?: string;
    output?: GetReputationReportOutputEnum;
}

export interface GetStudyRequest {
    id: number;
}

export interface GetStudyReportRequest {
    id: number;
    reportId: string;
    page?: number;
    perPage?: number;
    model?: GetStudyReportModelEnum;
    subject?: string;
    dimension?: string;
    output?: GetStudyReportOutputEnum;
}

export interface ListReputationReportsRequest {
    projectId: number;
    page?: number;
    perPage?: number;
    output?: ListReputationReportsOutputEnum;
}

export interface ListStudiesRequest {
    projectId?: number;
    status?: ListStudiesStatusEnum;
    page?: number;
    perPage?: number;
    output?: ListStudiesOutputEnum;
}

/**
 * ReputationStudiesApi - interface
 * 
 * @export
 * @interface ReputationStudiesApiInterface
 */
export interface ReputationStudiesApiInterface {
    /**
     * Creates request options for getReputationReport without sending the request
     * @param {string} id The report id from GET /reputation/reports
     * @param {number} projectId Project ID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'chatgpt' | 'perplexity' | 'gemini' | 'deepseek' | 'grok' | 'claude'} [model] Restrict to one analyst model
     * @param {string} [brand] Restrict to one brand name, or a comma-separated list
     * @param {string} [dimension] Restrict to one reputation dimension key
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getReputationReportRequestOpts(requestParameters: GetReputationReportRequest): Promise<runtime.RequestOpts>;

    /**
     * One reputation report\'s scores as flat rows: one row per analyst model, brand, dimension and attribute, with its 0-100 score and the reasoning the model gave. Scores come from several analyst models independently, so compare models rather than averaging them blindly.
     * @summary Get reputation report scores
     * @param {string} id The report id from GET /reputation/reports
     * @param {number} projectId Project ID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'chatgpt' | 'perplexity' | 'gemini' | 'deepseek' | 'grok' | 'claude'} [model] Restrict to one analyst model
     * @param {string} [brand] Restrict to one brand name, or a comma-separated list
     * @param {string} [dimension] Restrict to one reputation dimension key
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getReputationReportRaw(requestParameters: GetReputationReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * One reputation report\'s scores as flat rows: one row per analyst model, brand, dimension and attribute, with its 0-100 score and the reasoning the model gave. Scores come from several analyst models independently, so compare models rather than averaging them blindly.
     * Get reputation report scores
     */
    getReputationReport(requestParameters: GetReputationReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getStudy without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getStudyRequestOpts(requestParameters: GetStudyRequest): Promise<runtime.RequestOpts>;

    /**
     * One study with its brief, the subjects it compares, the dimensions it scores them on, and its report history. Use the ids in `reports` with GET /studies/{id}/reports/{report_id}.
     * @summary Get a custom AI study
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getStudyRaw(requestParameters: GetStudyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * One study with its brief, the subjects it compares, the dimensions it scores them on, and its report history. Use the ids in `reports` with GET /studies/{id}/reports/{report_id}.
     * Get a custom AI study
     */
    getStudy(requestParameters: GetStudyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getStudyReport without sending the request
     * @param {number} id 
     * @param {string} reportId The report id from GET /studies/{id}
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'chatgpt' | 'perplexity' | 'gemini' | 'deepseek' | 'grok' | 'claude'} [model] Restrict to one analyst model
     * @param {string} [subject] Restrict to one subject name, or a comma-separated list
     * @param {string} [dimension] Restrict to one dimension key
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getStudyReportRequestOpts(requestParameters: GetStudyReportRequest): Promise<runtime.RequestOpts>;

    /**
     * One custom-study report\'s scores as flat rows: one row per analyst model, subject, dimension and attribute, with its 0-100 score and the reasoning the model gave.
     * @summary Get custom study report scores
     * @param {number} id 
     * @param {string} reportId The report id from GET /studies/{id}
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'chatgpt' | 'perplexity' | 'gemini' | 'deepseek' | 'grok' | 'claude'} [model] Restrict to one analyst model
     * @param {string} [subject] Restrict to one subject name, or a comma-separated list
     * @param {string} [dimension] Restrict to one dimension key
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    getStudyReportRaw(requestParameters: GetStudyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * One custom-study report\'s scores as flat rows: one row per analyst model, subject, dimension and attribute, with its 0-100 score and the reasoning the model gave.
     * Get custom study report scores
     */
    getStudyReport(requestParameters: GetStudyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listReputationReports without sending the request
     * @param {number} projectId Project ID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    listReputationReportsRequestOpts(requestParameters: ListReputationReportsRequest): Promise<runtime.RequestOpts>;

    /**
     * The monthly multi-model analyst reports scoring the tracked brand and its competitors, newest first. Pending and failed reports are included on purpose: whether this month ran at all is often the question. Each row carries the report id, its status, and which analyst models produced data. Requires reputation monitoring to be enabled on the account.
     * @summary List reputation reports
     * @param {number} projectId Project ID
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    listReputationReportsRaw(requestParameters: ListReputationReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * The monthly multi-model analyst reports scoring the tracked brand and its competitors, newest first. Pending and failed reports are included on purpose: whether this month ran at all is often the question. Each row carries the report id, its status, and which analyst models produced data. Requires reputation monitoring to be enabled on the account.
     * List reputation reports
     */
    listReputationReports(requestParameters: ListReputationReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listStudies without sending the request
     * @param {number} [projectId] Restrict to studies attached to this project (plus account-level ones)
     * @param {'active' | 'archived'} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    listStudiesRequestOpts(requestParameters: ListStudiesRequest): Promise<runtime.RequestOpts>;

    /**
     * The custom AI studies defined on the account: analyst reports over any set of subjects (brands, sectors, topics) and any set of dimensions. Studies belong to the ACCOUNT, not to a project, so project_id is an optional filter here and account-level studies are returned whichever project you filter by. A team member whose project access is restricted sees only the studies of the projects they can reach. Requires reputation monitoring to be enabled on the account.
     * @summary List custom AI studies
     * @param {number} [projectId] Restrict to studies attached to this project (plus account-level ones)
     * @param {'active' | 'archived'} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReputationStudiesApiInterface
     */
    listStudiesRaw(requestParameters: ListStudiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * The custom AI studies defined on the account: analyst reports over any set of subjects (brands, sectors, topics) and any set of dimensions. Studies belong to the ACCOUNT, not to a project, so project_id is an optional filter here and account-level studies are returned whichever project you filter by. A team member whose project access is restricted sees only the studies of the projects they can reach. Requires reputation monitoring to be enabled on the account.
     * List custom AI studies
     */
    listStudies(requestParameters: ListStudiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ReputationStudiesApi extends runtime.BaseAPI implements ReputationStudiesApiInterface {

    /**
     * Creates request options for getReputationReport without sending the request
     */
    async getReputationReportRequestOpts(requestParameters: GetReputationReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getReputationReport().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getReputationReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['brand'] != null) {
            queryParameters['brand'] = requestParameters['brand'];
        }

        if (requestParameters['dimension'] != null) {
            queryParameters['dimension'] = requestParameters['dimension'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reputation/reports/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One reputation report\'s scores as flat rows: one row per analyst model, brand, dimension and attribute, with its 0-100 score and the reasoning the model gave. Scores come from several analyst models independently, so compare models rather than averaging them blindly.
     * Get reputation report scores
     */
    async getReputationReportRaw(requestParameters: GetReputationReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getReputationReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * One reputation report\'s scores as flat rows: one row per analyst model, brand, dimension and attribute, with its 0-100 score and the reasoning the model gave. Scores come from several analyst models independently, so compare models rather than averaging them blindly.
     * Get reputation report scores
     */
    async getReputationReport(requestParameters: GetReputationReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getReputationReportRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getStudy without sending the request
     */
    async getStudyRequestOpts(requestParameters: GetStudyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/studies/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One study with its brief, the subjects it compares, the dimensions it scores them on, and its report history. Use the ids in `reports` with GET /studies/{id}/reports/{report_id}.
     * Get a custom AI study
     */
    async getStudyRaw(requestParameters: GetStudyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getStudyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * One study with its brief, the subjects it compares, the dimensions it scores them on, and its report history. Use the ids in `reports` with GET /studies/{id}/reports/{report_id}.
     * Get a custom AI study
     */
    async getStudy(requestParameters: GetStudyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getStudyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getStudyReport without sending the request
     */
    async getStudyReportRequestOpts(requestParameters: GetStudyReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudyReport().'
            );
        }

        if (requestParameters['reportId'] == null) {
            throw new runtime.RequiredError(
                'reportId',
                'Required parameter "reportId" was null or undefined when calling getStudyReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['subject'] != null) {
            queryParameters['subject'] = requestParameters['subject'];
        }

        if (requestParameters['dimension'] != null) {
            queryParameters['dimension'] = requestParameters['dimension'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/studies/{id}/reports/{report_id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{report_id}', encodeURIComponent(String(requestParameters['reportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One custom-study report\'s scores as flat rows: one row per analyst model, subject, dimension and attribute, with its 0-100 score and the reasoning the model gave.
     * Get custom study report scores
     */
    async getStudyReportRaw(requestParameters: GetStudyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getStudyReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * One custom-study report\'s scores as flat rows: one row per analyst model, subject, dimension and attribute, with its 0-100 score and the reasoning the model gave.
     * Get custom study report scores
     */
    async getStudyReport(requestParameters: GetStudyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getStudyReportRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listReputationReports without sending the request
     */
    async listReputationReportsRequestOpts(requestParameters: ListReputationReportsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listReputationReports().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reputation/reports`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The monthly multi-model analyst reports scoring the tracked brand and its competitors, newest first. Pending and failed reports are included on purpose: whether this month ran at all is often the question. Each row carries the report id, its status, and which analyst models produced data. Requires reputation monitoring to be enabled on the account.
     * List reputation reports
     */
    async listReputationReportsRaw(requestParameters: ListReputationReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listReputationReportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The monthly multi-model analyst reports scoring the tracked brand and its competitors, newest first. Pending and failed reports are included on purpose: whether this month ran at all is often the question. Each row carries the report id, its status, and which analyst models produced data. Requires reputation monitoring to be enabled on the account.
     * List reputation reports
     */
    async listReputationReports(requestParameters: ListReputationReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listReputationReportsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listStudies without sending the request
     */
    async listStudiesRequestOpts(requestParameters: ListStudiesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/studies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The custom AI studies defined on the account: analyst reports over any set of subjects (brands, sectors, topics) and any set of dimensions. Studies belong to the ACCOUNT, not to a project, so project_id is an optional filter here and account-level studies are returned whichever project you filter by. A team member whose project access is restricted sees only the studies of the projects they can reach. Requires reputation monitoring to be enabled on the account.
     * List custom AI studies
     */
    async listStudiesRaw(requestParameters: ListStudiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listStudiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The custom AI studies defined on the account: analyst reports over any set of subjects (brands, sectors, topics) and any set of dimensions. Studies belong to the ACCOUNT, not to a project, so project_id is an optional filter here and account-level studies are returned whichever project you filter by. A team member whose project access is restricted sees only the studies of the projects they can reach. Requires reputation monitoring to be enabled on the account.
     * List custom AI studies
     */
    async listStudies(requestParameters: ListStudiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listStudiesRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetReputationReportModelEnum = {
    Chatgpt: 'chatgpt',
    Perplexity: 'perplexity',
    Gemini: 'gemini',
    Deepseek: 'deepseek',
    Grok: 'grok',
    Claude: 'claude'
} as const;
export type GetReputationReportModelEnum = typeof GetReputationReportModelEnum[keyof typeof GetReputationReportModelEnum];
/**
 * @export
 */
export const GetReputationReportOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type GetReputationReportOutputEnum = typeof GetReputationReportOutputEnum[keyof typeof GetReputationReportOutputEnum];
/**
 * @export
 */
export const GetStudyReportModelEnum = {
    Chatgpt: 'chatgpt',
    Perplexity: 'perplexity',
    Gemini: 'gemini',
    Deepseek: 'deepseek',
    Grok: 'grok',
    Claude: 'claude'
} as const;
export type GetStudyReportModelEnum = typeof GetStudyReportModelEnum[keyof typeof GetStudyReportModelEnum];
/**
 * @export
 */
export const GetStudyReportOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type GetStudyReportOutputEnum = typeof GetStudyReportOutputEnum[keyof typeof GetStudyReportOutputEnum];
/**
 * @export
 */
export const ListReputationReportsOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type ListReputationReportsOutputEnum = typeof ListReputationReportsOutputEnum[keyof typeof ListReputationReportsOutputEnum];
/**
 * @export
 */
export const ListStudiesStatusEnum = {
    Active: 'active',
    Archived: 'archived'
} as const;
export type ListStudiesStatusEnum = typeof ListStudiesStatusEnum[keyof typeof ListStudiesStatusEnum];
/**
 * @export
 */
export const ListStudiesOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type ListStudiesOutputEnum = typeof ListStudiesOutputEnum[keyof typeof ListStudiesOutputEnum];
