/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';

export interface GetSearchConsolePagesRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    sort?: GetSearchConsolePagesSortEnum;
    page?: number;
    perPage?: number;
    output?: GetSearchConsolePagesOutputEnum;
}

export interface GetSearchConsoleQueriesRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    sort?: GetSearchConsoleQueriesSortEnum;
    page?: number;
    perPage?: number;
    output?: GetSearchConsoleQueriesOutputEnum;
}

export interface GetSearchConsoleSummaryRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    dimension?: GetSearchConsoleSummaryDimensionEnum;
}

export interface GetSearchConsoleTimeseriesRequest {
    projectId: number;
    range?: number;
    from?: Date;
    to?: Date;
    granularity?: GetSearchConsoleTimeseriesGranularityEnum;
    output?: GetSearchConsoleTimeseriesOutputEnum;
}

/**
 * SearchConsoleApi - interface
 * 
 * @export
 * @interface SearchConsoleApiInterface
 */
export interface SearchConsoleApiInterface {
    /**
     * Creates request options for getSearchConsolePages without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'impressions' | 'clicks' | 'ctr' | 'position'} [sort] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsolePagesRequestOpts(requestParameters: GetSearchConsolePagesRequest): Promise<runtime.RequestOpts>;

    /**
     * Top Google Search Console landing pages over a date range, ranked by impressions, clicks, ctr or position, paginated. Requires a connected Search Console property (Growth+).
     * @summary Top Search Console pages (Growth+)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'impressions' | 'clicks' | 'ctr' | 'position'} [sort] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsolePagesRaw(requestParameters: GetSearchConsolePagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Top Google Search Console landing pages over a date range, ranked by impressions, clicks, ctr or position, paginated. Requires a connected Search Console property (Growth+).
     * Top Search Console pages (Growth+)
     */
    getSearchConsolePages(requestParameters: GetSearchConsolePagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getSearchConsoleQueries without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'impressions' | 'clicks' | 'ctr' | 'position'} [sort] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleQueriesRequestOpts(requestParameters: GetSearchConsoleQueriesRequest): Promise<runtime.RequestOpts>;

    /**
     * Top Google Search Console search queries over a date range, ranked by impressions, clicks, ctr or position, paginated. Knowingly undercounts anonymized queries; for exact totals use /search_console/summary. Requires a connected Search Console property (Growth+).
     * @summary Top Search Console queries (Growth+)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'impressions' | 'clicks' | 'ctr' | 'position'} [sort] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleQueriesRaw(requestParameters: GetSearchConsoleQueriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Top Google Search Console search queries over a date range, ranked by impressions, clicks, ctr or position, paginated. Knowingly undercounts anonymized queries; for exact totals use /search_console/summary. Requires a connected Search Console property (Growth+).
     * Top Search Console queries (Growth+)
     */
    getSearchConsoleQueries(requestParameters: GetSearchConsoleQueriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getSearchConsoleSummary without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'country' | 'device'} [dimension] Optional breakdown aggregated over the range
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleSummaryRequestOpts(requestParameters: GetSearchConsoleSummaryRequest): Promise<runtime.RequestOpts>;

    /**
     * Google Search Console headline totals (impressions, clicks, ctr as a 0..1 fraction, average position) for the project over a date range. Pass dimension=country or dimension=device to also receive the breakdown aggregated over the range. Requires the project to have a connected Search Console property and the Growth plan or above; otherwise returns ERR_SEARCH_CONSOLE_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * @summary Search Console summary (Growth+)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'country' | 'device'} [dimension] Optional breakdown aggregated over the range
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleSummaryRaw(requestParameters: GetSearchConsoleSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Google Search Console headline totals (impressions, clicks, ctr as a 0..1 fraction, average position) for the project over a date range. Pass dimension=country or dimension=device to also receive the breakdown aggregated over the range. Requires the project to have a connected Search Console property and the Growth plan or above; otherwise returns ERR_SEARCH_CONSOLE_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * Search Console summary (Growth+)
     */
    getSearchConsoleSummary(requestParameters: GetSearchConsoleSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getSearchConsoleTimeseries without sending the request
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleTimeseriesRequestOpts(requestParameters: GetSearchConsoleTimeseriesRequest): Promise<runtime.RequestOpts>;

    /**
     * Google Search Console property-wide series (impressions, clicks, ctr, position) bucketed by day, week or month. Requires a connected Search Console property (Growth+).
     * @summary Search Console time series (Growth+)
     * @param {number} projectId Project ID
     * @param {number} [range] Number of days to look back (alternative to from/to)
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {'day' | 'week' | 'month'} [granularity] 
     * @param {'flat' | 'csv'} [output] Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. \&#39;flat\&#39; returns the same metadata plus \&#39;columns\&#39; and \&#39;rows\&#39;; \&#39;csv\&#39; returns those rows as text/csv. Errors are always returned as JSON.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchConsoleApiInterface
     */
    getSearchConsoleTimeseriesRaw(requestParameters: GetSearchConsoleTimeseriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Google Search Console property-wide series (impressions, clicks, ctr, position) bucketed by day, week or month. Requires a connected Search Console property (Growth+).
     * Search Console time series (Growth+)
     */
    getSearchConsoleTimeseries(requestParameters: GetSearchConsoleTimeseriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class SearchConsoleApi extends runtime.BaseAPI implements SearchConsoleApiInterface {

    /**
     * Creates request options for getSearchConsolePages without sending the request
     */
    async getSearchConsolePagesRequestOpts(requestParameters: GetSearchConsolePagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSearchConsolePages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/search_console/pages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Top Google Search Console landing pages over a date range, ranked by impressions, clicks, ctr or position, paginated. Requires a connected Search Console property (Growth+).
     * Top Search Console pages (Growth+)
     */
    async getSearchConsolePagesRaw(requestParameters: GetSearchConsolePagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getSearchConsolePagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Top Google Search Console landing pages over a date range, ranked by impressions, clicks, ctr or position, paginated. Requires a connected Search Console property (Growth+).
     * Top Search Console pages (Growth+)
     */
    async getSearchConsolePages(requestParameters: GetSearchConsolePagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getSearchConsolePagesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getSearchConsoleQueries without sending the request
     */
    async getSearchConsoleQueriesRequestOpts(requestParameters: GetSearchConsoleQueriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSearchConsoleQueries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/search_console/queries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Top Google Search Console search queries over a date range, ranked by impressions, clicks, ctr or position, paginated. Knowingly undercounts anonymized queries; for exact totals use /search_console/summary. Requires a connected Search Console property (Growth+).
     * Top Search Console queries (Growth+)
     */
    async getSearchConsoleQueriesRaw(requestParameters: GetSearchConsoleQueriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getSearchConsoleQueriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Top Google Search Console search queries over a date range, ranked by impressions, clicks, ctr or position, paginated. Knowingly undercounts anonymized queries; for exact totals use /search_console/summary. Requires a connected Search Console property (Growth+).
     * Top Search Console queries (Growth+)
     */
    async getSearchConsoleQueries(requestParameters: GetSearchConsoleQueriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getSearchConsoleQueriesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getSearchConsoleSummary without sending the request
     */
    async getSearchConsoleSummaryRequestOpts(requestParameters: GetSearchConsoleSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSearchConsoleSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['dimension'] != null) {
            queryParameters['dimension'] = requestParameters['dimension'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/search_console/summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Google Search Console headline totals (impressions, clicks, ctr as a 0..1 fraction, average position) for the project over a date range. Pass dimension=country or dimension=device to also receive the breakdown aggregated over the range. Requires the project to have a connected Search Console property and the Growth plan or above; otherwise returns ERR_SEARCH_CONSOLE_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * Search Console summary (Growth+)
     */
    async getSearchConsoleSummaryRaw(requestParameters: GetSearchConsoleSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getSearchConsoleSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Google Search Console headline totals (impressions, clicks, ctr as a 0..1 fraction, average position) for the project over a date range. Pass dimension=country or dimension=device to also receive the breakdown aggregated over the range. Requires the project to have a connected Search Console property and the Growth plan or above; otherwise returns ERR_SEARCH_CONSOLE_NOT_CONNECTED or ERR_PLAN_REQUIRED.
     * Search Console summary (Growth+)
     */
    async getSearchConsoleSummary(requestParameters: GetSearchConsoleSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getSearchConsoleSummaryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getSearchConsoleTimeseries without sending the request
     */
    async getSearchConsoleTimeseriesRequestOpts(requestParameters: GetSearchConsoleTimeseriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSearchConsoleTimeseries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        if (requestParameters['output'] != null) {
            queryParameters['output'] = requestParameters['output'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/search_console/timeseries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Google Search Console property-wide series (impressions, clicks, ctr, position) bucketed by day, week or month. Requires a connected Search Console property (Growth+).
     * Search Console time series (Growth+)
     */
    async getSearchConsoleTimeseriesRaw(requestParameters: GetSearchConsoleTimeseriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getSearchConsoleTimeseriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Google Search Console property-wide series (impressions, clicks, ctr, position) bucketed by day, week or month. Requires a connected Search Console property (Growth+).
     * Search Console time series (Growth+)
     */
    async getSearchConsoleTimeseries(requestParameters: GetSearchConsoleTimeseriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getSearchConsoleTimeseriesRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetSearchConsolePagesSortEnum = {
    Impressions: 'impressions',
    Clicks: 'clicks',
    Ctr: 'ctr',
    Position: 'position'
} as const;
export type GetSearchConsolePagesSortEnum = typeof GetSearchConsolePagesSortEnum[keyof typeof GetSearchConsolePagesSortEnum];
/**
 * @export
 */
export const GetSearchConsolePagesOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type GetSearchConsolePagesOutputEnum = typeof GetSearchConsolePagesOutputEnum[keyof typeof GetSearchConsolePagesOutputEnum];
/**
 * @export
 */
export const GetSearchConsoleQueriesSortEnum = {
    Impressions: 'impressions',
    Clicks: 'clicks',
    Ctr: 'ctr',
    Position: 'position'
} as const;
export type GetSearchConsoleQueriesSortEnum = typeof GetSearchConsoleQueriesSortEnum[keyof typeof GetSearchConsoleQueriesSortEnum];
/**
 * @export
 */
export const GetSearchConsoleQueriesOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type GetSearchConsoleQueriesOutputEnum = typeof GetSearchConsoleQueriesOutputEnum[keyof typeof GetSearchConsoleQueriesOutputEnum];
/**
 * @export
 */
export const GetSearchConsoleSummaryDimensionEnum = {
    Country: 'country',
    Device: 'device'
} as const;
export type GetSearchConsoleSummaryDimensionEnum = typeof GetSearchConsoleSummaryDimensionEnum[keyof typeof GetSearchConsoleSummaryDimensionEnum];
/**
 * @export
 */
export const GetSearchConsoleTimeseriesGranularityEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;
export type GetSearchConsoleTimeseriesGranularityEnum = typeof GetSearchConsoleTimeseriesGranularityEnum[keyof typeof GetSearchConsoleTimeseriesGranularityEnum];
/**
 * @export
 */
export const GetSearchConsoleTimeseriesOutputEnum = {
    Flat: 'flat',
    Csv: 'csv'
} as const;
export type GetSearchConsoleTimeseriesOutputEnum = typeof GetSearchConsoleTimeseriesOutputEnum[keyof typeof GetSearchConsoleTimeseriesOutputEnum];
