/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A ceiling with no usage counter attached. limit is null when unlimited is true.
 * @export
 * @interface AccountCapacity
 */
export interface AccountCapacity {
    /**
     * 
     * @type {number}
     * @memberof AccountCapacity
     */
    limit?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccountCapacity
     */
    unlimited?: boolean;
}

/**
 * Check if a given object implements the AccountCapacity interface.
 */
export function instanceOfAccountCapacity(value: object): value is AccountCapacity {
    return true;
}

export function AccountCapacityFromJSON(json: any): AccountCapacity {
    return AccountCapacityFromJSONTyped(json, false);
}

export function AccountCapacityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCapacity {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] === undefined ? undefined : json['limit'] === null ? null : json['limit'],
        'unlimited': json['unlimited'] == null ? undefined : json['unlimited'],
    };
}

export function AccountCapacityToJSON(json: any): AccountCapacity {
    return AccountCapacityToJSONTyped(json, false);
}

export function AccountCapacityToJSONTyped(value?: AccountCapacity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'unlimited': value['unlimited'],
    };
}

