/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Actor
 */
export interface Actor {
    /**
     * 
     * @type {ActorTypeEnum}
     * @memberof Actor
     */
    type?: ActorTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Actor
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Actor
     */
    competitorId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Actor
     */
    name?: string;
    /**
     * Bare (scheme-less) domain
     * @type {string}
     * @memberof Actor
     */
    domain?: string;
}


/**
 * @export
 */
export const ActorTypeEnum = {
    Project: 'project',
    Competitor: 'competitor'
} as const;
export type ActorTypeEnum = typeof ActorTypeEnum[keyof typeof ActorTypeEnum];


/**
 * Check if a given object implements the Actor interface.
 */
export function instanceOfActor(value: object): value is Actor {
    return true;
}

export function ActorFromJSON(json: any): Actor {
    return ActorFromJSONTyped(json, false);
}

export function ActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Actor {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'competitorId': json['competitor_id'] === undefined ? undefined : json['competitor_id'] === null ? null : json['competitor_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function ActorToJSON(json: any): Actor {
    return ActorToJSONTyped(json, false);
}

export function ActorToJSONTyped(value?: Actor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'competitor_id': value['competitorId'],
        'name': value['name'],
        'domain': value['domain'],
    };
}

