/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentTrafficResponse
 */
export interface AgentTrafficResponse {
    /**
     * 
     * @type {number}
     * @memberof AgentTrafficResponse
     */
    projectId?: number;
    /**
     * 
     * @type {Date}
     * @memberof AgentTrafficResponse
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AgentTrafficResponse
     */
    to?: Date;
    /**
     * 
     * @type {AgentTrafficResponseGroupByEnum}
     * @memberof AgentTrafficResponse
     */
    groupBy?: AgentTrafficResponseGroupByEnum;
    /**
     * 
     * @type {AgentTrafficResponseGranularityEnum}
     * @memberof AgentTrafficResponse
     */
    granularity?: AgentTrafficResponseGranularityEnum;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof AgentTrafficResponse
     */
    totals?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof AgentTrafficResponse
     */
    timeseries?: { [key: string]: { [key: string]: number; }; };
    /**
     * 
     * @type {string}
     * @memberof AgentTrafficResponse
     */
    requestId?: string;
}


/**
 * @export
 */
export const AgentTrafficResponseGroupByEnum = {
    Bot: 'bot',
    Company: 'company'
} as const;
export type AgentTrafficResponseGroupByEnum = typeof AgentTrafficResponseGroupByEnum[keyof typeof AgentTrafficResponseGroupByEnum];

/**
 * @export
 */
export const AgentTrafficResponseGranularityEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;
export type AgentTrafficResponseGranularityEnum = typeof AgentTrafficResponseGranularityEnum[keyof typeof AgentTrafficResponseGranularityEnum];


/**
 * Check if a given object implements the AgentTrafficResponse interface.
 */
export function instanceOfAgentTrafficResponse(value: object): value is AgentTrafficResponse {
    return true;
}

export function AgentTrafficResponseFromJSON(json: any): AgentTrafficResponse {
    return AgentTrafficResponseFromJSONTyped(json, false);
}

export function AgentTrafficResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTrafficResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'groupBy': json['group_by'] == null ? undefined : json['group_by'],
        'granularity': json['granularity'] == null ? undefined : json['granularity'],
        'totals': json['totals'] == null ? undefined : json['totals'],
        'timeseries': json['timeseries'] == null ? undefined : json['timeseries'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function AgentTrafficResponseToJSON(json: any): AgentTrafficResponse {
    return AgentTrafficResponseToJSONTyped(json, false);
}

export function AgentTrafficResponseToJSONTyped(value?: AgentTrafficResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'from': value['from'] == null ? value['from'] : value['from'].toISOString().substring(0,10),
        'to': value['to'] == null ? value['to'] : value['to'].toISOString().substring(0,10),
        'group_by': value['groupBy'],
        'granularity': value['granularity'],
        'totals': value['totals'],
        'timeseries': value['timeseries'],
        'request_id': value['requestId'],
    };
}

