/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiOrdersUpdateRequestDaysInner } from './AiOrdersUpdateRequestDaysInner';
import {
    AiOrdersUpdateRequestDaysInnerFromJSON,
    AiOrdersUpdateRequestDaysInnerFromJSONTyped,
    AiOrdersUpdateRequestDaysInnerToJSON,
    AiOrdersUpdateRequestDaysInnerToJSONTyped,
} from './AiOrdersUpdateRequestDaysInner';

/**
 * 
 * @export
 * @interface AiOrdersUpdateRequest
 */
export interface AiOrdersUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof AiOrdersUpdateRequest
     */
    projectId: number;
    /**
     * 
     * @type {AiOrdersUpdateRequestPlatformEnum}
     * @memberof AiOrdersUpdateRequest
     */
    platform: AiOrdersUpdateRequestPlatformEnum;
    /**
     * ISO 4217 code, e.g. EUR
     * @type {string}
     * @memberof AiOrdersUpdateRequest
     */
    currency: string;
    /**
     * First day of the window this push replaces
     * @type {Date}
     * @memberof AiOrdersUpdateRequest
     */
    from: Date;
    /**
     * Last day of the window; at most 400 days after from
     * @type {Date}
     * @memberof AiOrdersUpdateRequest
     */
    to: Date;
    /**
     * 
     * @type {Array<AiOrdersUpdateRequestDaysInner>}
     * @memberof AiOrdersUpdateRequest
     */
    days: Array<AiOrdersUpdateRequestDaysInner>;
}


/**
 * @export
 */
export const AiOrdersUpdateRequestPlatformEnum = {
    Shopify: 'shopify'
} as const;
export type AiOrdersUpdateRequestPlatformEnum = typeof AiOrdersUpdateRequestPlatformEnum[keyof typeof AiOrdersUpdateRequestPlatformEnum];


/**
 * Check if a given object implements the AiOrdersUpdateRequest interface.
 */
export function instanceOfAiOrdersUpdateRequest(value: object): value is AiOrdersUpdateRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'shopify') return false;
    
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function AiOrdersUpdateRequestFromJSON(json: any): AiOrdersUpdateRequest {
    return AiOrdersUpdateRequestFromJSONTyped(json, false);
}

export function AiOrdersUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiOrdersUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'platform': json['platform'],
        'currency': json['currency'],
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
        'days': ((json['days'] as Array<any>).map(AiOrdersUpdateRequestDaysInnerFromJSON)),
    };
}

export function AiOrdersUpdateRequestToJSON(json: any): AiOrdersUpdateRequest {
    return AiOrdersUpdateRequestToJSONTyped(json, false);
}

export function AiOrdersUpdateRequestToJSONTyped(value?: AiOrdersUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'platform': value['platform'],
        'currency': value['currency'],
        'from': value['from'].toISOString().substring(0,10),
        'to': value['to'].toISOString().substring(0,10),
        'days': ((value['days'] as Array<any>).map(AiOrdersUpdateRequestDaysInnerToJSON)),
    };
}

