/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiOrdersUpdateResponse
 */
export interface AiOrdersUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof AiOrdersUpdateResponse
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof AiOrdersUpdateResponse
     */
    platform: string;
    /**
     * Rows stored, one per day and AI assistant
     * @type {number}
     * @memberof AiOrdersUpdateResponse
     */
    stored: number;
    /**
     * Entries whose referrer is not an AI assistant
     * @type {number}
     * @memberof AiOrdersUpdateResponse
     */
    ignored: number;
    /**
     * 
     * @type {string}
     * @memberof AiOrdersUpdateResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the AiOrdersUpdateResponse interface.
 */
export function instanceOfAiOrdersUpdateResponse(value: object): value is AiOrdersUpdateResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('stored' in value) || value['stored'] === undefined) return false;
    if (!('ignored' in value) || value['ignored'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function AiOrdersUpdateResponseFromJSON(json: any): AiOrdersUpdateResponse {
    return AiOrdersUpdateResponseFromJSONTyped(json, false);
}

export function AiOrdersUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiOrdersUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'platform': json['platform'],
        'stored': json['stored'],
        'ignored': json['ignored'],
        'requestId': json['request_id'],
    };
}

export function AiOrdersUpdateResponseToJSON(json: any): AiOrdersUpdateResponse {
    return AiOrdersUpdateResponseToJSONTyped(json, false);
}

export function AiOrdersUpdateResponseToJSONTyped(value?: AiOrdersUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'platform': value['platform'],
        'stored': value['stored'],
        'ignored': value['ignored'],
        'request_id': value['requestId'],
    };
}

