/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiOrdersResponseBySourceInner } from './AiOrdersResponseBySourceInner';
import {
    AiOrdersResponseBySourceInnerFromJSON,
    AiOrdersResponseBySourceInnerFromJSONTyped,
    AiOrdersResponseBySourceInnerToJSON,
    AiOrdersResponseBySourceInnerToJSONTyped,
} from './AiOrdersResponseBySourceInner';
import type { AiOrdersResponseSeriesInner } from './AiOrdersResponseSeriesInner';
import {
    AiOrdersResponseSeriesInnerFromJSON,
    AiOrdersResponseSeriesInnerFromJSONTyped,
    AiOrdersResponseSeriesInnerToJSON,
    AiOrdersResponseSeriesInnerToJSONTyped,
} from './AiOrdersResponseSeriesInner';
import type { AiOrdersResponseTotals } from './AiOrdersResponseTotals';
import {
    AiOrdersResponseTotalsFromJSON,
    AiOrdersResponseTotalsFromJSONTyped,
    AiOrdersResponseTotalsToJSON,
    AiOrdersResponseTotalsToJSONTyped,
} from './AiOrdersResponseTotals';

/**
 * 
 * @export
 * @interface AiOrdersResponse
 */
export interface AiOrdersResponse {
    /**
     * 
     * @type {number}
     * @memberof AiOrdersResponse
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof AiOrdersResponse
     */
    platform: string;
    /**
     * ISO 4217 code of the most recent stored day; null when the window holds no stored order
     * @type {string}
     * @memberof AiOrdersResponse
     */
    currency: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AiOrdersResponse
     */
    from: Date;
    /**
     * 
     * @type {Date}
     * @memberof AiOrdersResponse
     */
    to: Date;
    /**
     * 
     * @type {AiOrdersResponseTotals}
     * @memberof AiOrdersResponse
     */
    totals: AiOrdersResponseTotals;
    /**
     * One row per AI assistant, highest revenue first
     * @type {Array<AiOrdersResponseBySourceInner>}
     * @memberof AiOrdersResponse
     */
    bySource: Array<AiOrdersResponseBySourceInner>;
    /**
     * Days that have stored orders, oldest first
     * @type {Array<AiOrdersResponseSeriesInner>}
     * @memberof AiOrdersResponse
     */
    series: Array<AiOrdersResponseSeriesInner>;
    /**
     * 
     * @type {string}
     * @memberof AiOrdersResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the AiOrdersResponse interface.
 */
export function instanceOfAiOrdersResponse(value: object): value is AiOrdersResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('totals' in value) || value['totals'] === undefined) return false;
    if ((!('bySource' in (value as Record<string, any>)) && !('by_source' in (value as Record<string, any>))) || ((value as Record<string, any>)['bySource'] === undefined && (value as Record<string, any>)['by_source'] === undefined)) return false;
    if (!('series' in value) || value['series'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function AiOrdersResponseFromJSON(json: any): AiOrdersResponse {
    return AiOrdersResponseFromJSONTyped(json, false);
}

export function AiOrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiOrdersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'platform': json['platform'],
        'currency': json['currency'],
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
        'totals': AiOrdersResponseTotalsFromJSON(json['totals']),
        'bySource': ((json['by_source'] as Array<any>).map(AiOrdersResponseBySourceInnerFromJSON)),
        'series': ((json['series'] as Array<any>).map(AiOrdersResponseSeriesInnerFromJSON)),
        'requestId': json['request_id'],
    };
}

export function AiOrdersResponseToJSON(json: any): AiOrdersResponse {
    return AiOrdersResponseToJSONTyped(json, false);
}

export function AiOrdersResponseToJSONTyped(value?: AiOrdersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'platform': value['platform'],
        'currency': value['currency'],
        'from': value['from'].toISOString().substring(0,10),
        'to': value['to'].toISOString().substring(0,10),
        'totals': AiOrdersResponseTotalsToJSON(value['totals']),
        'by_source': ((value['bySource'] as Array<any>).map(AiOrdersResponseBySourceInnerToJSON)),
        'series': ((value['series'] as Array<any>).map(AiOrdersResponseSeriesInnerToJSON)),
        'request_id': value['requestId'],
    };
}

