/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiOrdersResponseBySourceInner
 */
export interface AiOrdersResponseBySourceInner {
    /**
     * AI assistant slug, e.g. chatgpt or perplexity
     * @type {string}
     * @memberof AiOrdersResponseBySourceInner
     */
    source: string;
    /**
     * Display name, e.g. ChatGPT
     * @type {string}
     * @memberof AiOrdersResponseBySourceInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AiOrdersResponseBySourceInner
     */
    orders: number;
    /**
     * 
     * @type {string}
     * @memberof AiOrdersResponseBySourceInner
     */
    revenue: string;
}

/**
 * Check if a given object implements the AiOrdersResponseBySourceInner interface.
 */
export function instanceOfAiOrdersResponseBySourceInner(value: object): value is AiOrdersResponseBySourceInner {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    return true;
}

export function AiOrdersResponseBySourceInnerFromJSON(json: any): AiOrdersResponseBySourceInner {
    return AiOrdersResponseBySourceInnerFromJSONTyped(json, false);
}

export function AiOrdersResponseBySourceInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiOrdersResponseBySourceInner {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'name': json['name'],
        'orders': json['orders'],
        'revenue': json['revenue'],
    };
}

export function AiOrdersResponseBySourceInnerToJSON(json: any): AiOrdersResponseBySourceInner {
    return AiOrdersResponseBySourceInnerToJSONTyped(json, false);
}

export function AiOrdersResponseBySourceInnerToJSONTyped(value?: AiOrdersResponseBySourceInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'name': value['name'],
        'orders': value['orders'],
        'revenue': value['revenue'],
    };
}

