/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiOrdersResponseTotals
 */
export interface AiOrdersResponseTotals {
    /**
     * 
     * @type {number}
     * @memberof AiOrdersResponseTotals
     */
    orders: number;
    /**
     * Decimal amount with two decimals, e.g. 1834.20
     * @type {string}
     * @memberof AiOrdersResponseTotals
     */
    revenue: string;
}

/**
 * Check if a given object implements the AiOrdersResponseTotals interface.
 */
export function instanceOfAiOrdersResponseTotals(value: object): value is AiOrdersResponseTotals {
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    return true;
}

export function AiOrdersResponseTotalsFromJSON(json: any): AiOrdersResponseTotals {
    return AiOrdersResponseTotalsFromJSONTyped(json, false);
}

export function AiOrdersResponseTotalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiOrdersResponseTotals {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'],
        'revenue': json['revenue'],
    };
}

export function AiOrdersResponseTotalsToJSON(json: any): AiOrdersResponseTotals {
    return AiOrdersResponseTotalsToJSONTyped(json, false);
}

export function AiOrdersResponseTotalsToJSONTyped(value?: AiOrdersResponseTotals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'],
        'revenue': value['revenue'],
    };
}

