/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerDetailsLocale } from './AnswerDetailsLocale';
import {
    AnswerDetailsLocaleFromJSON,
    AnswerDetailsLocaleFromJSONTyped,
    AnswerDetailsLocaleToJSON,
    AnswerDetailsLocaleToJSONTyped,
} from './AnswerDetailsLocale';

/**
 * 
 * @export
 * @interface AnswerDetails
 */
export interface AnswerDetails {
    /**
     * 
     * @type {number}
     * @memberof AnswerDetails
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AnswerDetails
     */
    promptId?: number;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetails
     */
    promptText?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetails
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetails
     */
    response?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AnswerDetails
     */
    responseTruncated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AnswerDetails
     */
    executedAt?: Date | null;
    /**
     * Milliseconds, rounded to one decimal place
     * @type {number}
     * @memberof AnswerDetails
     */
    durationMs?: number | null;
    /**
     * Null while the answer is still pending
     * @type {boolean}
     * @memberof AnswerDetails
     */
    success?: boolean | null;
    /**
     * True for a sentinel non-answer (the provider returned nothing after retries); excluded from platform metrics
     * @type {boolean}
     * @memberof AnswerDetails
     */
    noResult?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnswerDetails
     */
    fanOutQueries?: Array<string> | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    mentions?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    citations?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    competitorMentions?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    competitorCitations?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    sentiments?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    sources?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    shoppingProducts?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    brandEntities?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnswerDetails
     */
    localBusinesses?: Array<object>;
    /**
     * 
     * @type {AnswerDetailsLocale}
     * @memberof AnswerDetails
     */
    locale?: AnswerDetailsLocale;
    /**
     * Opens this answer in the app. The link names its project, so it opens there for any user with access to that project
     * @type {string}
     * @memberof AnswerDetails
     */
    appUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerDetails
     */
    requestId?: string;
}

/**
 * Check if a given object implements the AnswerDetails interface.
 */
export function instanceOfAnswerDetails(value: object): value is AnswerDetails {
    return true;
}

export function AnswerDetailsFromJSON(json: any): AnswerDetails {
    return AnswerDetailsFromJSONTyped(json, false);
}

export function AnswerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'promptId': json['prompt_id'] == null ? undefined : json['prompt_id'],
        'promptText': json['prompt_text'] == null ? undefined : json['prompt_text'],
        'model': json['model'] == null ? undefined : json['model'],
        'response': json['response'] === undefined ? undefined : json['response'] === null ? null : json['response'],
        'responseTruncated': json['response_truncated'] == null ? undefined : json['response_truncated'],
        'executedAt': json['executed_at'] === undefined ? undefined : json['executed_at'] === null ? null : (new Date(json['executed_at'])),
        'durationMs': json['duration_ms'] === undefined ? undefined : json['duration_ms'] === null ? null : json['duration_ms'],
        'success': json['success'] === undefined ? undefined : json['success'] === null ? null : json['success'],
        'noResult': json['no_result'] == null ? undefined : json['no_result'],
        'fanOutQueries': json['fan_out_queries'] === undefined ? undefined : json['fan_out_queries'] === null ? null : json['fan_out_queries'],
        'mentions': json['mentions'] == null ? undefined : json['mentions'],
        'citations': json['citations'] == null ? undefined : json['citations'],
        'competitorMentions': json['competitor_mentions'] == null ? undefined : json['competitor_mentions'],
        'competitorCitations': json['competitor_citations'] == null ? undefined : json['competitor_citations'],
        'sentiments': json['sentiments'] == null ? undefined : json['sentiments'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'shoppingProducts': json['shopping_products'] == null ? undefined : json['shopping_products'],
        'brandEntities': json['brand_entities'] == null ? undefined : json['brand_entities'],
        'localBusinesses': json['local_businesses'] == null ? undefined : json['local_businesses'],
        'locale': json['locale'] == null ? undefined : AnswerDetailsLocaleFromJSON(json['locale']),
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function AnswerDetailsToJSON(json: any): AnswerDetails {
    return AnswerDetailsToJSONTyped(json, false);
}

export function AnswerDetailsToJSONTyped(value?: AnswerDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'prompt_id': value['promptId'],
        'prompt_text': value['promptText'],
        'model': value['model'],
        'response': value['response'],
        'response_truncated': value['responseTruncated'],
        'executed_at': value['executedAt'] == null ? value['executedAt'] : value['executedAt'].toISOString(),
        'duration_ms': value['durationMs'],
        'success': value['success'],
        'no_result': value['noResult'],
        'fan_out_queries': value['fanOutQueries'],
        'mentions': value['mentions'],
        'citations': value['citations'],
        'competitor_mentions': value['competitorMentions'],
        'competitor_citations': value['competitorCitations'],
        'sentiments': value['sentiments'],
        'sources': value['sources'],
        'shopping_products': value['shoppingProducts'],
        'brand_entities': value['brandEntities'],
        'local_businesses': value['localBusinesses'],
        'locale': AnswerDetailsLocaleToJSON(value['locale']),
        'app_url': value['appUrl'],
        'request_id': value['requestId'],
    };
}

