/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogPromptSuggestion } from './CatalogPromptSuggestion';
import {
    CatalogPromptSuggestionFromJSON,
    CatalogPromptSuggestionFromJSONTyped,
    CatalogPromptSuggestionToJSON,
    CatalogPromptSuggestionToJSONTyped,
} from './CatalogPromptSuggestion';

/**
 * 
 * @export
 * @interface CatalogPromptSuggestionsCreateResponse
 */
export interface CatalogPromptSuggestionsCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof CatalogPromptSuggestionsCreateResponse
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogPromptSuggestionsCreateResponse
     */
    created: number;
    /**
     * Generated prompts not saved because the project already holds them as a suggestion (from any source or product, in any status).
     * @type {number}
     * @memberof CatalogPromptSuggestionsCreateResponse
     */
    skipped: number;
    /**
     * 
     * @type {Array<CatalogPromptSuggestion>}
     * @memberof CatalogPromptSuggestionsCreateResponse
     */
    data: Array<CatalogPromptSuggestion>;
    /**
     * 
     * @type {string}
     * @memberof CatalogPromptSuggestionsCreateResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the CatalogPromptSuggestionsCreateResponse interface.
 */
export function instanceOfCatalogPromptSuggestionsCreateResponse(value: object): value is CatalogPromptSuggestionsCreateResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function CatalogPromptSuggestionsCreateResponseFromJSON(json: any): CatalogPromptSuggestionsCreateResponse {
    return CatalogPromptSuggestionsCreateResponseFromJSONTyped(json, false);
}

export function CatalogPromptSuggestionsCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogPromptSuggestionsCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'created': json['created'],
        'skipped': json['skipped'],
        'data': ((json['data'] as Array<any>).map(CatalogPromptSuggestionFromJSON)),
        'requestId': json['request_id'],
    };
}

export function CatalogPromptSuggestionsCreateResponseToJSON(json: any): CatalogPromptSuggestionsCreateResponse {
    return CatalogPromptSuggestionsCreateResponseToJSONTyped(json, false);
}

export function CatalogPromptSuggestionsCreateResponseToJSONTyped(value?: CatalogPromptSuggestionsCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'created': value['created'],
        'skipped': value['skipped'],
        'data': ((value['data'] as Array<any>).map(CatalogPromptSuggestionToJSON)),
        'request_id': value['requestId'],
    };
}

