/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogPromptSuggestionsAcceptResponseSkippedInner
 */
export interface CatalogPromptSuggestionsAcceptResponseSkippedInner {
    /**
     * 
     * @type {number}
     * @memberof CatalogPromptSuggestionsAcceptResponseSkippedInner
     */
    suggestionId: number;
    /**
     * accepted or rejected (the suggestion was no longer pending), or pending_deletion
     * @type {string}
     * @memberof CatalogPromptSuggestionsAcceptResponseSkippedInner
     */
    reason: string;
}

/**
 * Check if a given object implements the CatalogPromptSuggestionsAcceptResponseSkippedInner interface.
 */
export function instanceOfCatalogPromptSuggestionsAcceptResponseSkippedInner(value: object): value is CatalogPromptSuggestionsAcceptResponseSkippedInner {
    if ((!('suggestionId' in (value as Record<string, any>)) && !('suggestion_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['suggestionId'] === undefined && (value as Record<string, any>)['suggestion_id'] === undefined)) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function CatalogPromptSuggestionsAcceptResponseSkippedInnerFromJSON(json: any): CatalogPromptSuggestionsAcceptResponseSkippedInner {
    return CatalogPromptSuggestionsAcceptResponseSkippedInnerFromJSONTyped(json, false);
}

export function CatalogPromptSuggestionsAcceptResponseSkippedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogPromptSuggestionsAcceptResponseSkippedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestionId': json['suggestion_id'],
        'reason': json['reason'],
    };
}

export function CatalogPromptSuggestionsAcceptResponseSkippedInnerToJSON(json: any): CatalogPromptSuggestionsAcceptResponseSkippedInner {
    return CatalogPromptSuggestionsAcceptResponseSkippedInnerToJSONTyped(json, false);
}

export function CatalogPromptSuggestionsAcceptResponseSkippedInnerToJSONTyped(value?: CatalogPromptSuggestionsAcceptResponseSkippedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestion_id': value['suggestionId'],
        'reason': value['reason'],
    };
}

