/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogProduct
 */
export interface CatalogProduct {
    /**
     * The store's product id, e.g. gid://shopify/Product/1
     * @type {string}
     * @memberof CatalogProduct
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogProduct
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogProduct
     */
    handle?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogProduct
     */
    productType?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogProduct
     */
    vendor?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogProduct
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogProduct
     */
    collections?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogProduct
     */
    url?: string;
}

/**
 * Check if a given object implements the CatalogProduct interface.
 */
export function instanceOfCatalogProduct(value: object): value is CatalogProduct {
    if ((!('externalId' in (value as Record<string, any>)) && !('external_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['externalId'] === undefined && (value as Record<string, any>)['external_id'] === undefined)) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CatalogProductFromJSON(json: any): CatalogProduct {
    return CatalogProductFromJSONTyped(json, false);
}

export function CatalogProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'title': json['title'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'productType': json['product_type'] == null ? undefined : json['product_type'],
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'collections': json['collections'] == null ? undefined : json['collections'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CatalogProductToJSON(json: any): CatalogProduct {
    return CatalogProductToJSONTyped(json, false);
}

export function CatalogProductToJSONTyped(value?: CatalogProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'title': value['title'],
        'handle': value['handle'],
        'product_type': value['productType'],
        'vendor': value['vendor'],
        'tags': value['tags'],
        'collections': value['collections'],
        'url': value['url'],
    };
}

