/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogPromptSuggestionsAcceptResponseAcceptedInner
 */
export interface CatalogPromptSuggestionsAcceptResponseAcceptedInner {
    /**
     * 
     * @type {number}
     * @memberof CatalogPromptSuggestionsAcceptResponseAcceptedInner
     */
    suggestionId: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogPromptSuggestionsAcceptResponseAcceptedInner
     */
    promptId: number;
    /**
     * The collection named after the product; null when the product has no title or the team member cannot create tags
     * @type {number}
     * @memberof CatalogPromptSuggestionsAcceptResponseAcceptedInner
     */
    collectionId: number | null;
}

/**
 * Check if a given object implements the CatalogPromptSuggestionsAcceptResponseAcceptedInner interface.
 */
export function instanceOfCatalogPromptSuggestionsAcceptResponseAcceptedInner(value: object): value is CatalogPromptSuggestionsAcceptResponseAcceptedInner {
    if ((!('suggestionId' in (value as Record<string, any>)) && !('suggestion_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['suggestionId'] === undefined && (value as Record<string, any>)['suggestion_id'] === undefined)) return false;
    if ((!('promptId' in (value as Record<string, any>)) && !('prompt_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['promptId'] === undefined && (value as Record<string, any>)['prompt_id'] === undefined)) return false;
    if ((!('collectionId' in (value as Record<string, any>)) && !('collection_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['collectionId'] === undefined && (value as Record<string, any>)['collection_id'] === undefined)) return false;
    return true;
}

export function CatalogPromptSuggestionsAcceptResponseAcceptedInnerFromJSON(json: any): CatalogPromptSuggestionsAcceptResponseAcceptedInner {
    return CatalogPromptSuggestionsAcceptResponseAcceptedInnerFromJSONTyped(json, false);
}

export function CatalogPromptSuggestionsAcceptResponseAcceptedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogPromptSuggestionsAcceptResponseAcceptedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestionId': json['suggestion_id'],
        'promptId': json['prompt_id'],
        'collectionId': json['collection_id'],
    };
}

export function CatalogPromptSuggestionsAcceptResponseAcceptedInnerToJSON(json: any): CatalogPromptSuggestionsAcceptResponseAcceptedInner {
    return CatalogPromptSuggestionsAcceptResponseAcceptedInnerToJSONTyped(json, false);
}

export function CatalogPromptSuggestionsAcceptResponseAcceptedInnerToJSONTyped(value?: CatalogPromptSuggestionsAcceptResponseAcceptedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestion_id': value['suggestionId'],
        'prompt_id': value['promptId'],
        'collection_id': value['collectionId'],
    };
}

