/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompetitorMentionRecord } from './CompetitorMentionRecord';
import {
    CompetitorMentionRecordFromJSON,
    CompetitorMentionRecordFromJSONTyped,
    CompetitorMentionRecordToJSON,
    CompetitorMentionRecordToJSONTyped,
} from './CompetitorMentionRecord';

/**
 * 
 * @export
 * @interface CompetitorMentionsResponse
 */
export interface CompetitorMentionsResponse {
    /**
     * 
     * @type {number}
     * @memberof CompetitorMentionsResponse
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorMentionsResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorMentionsResponse
     */
    perPage: number;
    /**
     * Rows matching the filters across every page
     * @type {number}
     * @memberof CompetitorMentionsResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof CompetitorMentionsResponse
     */
    requestId: string;
    /**
     * 
     * @type {Array<CompetitorMentionRecord>}
     * @memberof CompetitorMentionsResponse
     */
    data: Array<CompetitorMentionRecord>;
}

/**
 * Check if a given object implements the CompetitorMentionsResponse interface.
 */
export function instanceOfCompetitorMentionsResponse(value: object): value is CompetitorMentionsResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if ((!('perPage' in (value as Record<string, any>)) && !('per_page' in (value as Record<string, any>))) || ((value as Record<string, any>)['perPage'] === undefined && (value as Record<string, any>)['per_page'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CompetitorMentionsResponseFromJSON(json: any): CompetitorMentionsResponse {
    return CompetitorMentionsResponseFromJSONTyped(json, false);
}

export function CompetitorMentionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitorMentionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'page': json['page'],
        'perPage': json['per_page'],
        'total': json['total'],
        'requestId': json['request_id'],
        'data': ((json['data'] as Array<any>).map(CompetitorMentionRecordFromJSON)),
    };
}

export function CompetitorMentionsResponseToJSON(json: any): CompetitorMentionsResponse {
    return CompetitorMentionsResponseToJSONTyped(json, false);
}

export function CompetitorMentionsResponseToJSONTyped(value?: CompetitorMentionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'request_id': value['requestId'],
        'data': ((value['data'] as Array<any>).map(CompetitorMentionRecordToJSON)),
    };
}

