/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitorDetails
 */
export interface CompetitorDetails {
    /**
     * 
     * @type {number}
     * @memberof CompetitorDetails
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CompetitorDetails
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDetails
     */
    brandName?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDetails
     */
    domain?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitorDetails
     */
    matchingNames?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDetails
     */
    googlePlayId?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDetails
     */
    appStoreId?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitorDetails
     */
    color?: string;
    /**
     * 
     * @type {Date}
     * @memberof CompetitorDetails
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CompetitorDetails interface.
 */
export function instanceOfCompetitorDetails(value: object): value is CompetitorDetails {
    return true;
}

export function CompetitorDetailsFromJSON(json: any): CompetitorDetails {
    return CompetitorDetailsFromJSONTyped(json, false);
}

export function CompetitorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'matchingNames': json['matching_names'] == null ? undefined : json['matching_names'],
        'googlePlayId': json['google_play_id'] == null ? undefined : json['google_play_id'],
        'appStoreId': json['app_store_id'] == null ? undefined : json['app_store_id'],
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function CompetitorDetailsToJSON(json: any): CompetitorDetails {
    return CompetitorDetailsToJSONTyped(json, false);
}

export function CompetitorDetailsToJSONTyped(value?: CompetitorDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'brand_name': value['brandName'],
        'domain': value['domain'],
        'matching_names': value['matchingNames'],
        'google_play_id': value['googlePlayId'],
        'app_store_id': value['appStoreId'],
        'color': value['color'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

