/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoAuditComparisonChangesInner
 */
export interface GeoAuditComparisonChangesInner {
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    checkKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    checkTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    subjectKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    severity?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    fromStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditComparisonChangesInner
     */
    toStatus?: string | null;
    /**
     * 
     * @type {GeoAuditComparisonChangesInnerChangeEnum}
     * @memberof GeoAuditComparisonChangesInner
     */
    change?: GeoAuditComparisonChangesInnerChangeEnum;
}


/**
 * @export
 */
export const GeoAuditComparisonChangesInnerChangeEnum = {
    New: 'new',
    Fixed: 'fixed',
    Changed: 'changed',
    Appeared: 'appeared',
    Disappeared: 'disappeared',
    Unchanged: 'unchanged'
} as const;
export type GeoAuditComparisonChangesInnerChangeEnum = typeof GeoAuditComparisonChangesInnerChangeEnum[keyof typeof GeoAuditComparisonChangesInnerChangeEnum];


/**
 * Check if a given object implements the GeoAuditComparisonChangesInner interface.
 */
export function instanceOfGeoAuditComparisonChangesInner(value: object): value is GeoAuditComparisonChangesInner {
    return true;
}

export function GeoAuditComparisonChangesInnerFromJSON(json: any): GeoAuditComparisonChangesInner {
    return GeoAuditComparisonChangesInnerFromJSONTyped(json, false);
}

export function GeoAuditComparisonChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditComparisonChangesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'checkKey': json['check_key'] == null ? undefined : json['check_key'],
        'checkTitle': json['check_title'] === undefined ? undefined : json['check_title'] === null ? null : json['check_title'],
        'subjectKey': json['subject_key'] == null ? undefined : json['subject_key'],
        'subject': json['subject'] === undefined ? undefined : json['subject'] === null ? null : json['subject'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'fromStatus': json['from_status'] === undefined ? undefined : json['from_status'] === null ? null : json['from_status'],
        'toStatus': json['to_status'] === undefined ? undefined : json['to_status'] === null ? null : json['to_status'],
        'change': json['change'] == null ? undefined : json['change'],
    };
}

export function GeoAuditComparisonChangesInnerToJSON(json: any): GeoAuditComparisonChangesInner {
    return GeoAuditComparisonChangesInnerToJSONTyped(json, false);
}

export function GeoAuditComparisonChangesInnerToJSONTyped(value?: GeoAuditComparisonChangesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_key': value['checkKey'],
        'check_title': value['checkTitle'],
        'subject_key': value['subjectKey'],
        'subject': value['subject'],
        'severity': value['severity'],
        'from_status': value['fromStatus'],
        'to_status': value['toStatus'],
        'change': value['change'],
    };
}

