/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoAlertEventsInner } from './GeoAlertEventsInner';
import {
    GeoAlertEventsInnerFromJSON,
    GeoAlertEventsInnerFromJSONTyped,
    GeoAlertEventsInnerToJSON,
    GeoAlertEventsInnerToJSONTyped,
} from './GeoAlertEventsInner';

/**
 * 
 * @export
 * @interface GeoAlert
 */
export interface GeoAlert {
    /**
     * 
     * @type {number}
     * @memberof GeoAlert
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GeoAlert
     */
    auditId?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAlert
     */
    auditType?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAlert
     */
    target?: string;
    /**
     * 
     * @type {number}
     * @memberof GeoAlert
     */
    runSequence?: number;
    /**
     * 
     * @type {string}
     * @memberof GeoAlert
     */
    severity?: string;
    /**
     * 
     * @type {Array<GeoAlertEventsInner>}
     * @memberof GeoAlert
     */
    events?: Array<GeoAlertEventsInner>;
    /**
     * 
     * @type {Date}
     * @memberof GeoAlert
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GeoAlert
     */
    appUrl?: string;
}

/**
 * Check if a given object implements the GeoAlert interface.
 */
export function instanceOfGeoAlert(value: object): value is GeoAlert {
    return true;
}

export function GeoAlertFromJSON(json: any): GeoAlert {
    return GeoAlertFromJSONTyped(json, false);
}

export function GeoAlertFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAlert {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'auditId': json['audit_id'] == null ? undefined : json['audit_id'],
        'auditType': json['audit_type'] == null ? undefined : json['audit_type'],
        'target': json['target'] == null ? undefined : json['target'],
        'runSequence': json['run_sequence'] == null ? undefined : json['run_sequence'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(GeoAlertEventsInnerFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
    };
}

export function GeoAlertToJSON(json: any): GeoAlert {
    return GeoAlertToJSONTyped(json, false);
}

export function GeoAlertToJSONTyped(value?: GeoAlert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'audit_id': value['auditId'],
        'audit_type': value['auditType'],
        'target': value['target'],
        'run_sequence': value['runSequence'],
        'severity': value['severity'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(GeoAlertEventsInnerToJSON)),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'app_url': value['appUrl'],
    };
}

