/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoAuditCreateRequest
 */
export interface GeoAuditCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof GeoAuditCreateRequest
     */
    projectId: number;
    /**
     * The domain (site-wide types) or page URL to audit
     * @type {string}
     * @memberof GeoAuditCreateRequest
     */
    target: string;
    /**
     * One or more audit types; each becomes its own audit and starts its first run
     * @type {Array<GeoAuditCreateRequestAuditTypesEnum>}
     * @memberof GeoAuditCreateRequest
     */
    auditTypes: Array<GeoAuditCreateRequestAuditTypesEnum>;
    /**
     * once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
     * @type {GeoAuditCreateRequestCadenceEnum}
     * @memberof GeoAuditCreateRequest
     */
    cadence?: GeoAuditCreateRequestCadenceEnum;
}


/**
 * @export
 */
export const GeoAuditCreateRequestAuditTypesEnum = {
    AgentReadiness: 'agent_readiness',
    RobotsTxt: 'robots_txt',
    Crawlability: 'crawlability',
    Schema: 'schema',
    ContentReadiness: 'content_readiness',
    Discoverability: 'discoverability',
    SiteStructure: 'site_structure'
} as const;
export type GeoAuditCreateRequestAuditTypesEnum = typeof GeoAuditCreateRequestAuditTypesEnum[keyof typeof GeoAuditCreateRequestAuditTypesEnum];

/**
 * @export
 */
export const GeoAuditCreateRequestCadenceEnum = {
    Once: 'once',
    Weekly: 'weekly',
    Monthly: 'monthly'
} as const;
export type GeoAuditCreateRequestCadenceEnum = typeof GeoAuditCreateRequestCadenceEnum[keyof typeof GeoAuditCreateRequestCadenceEnum];


/**
 * Check if a given object implements the GeoAuditCreateRequest interface.
 */
export function instanceOfGeoAuditCreateRequest(value: object): value is GeoAuditCreateRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if ((!('auditTypes' in (value as Record<string, any>)) && !('audit_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['auditTypes'] === undefined && (value as Record<string, any>)['audit_types'] === undefined)) return false;
    return true;
}

export function GeoAuditCreateRequestFromJSON(json: any): GeoAuditCreateRequest {
    return GeoAuditCreateRequestFromJSONTyped(json, false);
}

export function GeoAuditCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'target': json['target'],
        'auditTypes': json['audit_types'],
        'cadence': json['cadence'] == null ? undefined : json['cadence'],
    };
}

export function GeoAuditCreateRequestToJSON(json: any): GeoAuditCreateRequest {
    return GeoAuditCreateRequestToJSONTyped(json, false);
}

export function GeoAuditCreateRequestToJSONTyped(value?: GeoAuditCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'target': value['target'],
        'audit_types': value['auditTypes'],
        'cadence': value['cadence'],
    };
}

