/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoAuditIssueUpdateRequest
 */
export interface GeoAuditIssueUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof GeoAuditIssueUpdateRequest
     */
    projectId?: number;
    /**
     * true accepts the issue (it stays listed but leaves the open count until its evidence changes); false reopens it
     * @type {boolean}
     * @memberof GeoAuditIssueUpdateRequest
     */
    accepted: boolean;
}

/**
 * Check if a given object implements the GeoAuditIssueUpdateRequest interface.
 */
export function instanceOfGeoAuditIssueUpdateRequest(value: object): value is GeoAuditIssueUpdateRequest {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    return true;
}

export function GeoAuditIssueUpdateRequestFromJSON(json: any): GeoAuditIssueUpdateRequest {
    return GeoAuditIssueUpdateRequestFromJSONTyped(json, false);
}

export function GeoAuditIssueUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditIssueUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'accepted': json['accepted'],
    };
}

export function GeoAuditIssueUpdateRequestToJSON(json: any): GeoAuditIssueUpdateRequest {
    return GeoAuditIssueUpdateRequestToJSONTyped(json, false);
}

export function GeoAuditIssueUpdateRequestToJSONTyped(value?: GeoAuditIssueUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'accepted': value['accepted'],
    };
}

