/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoAuditRun } from './GeoAuditRun';
import {
    GeoAuditRunFromJSON,
    GeoAuditRunFromJSONTyped,
    GeoAuditRunToJSON,
    GeoAuditRunToJSONTyped,
} from './GeoAuditRun';

/**
 * 
 * @export
 * @interface GeoAuditRunList
 */
export interface GeoAuditRunList {
    /**
     * 
     * @type {number}
     * @memberof GeoAuditRunList
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditRunList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditRunList
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditRunList
     */
    total?: number;
    /**
     * 
     * @type {Array<GeoAuditRun>}
     * @memberof GeoAuditRunList
     */
    data?: Array<GeoAuditRun>;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditRunList
     */
    requestId?: string;
}

/**
 * Check if a given object implements the GeoAuditRunList interface.
 */
export function instanceOfGeoAuditRunList(value: object): value is GeoAuditRunList {
    return true;
}

export function GeoAuditRunListFromJSON(json: any): GeoAuditRunList {
    return GeoAuditRunListFromJSONTyped(json, false);
}

export function GeoAuditRunListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditRunList {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GeoAuditRunFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function GeoAuditRunListToJSON(json: any): GeoAuditRunList {
    return GeoAuditRunListToJSONTyped(json, false);
}

export function GeoAuditRunListToJSONTyped(value?: GeoAuditRunList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GeoAuditRunToJSON)),
        'request_id': value['requestId'],
    };
}

