/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoAuditRun } from './GeoAuditRun';
import {
    GeoAuditRunFromJSON,
    GeoAuditRunFromJSONTyped,
    GeoAuditRunToJSON,
    GeoAuditRunToJSONTyped,
} from './GeoAuditRun';
import type { GeoAuditSchedule } from './GeoAuditSchedule';
import {
    GeoAuditScheduleFromJSON,
    GeoAuditScheduleFromJSONTyped,
    GeoAuditScheduleToJSON,
    GeoAuditScheduleToJSONTyped,
} from './GeoAuditSchedule';

/**
 * 
 * @export
 * @interface GeoAuditResponse
 */
export interface GeoAuditResponse {
    /**
     * Stable audit id
     * @type {string}
     * @memberof GeoAuditResponse
     */
    id?: string;
    /**
     * 
     * @type {GeoAuditResponseAuditTypeEnum}
     * @memberof GeoAuditResponse
     */
    auditType?: GeoAuditResponseAuditTypeEnum;
    /**
     * The audited domain (site-wide types) or page URL, normalized
     * @type {string}
     * @memberof GeoAuditResponse
     */
    target?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditResponse
     */
    countryCode?: string | null;
    /**
     * 
     * @type {GeoAuditResponseCadenceEnum}
     * @memberof GeoAuditResponse
     */
    cadence?: GeoAuditResponseCadenceEnum;
    /**
     * 
     * @type {GeoAuditResponseStatusEnum}
     * @memberof GeoAuditResponse
     */
    status?: GeoAuditResponseStatusEnum;
    /**
     * user, or unreachable when three runs in a row could not reach the site
     * @type {string}
     * @memberof GeoAuditResponse
     */
    pausedReason?: string | null;
    /**
     * 
     * @type {GeoAuditSchedule}
     * @memberof GeoAuditResponse
     */
    schedule?: GeoAuditSchedule | null;
    /**
     * 
     * @type {Date}
     * @memberof GeoAuditResponse
     */
    nextRunAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GeoAuditResponse
     */
    emailAlerts?: boolean;
    /**
     * Whether this audit type can run weekly or monthly
     * @type {boolean}
     * @memberof GeoAuditResponse
     */
    recurringAvailable?: boolean;
    /**
     * Whether runs of this type produce findings and issues, or a score only
     * @type {boolean}
     * @memberof GeoAuditResponse
     */
    checksTracked?: boolean;
    /**
     * 
     * @type {GeoAuditRun}
     * @memberof GeoAuditResponse
     */
    latestRun?: GeoAuditRun | null;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditResponse
     */
    openIssues?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditResponse
     */
    openCriticalIssues?: number;
    /**
     * 
     * @type {Date}
     * @memberof GeoAuditResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditResponse
     */
    appUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditResponse
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditResponse
     */
    requestId?: string;
}


/**
 * @export
 */
export const GeoAuditResponseAuditTypeEnum = {
    AgentReadiness: 'agent_readiness',
    RobotsTxt: 'robots_txt',
    Crawlability: 'crawlability',
    Schema: 'schema',
    ContentReadiness: 'content_readiness',
    Discoverability: 'discoverability',
    SiteStructure: 'site_structure'
} as const;
export type GeoAuditResponseAuditTypeEnum = typeof GeoAuditResponseAuditTypeEnum[keyof typeof GeoAuditResponseAuditTypeEnum];

/**
 * @export
 */
export const GeoAuditResponseCadenceEnum = {
    Once: 'once',
    Weekly: 'weekly',
    Monthly: 'monthly'
} as const;
export type GeoAuditResponseCadenceEnum = typeof GeoAuditResponseCadenceEnum[keyof typeof GeoAuditResponseCadenceEnum];

/**
 * @export
 */
export const GeoAuditResponseStatusEnum = {
    Active: 'active',
    Paused: 'paused',
    Archived: 'archived'
} as const;
export type GeoAuditResponseStatusEnum = typeof GeoAuditResponseStatusEnum[keyof typeof GeoAuditResponseStatusEnum];


/**
 * Check if a given object implements the GeoAuditResponse interface.
 */
export function instanceOfGeoAuditResponse(value: object): value is GeoAuditResponse {
    return true;
}

export function GeoAuditResponseFromJSON(json: any): GeoAuditResponse {
    return GeoAuditResponseFromJSONTyped(json, false);
}

export function GeoAuditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'auditType': json['audit_type'] == null ? undefined : json['audit_type'],
        'target': json['target'] == null ? undefined : json['target'],
        'countryCode': json['country_code'] === undefined ? undefined : json['country_code'] === null ? null : json['country_code'],
        'cadence': json['cadence'] == null ? undefined : json['cadence'],
        'status': json['status'] == null ? undefined : json['status'],
        'pausedReason': json['paused_reason'] === undefined ? undefined : json['paused_reason'] === null ? null : json['paused_reason'],
        'schedule': json['schedule'] === undefined ? undefined : json['schedule'] === null ? null : GeoAuditScheduleFromJSON(json['schedule']),
        'nextRunAt': json['next_run_at'] === undefined ? undefined : json['next_run_at'] === null ? null : (new Date(json['next_run_at'])),
        'emailAlerts': json['email_alerts'] == null ? undefined : json['email_alerts'],
        'recurringAvailable': json['recurring_available'] == null ? undefined : json['recurring_available'],
        'checksTracked': json['checks_tracked'] == null ? undefined : json['checks_tracked'],
        'latestRun': json['latest_run'] === undefined ? undefined : json['latest_run'] === null ? null : GeoAuditRunFromJSON(json['latest_run']),
        'openIssues': json['open_issues'] == null ? undefined : json['open_issues'],
        'openCriticalIssues': json['open_critical_issues'] == null ? undefined : json['open_critical_issues'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function GeoAuditResponseToJSON(json: any): GeoAuditResponse {
    return GeoAuditResponseToJSONTyped(json, false);
}

export function GeoAuditResponseToJSONTyped(value?: GeoAuditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'audit_type': value['auditType'],
        'target': value['target'],
        'country_code': value['countryCode'],
        'cadence': value['cadence'],
        'status': value['status'],
        'paused_reason': value['pausedReason'],
        'schedule': GeoAuditScheduleToJSON(value['schedule']),
        'next_run_at': value['nextRunAt'] == null ? value['nextRunAt'] : value['nextRunAt'].toISOString(),
        'email_alerts': value['emailAlerts'],
        'recurring_available': value['recurringAvailable'],
        'checks_tracked': value['checksTracked'],
        'latest_run': GeoAuditRunToJSON(value['latestRun']),
        'open_issues': value['openIssues'],
        'open_critical_issues': value['openCriticalIssues'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'app_url': value['appUrl'],
        'project_id': value['projectId'],
        'request_id': value['requestId'],
    };
}

