/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoAuditIssueResponse
 */
export interface GeoAuditIssueResponse {
    /**
     * 
     * @type {number}
     * @memberof GeoAuditIssueResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    checkKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    checkTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    subjectKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    severity?: string;
    /**
     * 
     * @type {GeoAuditIssueResponseStateEnum}
     * @memberof GeoAuditIssueResponse
     */
    state?: GeoAuditIssueResponseStateEnum;
    /**
     * How the latest comparable run moved the issue
     * @type {GeoAuditIssueResponseBadgeEnum}
     * @memberof GeoAuditIssueResponse
     */
    badge?: GeoAuditIssueResponseBadgeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof GeoAuditIssueResponse
     */
    accepted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GeoAuditIssueResponse
     */
    acceptedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditIssueResponse
     */
    regressionCount?: number;
    /**
     * 
     * @type {object}
     * @memberof GeoAuditIssueResponse
     */
    evidence?: object;
    /**
     * 
     * @type {Date}
     * @memberof GeoAuditIssueResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditIssueResponse
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditIssueResponse
     */
    requestId?: string;
}


/**
 * @export
 */
export const GeoAuditIssueResponseStateEnum = {
    Open: 'open',
    Fixed: 'fixed',
    Gone: 'gone'
} as const;
export type GeoAuditIssueResponseStateEnum = typeof GeoAuditIssueResponseStateEnum[keyof typeof GeoAuditIssueResponseStateEnum];

/**
 * @export
 */
export const GeoAuditIssueResponseBadgeEnum = {
    New: 'new',
    Persisting: 'persisting',
    Regressed: 'regressed',
    Fixed: 'fixed',
    Gone: 'gone'
} as const;
export type GeoAuditIssueResponseBadgeEnum = typeof GeoAuditIssueResponseBadgeEnum[keyof typeof GeoAuditIssueResponseBadgeEnum];


/**
 * Check if a given object implements the GeoAuditIssueResponse interface.
 */
export function instanceOfGeoAuditIssueResponse(value: object): value is GeoAuditIssueResponse {
    return true;
}

export function GeoAuditIssueResponseFromJSON(json: any): GeoAuditIssueResponse {
    return GeoAuditIssueResponseFromJSONTyped(json, false);
}

export function GeoAuditIssueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditIssueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'checkKey': json['check_key'] == null ? undefined : json['check_key'],
        'checkTitle': json['check_title'] === undefined ? undefined : json['check_title'] === null ? null : json['check_title'],
        'subjectKey': json['subject_key'] == null ? undefined : json['subject_key'],
        'subject': json['subject'] === undefined ? undefined : json['subject'] === null ? null : json['subject'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'state': json['state'] == null ? undefined : json['state'],
        'badge': json['badge'] == null ? undefined : json['badge'],
        'accepted': json['accepted'] == null ? undefined : json['accepted'],
        'acceptedAt': json['accepted_at'] === undefined ? undefined : json['accepted_at'] === null ? null : (new Date(json['accepted_at'])),
        'regressionCount': json['regression_count'] == null ? undefined : json['regression_count'],
        'evidence': json['evidence'] == null ? undefined : json['evidence'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function GeoAuditIssueResponseToJSON(json: any): GeoAuditIssueResponse {
    return GeoAuditIssueResponseToJSONTyped(json, false);
}

export function GeoAuditIssueResponseToJSONTyped(value?: GeoAuditIssueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'check_key': value['checkKey'],
        'check_title': value['checkTitle'],
        'subject_key': value['subjectKey'],
        'subject': value['subject'],
        'severity': value['severity'],
        'state': value['state'],
        'badge': value['badge'],
        'accepted': value['accepted'],
        'accepted_at': value['acceptedAt'] == null ? value['acceptedAt'] : value['acceptedAt'].toISOString(),
        'regression_count': value['regressionCount'],
        'evidence': value['evidence'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'project_id': value['projectId'],
        'request_id': value['requestId'],
    };
}

