/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoAuditFinding } from './GeoAuditFinding';
import {
    GeoAuditFindingFromJSON,
    GeoAuditFindingFromJSONTyped,
    GeoAuditFindingToJSON,
    GeoAuditFindingToJSONTyped,
} from './GeoAuditFinding';

/**
 * 
 * @export
 * @interface GeoAuditFindingList
 */
export interface GeoAuditFindingList {
    /**
     * 
     * @type {number}
     * @memberof GeoAuditFindingList
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditFindingList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditFindingList
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GeoAuditFindingList
     */
    total?: number;
    /**
     * 
     * @type {Array<GeoAuditFinding>}
     * @memberof GeoAuditFindingList
     */
    data?: Array<GeoAuditFinding>;
    /**
     * 
     * @type {string}
     * @memberof GeoAuditFindingList
     */
    requestId?: string;
}

/**
 * Check if a given object implements the GeoAuditFindingList interface.
 */
export function instanceOfGeoAuditFindingList(value: object): value is GeoAuditFindingList {
    return true;
}

export function GeoAuditFindingListFromJSON(json: any): GeoAuditFindingList {
    return GeoAuditFindingListFromJSONTyped(json, false);
}

export function GeoAuditFindingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoAuditFindingList {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GeoAuditFindingFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function GeoAuditFindingListToJSON(json: any): GeoAuditFindingList {
    return GeoAuditFindingListToJSONTyped(json, false);
}

export function GeoAuditFindingListToJSONTyped(value?: GeoAuditFindingList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GeoAuditFindingToJSON)),
        'request_id': value['requestId'],
    };
}

