/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.49.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAccount200ResponseRateLimits } from './GetAccount200ResponseRateLimits';
import {
    GetAccount200ResponseRateLimitsFromJSON,
    GetAccount200ResponseRateLimitsFromJSONTyped,
    GetAccount200ResponseRateLimitsToJSON,
    GetAccount200ResponseRateLimitsToJSONTyped,
} from './GetAccount200ResponseRateLimits';
import type { GetAccount200ResponseSubscription } from './GetAccount200ResponseSubscription';
import {
    GetAccount200ResponseSubscriptionFromJSON,
    GetAccount200ResponseSubscriptionFromJSONTyped,
    GetAccount200ResponseSubscriptionToJSON,
    GetAccount200ResponseSubscriptionToJSONTyped,
} from './GetAccount200ResponseSubscription';
import type { GetAccount200ResponseLimits } from './GetAccount200ResponseLimits';
import {
    GetAccount200ResponseLimitsFromJSON,
    GetAccount200ResponseLimitsFromJSONTyped,
    GetAccount200ResponseLimitsToJSON,
    GetAccount200ResponseLimitsToJSONTyped,
} from './GetAccount200ResponseLimits';

/**
 * 
 * @export
 * @interface GetAccount200Response
 */
export interface GetAccount200Response {
    /**
     * Plan key (starter, growth, scale, ...)
     * @type {string}
     * @memberof GetAccount200Response
     */
    plan?: string;
    /**
     * How often prompts run (weekly, daily, monthly, ...)
     * @type {string}
     * @memberof GetAccount200Response
     */
    trackingFrequency?: string;
    /**
     * Whether the key belongs to the account owner or a team member
     * @type {GetAccount200ResponseRoleEnum}
     * @memberof GetAccount200Response
     */
    role?: GetAccount200ResponseRoleEnum;
    /**
     * 
     * @type {GetAccount200ResponseSubscription}
     * @memberof GetAccount200Response
     */
    subscription?: GetAccount200ResponseSubscription;
    /**
     * 
     * @type {GetAccount200ResponseLimits}
     * @memberof GetAccount200Response
     */
    limits?: GetAccount200ResponseLimits;
    /**
     * 
     * @type {GetAccount200ResponseRateLimits}
     * @memberof GetAccount200Response
     */
    rateLimits?: GetAccount200ResponseRateLimits;
    /**
     * 
     * @type {string}
     * @memberof GetAccount200Response
     */
    requestId?: string;
}


/**
 * @export
 */
export const GetAccount200ResponseRoleEnum = {
    Owner: 'owner',
    Member: 'member'
} as const;
export type GetAccount200ResponseRoleEnum = typeof GetAccount200ResponseRoleEnum[keyof typeof GetAccount200ResponseRoleEnum];


/**
 * Check if a given object implements the GetAccount200Response interface.
 */
export function instanceOfGetAccount200Response(value: object): value is GetAccount200Response {
    return true;
}

export function GetAccount200ResponseFromJSON(json: any): GetAccount200Response {
    return GetAccount200ResponseFromJSONTyped(json, false);
}

export function GetAccount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccount200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'plan': json['plan'] == null ? undefined : json['plan'],
        'trackingFrequency': json['tracking_frequency'] == null ? undefined : json['tracking_frequency'],
        'role': json['role'] == null ? undefined : json['role'],
        'subscription': json['subscription'] == null ? undefined : GetAccount200ResponseSubscriptionFromJSON(json['subscription']),
        'limits': json['limits'] == null ? undefined : GetAccount200ResponseLimitsFromJSON(json['limits']),
        'rateLimits': json['rate_limits'] == null ? undefined : GetAccount200ResponseRateLimitsFromJSON(json['rate_limits']),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function GetAccount200ResponseToJSON(json: any): GetAccount200Response {
    return GetAccount200ResponseToJSONTyped(json, false);
}

export function GetAccount200ResponseToJSONTyped(value?: GetAccount200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan': value['plan'],
        'tracking_frequency': value['trackingFrequency'],
        'role': value['role'],
        'subscription': GetAccount200ResponseSubscriptionToJSON(value['subscription']),
        'limits': GetAccount200ResponseLimitsToJSON(value['limits']),
        'rate_limits': GetAccount200ResponseRateLimitsToJSON(value['rateLimits']),
        'request_id': value['requestId'],
    };
}

