/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntelligenceTaskUpdateResponse
 */
export interface IntelligenceTaskUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTaskUpdateResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    publicId?: string;
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTaskUpdateResponse
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    taskType?: string;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTaskUpdateResponse
     */
    promptId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    promptText?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IntelligenceTaskUpdateResponse
     */
    agenticMode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    customTopic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    userInstructions?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    outputLanguageCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTaskUpdateResponse
     */
    wordCount?: number | null;
    /**
     * The generated content once status is completed; null before that. A product_listing task returns title, summary, description_html (p, ul, ol, li, strong, em, h3 and br only), faq (question and answer pairs), seo_title, seo_description, image_alts (image_id and alt), changes (field and reason) and labels
     * @type {object}
     * @memberof IntelligenceTaskUpdateResponse
     */
    resultData?: object | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    estimatedTime?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IntelligenceTaskUpdateResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IntelligenceTaskUpdateResponse
     */
    processedAt?: Date | null;
    /**
     * When the content was last edited by hand; null while the output is as generated
     * @type {Date}
     * @memberof IntelligenceTaskUpdateResponse
     */
    manuallyEditedAt?: Date | null;
    /**
     * User behind the last manual edit; null for an unedited task or an edit made from an embedded portal
     * @type {number}
     * @memberof IntelligenceTaskUpdateResponse
     */
    editedByUserId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTaskUpdateResponse
     */
    requestId?: string;
    /**
     * Paths whose text actually changed; empty when every value matched the stored text
     * @type {Array<string>}
     * @memberof IntelligenceTaskUpdateResponse
     */
    changedPaths?: Array<string>;
}

/**
 * Check if a given object implements the IntelligenceTaskUpdateResponse interface.
 */
export function instanceOfIntelligenceTaskUpdateResponse(value: object): value is IntelligenceTaskUpdateResponse {
    return true;
}

export function IntelligenceTaskUpdateResponseFromJSON(json: any): IntelligenceTaskUpdateResponse {
    return IntelligenceTaskUpdateResponseFromJSONTyped(json, false);
}

export function IntelligenceTaskUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntelligenceTaskUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'publicId': json['public_id'] == null ? undefined : json['public_id'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'taskType': json['task_type'] == null ? undefined : json['task_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'promptId': json['prompt_id'] === undefined ? undefined : json['prompt_id'] === null ? null : json['prompt_id'],
        'promptText': json['prompt_text'] === undefined ? undefined : json['prompt_text'] === null ? null : json['prompt_text'],
        'agenticMode': json['agentic_mode'] == null ? undefined : json['agentic_mode'],
        'customTopic': json['custom_topic'] === undefined ? undefined : json['custom_topic'] === null ? null : json['custom_topic'],
        'userInstructions': json['user_instructions'] === undefined ? undefined : json['user_instructions'] === null ? null : json['user_instructions'],
        'outputLanguageCode': json['output_language_code'] === undefined ? undefined : json['output_language_code'] === null ? null : json['output_language_code'],
        'wordCount': json['word_count'] === undefined ? undefined : json['word_count'] === null ? null : json['word_count'],
        'resultData': json['result_data'] === undefined ? undefined : json['result_data'] === null ? null : json['result_data'],
        'errorMessage': json['error_message'] === undefined ? undefined : json['error_message'] === null ? null : json['error_message'],
        'estimatedTime': json['estimated_time'] === undefined ? undefined : json['estimated_time'] === null ? null : json['estimated_time'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'processedAt': json['processed_at'] === undefined ? undefined : json['processed_at'] === null ? null : (new Date(json['processed_at'])),
        'manuallyEditedAt': json['manually_edited_at'] === undefined ? undefined : json['manually_edited_at'] === null ? null : (new Date(json['manually_edited_at'])),
        'editedByUserId': json['edited_by_user_id'] === undefined ? undefined : json['edited_by_user_id'] === null ? null : json['edited_by_user_id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'changedPaths': json['changed_paths'] == null ? undefined : json['changed_paths'],
    };
}

export function IntelligenceTaskUpdateResponseToJSON(json: any): IntelligenceTaskUpdateResponse {
    return IntelligenceTaskUpdateResponseToJSONTyped(json, false);
}

export function IntelligenceTaskUpdateResponseToJSONTyped(value?: IntelligenceTaskUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'public_id': value['publicId'],
        'project_id': value['projectId'],
        'task_type': value['taskType'],
        'title': value['title'],
        'status': value['status'],
        'prompt_id': value['promptId'],
        'prompt_text': value['promptText'],
        'agentic_mode': value['agenticMode'],
        'custom_topic': value['customTopic'],
        'user_instructions': value['userInstructions'],
        'output_language_code': value['outputLanguageCode'],
        'word_count': value['wordCount'],
        'result_data': value['resultData'],
        'error_message': value['errorMessage'],
        'estimated_time': value['estimatedTime'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'processed_at': value['processedAt'] == null ? value['processedAt'] : value['processedAt'].toISOString(),
        'manually_edited_at': value['manuallyEditedAt'] == null ? value['manuallyEditedAt'] : value['manuallyEditedAt'].toISOString(),
        'edited_by_user_id': value['editedByUserId'],
        'request_id': value['requestId'],
        'changed_paths': value['changedPaths'],
    };
}

