/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntelligenceTaskSummary } from './IntelligenceTaskSummary';
import {
    IntelligenceTaskSummaryFromJSON,
    IntelligenceTaskSummaryFromJSONTyped,
    IntelligenceTaskSummaryToJSON,
    IntelligenceTaskSummaryToJSONTyped,
} from './IntelligenceTaskSummary';

/**
 * 
 * @export
 * @interface IntelligenceTasksResponse
 */
export interface IntelligenceTasksResponse {
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTasksResponse
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTasksResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof IntelligenceTasksResponse
     */
    perPage: number;
    /**
     * Rows matching the filters across every page
     * @type {number}
     * @memberof IntelligenceTasksResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof IntelligenceTasksResponse
     */
    requestId: string;
    /**
     * 
     * @type {Array<IntelligenceTaskSummary>}
     * @memberof IntelligenceTasksResponse
     */
    data: Array<IntelligenceTaskSummary>;
}

/**
 * Check if a given object implements the IntelligenceTasksResponse interface.
 */
export function instanceOfIntelligenceTasksResponse(value: object): value is IntelligenceTasksResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if ((!('perPage' in (value as Record<string, any>)) && !('per_page' in (value as Record<string, any>))) || ((value as Record<string, any>)['perPage'] === undefined && (value as Record<string, any>)['per_page'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function IntelligenceTasksResponseFromJSON(json: any): IntelligenceTasksResponse {
    return IntelligenceTasksResponseFromJSONTyped(json, false);
}

export function IntelligenceTasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntelligenceTasksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'page': json['page'],
        'perPage': json['per_page'],
        'total': json['total'],
        'requestId': json['request_id'],
        'data': ((json['data'] as Array<any>).map(IntelligenceTaskSummaryFromJSON)),
    };
}

export function IntelligenceTasksResponseToJSON(json: any): IntelligenceTasksResponse {
    return IntelligenceTasksResponseToJSONTyped(json, false);
}

export function IntelligenceTasksResponseToJSONTyped(value?: IntelligenceTasksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'request_id': value['requestId'],
        'data': ((value['data'] as Array<any>).map(IntelligenceTaskSummaryToJSON)),
    };
}

