/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListWebhooks200ResponseDataInner } from './ListWebhooks200ResponseDataInner';
import {
    ListWebhooks200ResponseDataInnerFromJSON,
    ListWebhooks200ResponseDataInnerFromJSONTyped,
    ListWebhooks200ResponseDataInnerToJSON,
    ListWebhooks200ResponseDataInnerToJSONTyped,
} from './ListWebhooks200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListWebhooks200Response
 */
export interface ListWebhooks200Response {
    /**
     * 
     * @type {number}
     * @memberof ListWebhooks200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ListWebhooks200Response
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ListWebhooks200Response
     */
    total?: number;
    /**
     * 
     * @type {Array<ListWebhooks200ResponseDataInner>}
     * @memberof ListWebhooks200Response
     */
    data?: Array<ListWebhooks200ResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof ListWebhooks200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ListWebhooks200Response interface.
 */
export function instanceOfListWebhooks200Response(value: object): value is ListWebhooks200Response {
    return true;
}

export function ListWebhooks200ResponseFromJSON(json: any): ListWebhooks200Response {
    return ListWebhooks200ResponseFromJSONTyped(json, false);
}

export function ListWebhooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListWebhooks200ResponseDataInnerFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ListWebhooks200ResponseToJSON(json: any): ListWebhooks200Response {
    return ListWebhooks200ResponseToJSONTyped(json, false);
}

export function ListWebhooks200ResponseToJSONTyped(value?: ListWebhooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListWebhooks200ResponseDataInnerToJSON)),
        'request_id': value['requestId'],
    };
}

