/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project';

/**
 * 
 * @export
 * @interface ListProjects200Response
 */
export interface ListProjects200Response {
    /**
     * 
     * @type {Array<Project>}
     * @memberof ListProjects200Response
     */
    projects?: Array<Project>;
    /**
     * 
     * @type {string}
     * @memberof ListProjects200Response
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ListProjects200Response interface.
 */
export function instanceOfListProjects200Response(value: object): value is ListProjects200Response {
    return true;
}

export function ListProjects200ResponseFromJSON(json: any): ListProjects200Response {
    return ListProjects200ResponseFromJSONTyped(json, false);
}

export function ListProjects200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjects200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(ProjectFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ListProjects200ResponseToJSON(json: any): ListProjects200Response {
    return ListProjects200ResponseToJSONTyped(json, false);
}

export function ListProjects200ResponseToJSONTyped(value?: ListProjects200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(ProjectToJSON)),
        'request_id': value['requestId'],
    };
}

