/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The files and generation details once the report has completed; null before that
 * @export
 * @interface LlmsTxtTechnicalGeoReportResultData
 */
export interface LlmsTxtTechnicalGeoReportResultData {
    /**
     * Current llms.txt, manual edits included
     * @type {string}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    llmsTxtContent?: string;
    /**
     * Current llms-full.txt, manual edits included
     * @type {string}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    llmsFullTxtContent?: string | null;
    /**
     * When the files were last edited by hand in the app, the API or MCP; null while they are as generated
     * @type {Date}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    manuallyEditedAt?: Date | null;
    /**
     * Send it back as content_version when editing the files. It changes on every save
     * @type {string}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    contentVersion?: string;
    /**
     * The generated llms.txt, kept from the first manual edit; null while the files are as generated
     * @type {string}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    originalLlmsTxtContent?: string | null;
    /**
     * The generated llms-full.txt, kept from the first manual edit; null while the files are as generated
     * @type {string}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    originalLlmsFullTxtContent?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    crawlData?: object | null;
    /**
     * Generation details, including output_language_code, the language the files were written in
     * @type {object}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    metadata?: object | null;
    /**
     * 
     * @type {number}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    pagesCrawled?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    generationTimeMs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmsTxtTechnicalGeoReportResultData
     */
    openaiTokensUsed?: number | null;
}

/**
 * Check if a given object implements the LlmsTxtTechnicalGeoReportResultData interface.
 */
export function instanceOfLlmsTxtTechnicalGeoReportResultData(value: object): value is LlmsTxtTechnicalGeoReportResultData {
    return true;
}

export function LlmsTxtTechnicalGeoReportResultDataFromJSON(json: any): LlmsTxtTechnicalGeoReportResultData {
    return LlmsTxtTechnicalGeoReportResultDataFromJSONTyped(json, false);
}

export function LlmsTxtTechnicalGeoReportResultDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmsTxtTechnicalGeoReportResultData {
    if (json == null) {
        return json;
    }
    return {
        
        'llmsTxtContent': json['llms_txt_content'] == null ? undefined : json['llms_txt_content'],
        'llmsFullTxtContent': json['llms_full_txt_content'] === undefined ? undefined : json['llms_full_txt_content'] === null ? null : json['llms_full_txt_content'],
        'manuallyEditedAt': json['manually_edited_at'] === undefined ? undefined : json['manually_edited_at'] === null ? null : (new Date(json['manually_edited_at'])),
        'contentVersion': json['content_version'] == null ? undefined : json['content_version'],
        'originalLlmsTxtContent': json['original_llms_txt_content'] === undefined ? undefined : json['original_llms_txt_content'] === null ? null : json['original_llms_txt_content'],
        'originalLlmsFullTxtContent': json['original_llms_full_txt_content'] === undefined ? undefined : json['original_llms_full_txt_content'] === null ? null : json['original_llms_full_txt_content'],
        'crawlData': json['crawl_data'] === undefined ? undefined : json['crawl_data'] === null ? null : json['crawl_data'],
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
        'pagesCrawled': json['pages_crawled'] === undefined ? undefined : json['pages_crawled'] === null ? null : json['pages_crawled'],
        'generationTimeMs': json['generation_time_ms'] === undefined ? undefined : json['generation_time_ms'] === null ? null : json['generation_time_ms'],
        'openaiTokensUsed': json['openai_tokens_used'] === undefined ? undefined : json['openai_tokens_used'] === null ? null : json['openai_tokens_used'],
    };
}

export function LlmsTxtTechnicalGeoReportResultDataToJSON(json: any): LlmsTxtTechnicalGeoReportResultData {
    return LlmsTxtTechnicalGeoReportResultDataToJSONTyped(json, false);
}

export function LlmsTxtTechnicalGeoReportResultDataToJSONTyped(value?: LlmsTxtTechnicalGeoReportResultData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'llms_txt_content': value['llmsTxtContent'],
        'llms_full_txt_content': value['llmsFullTxtContent'],
        'manually_edited_at': value['manuallyEditedAt'] == null ? value['manuallyEditedAt'] : value['manuallyEditedAt'].toISOString(),
        'content_version': value['contentVersion'],
        'original_llms_txt_content': value['originalLlmsTxtContent'],
        'original_llms_full_txt_content': value['originalLlmsFullTxtContent'],
        'crawl_data': value['crawlData'],
        'metadata': value['metadata'],
        'pages_crawled': value['pagesCrawled'],
        'generation_time_ms': value['generationTimeMs'],
        'openai_tokens_used': value['openaiTokensUsed'],
    };
}

