/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalBusiness
 */
export interface LocalBusiness {
    /**
     * Stable grouping key: the lowercased name and address
     * @type {string}
     * @memberof LocalBusiness
     */
    businessKey?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    domain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    phone?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocalBusiness
     */
    avgRating?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LocalBusiness
     */
    reviews?: number | null;
    /**
     * Average rank of the business in the answer's list (1 = first)
     * @type {number}
     * @memberof LocalBusiness
     */
    avgPosition?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LocalBusiness
     */
    prompts?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalBusiness
     */
    appearances?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LocalBusiness
     */
    isClient?: boolean;
    /**
     * 
     * @type {number}
     * @memberof LocalBusiness
     */
    competitorId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LocalBusiness
     */
    competitorName?: string | null;
}

/**
 * Check if a given object implements the LocalBusiness interface.
 */
export function instanceOfLocalBusiness(value: object): value is LocalBusiness {
    return true;
}

export function LocalBusinessFromJSON(json: any): LocalBusiness {
    return LocalBusinessFromJSONTyped(json, false);
}

export function LocalBusinessFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalBusiness {
    if (json == null) {
        return json;
    }
    return {
        
        'businessKey': json['business_key'] == null ? undefined : json['business_key'],
        'title': json['title'] == null ? undefined : json['title'],
        'address': json['address'] === undefined ? undefined : json['address'] === null ? null : json['address'],
        'domain': json['domain'] === undefined ? undefined : json['domain'] === null ? null : json['domain'],
        'url': json['url'] === undefined ? undefined : json['url'] === null ? null : json['url'],
        'phone': json['phone'] === undefined ? undefined : json['phone'] === null ? null : json['phone'],
        'avgRating': json['avg_rating'] === undefined ? undefined : json['avg_rating'] === null ? null : json['avg_rating'],
        'reviews': json['reviews'] === undefined ? undefined : json['reviews'] === null ? null : json['reviews'],
        'avgPosition': json['avg_position'] === undefined ? undefined : json['avg_position'] === null ? null : json['avg_position'],
        'prompts': json['prompts'] == null ? undefined : json['prompts'],
        'appearances': json['appearances'] == null ? undefined : json['appearances'],
        'isClient': json['is_client'] == null ? undefined : json['is_client'],
        'competitorId': json['competitor_id'] === undefined ? undefined : json['competitor_id'] === null ? null : json['competitor_id'],
        'competitorName': json['competitor_name'] === undefined ? undefined : json['competitor_name'] === null ? null : json['competitor_name'],
    };
}

export function LocalBusinessToJSON(json: any): LocalBusiness {
    return LocalBusinessToJSONTyped(json, false);
}

export function LocalBusinessToJSONTyped(value?: LocalBusiness | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'business_key': value['businessKey'],
        'title': value['title'],
        'address': value['address'],
        'domain': value['domain'],
        'url': value['url'],
        'phone': value['phone'],
        'avg_rating': value['avgRating'],
        'reviews': value['reviews'],
        'avg_position': value['avgPosition'],
        'prompts': value['prompts'],
        'appearances': value['appearances'],
        'is_client': value['isClient'],
        'competitor_id': value['competitorId'],
        'competitor_name': value['competitorName'],
    };
}

