/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalesResponse
 */
export interface LocalesResponse {
    /**
     * 
     * @type {number}
     * @memberof LocalesResponse
     */
    projectId: number;
    /**
     * Country codes with data
     * @type {Array<string>}
     * @memberof LocalesResponse
     */
    countries: Array<string>;
    /**
     * Language codes with data
     * @type {Array<string>}
     * @memberof LocalesResponse
     */
    languages: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LocalesResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the LocalesResponse interface.
 */
export function instanceOfLocalesResponse(value: object): value is LocalesResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('countries' in value) || value['countries'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function LocalesResponseFromJSON(json: any): LocalesResponse {
    return LocalesResponseFromJSONTyped(json, false);
}

export function LocalesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'countries': json['countries'],
        'languages': json['languages'],
        'requestId': json['request_id'],
    };
}

export function LocalesResponseToJSON(json: any): LocalesResponse {
    return LocalesResponseToJSONTyped(json, false);
}

export function LocalesResponseToJSONTyped(value?: LocalesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'countries': value['countries'],
        'languages': value['languages'],
        'request_id': value['requestId'],
    };
}

