/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MentionRecord
 */
export interface MentionRecord {
    /**
     * 
     * @type {number}
     * @memberof MentionRecord
     */
    id: number;
    /**
     * The project's brand name (its name when no brand name is set)
     * @type {string}
     * @memberof MentionRecord
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MentionRecord
     */
    promptId: number;
    /**
     * 
     * @type {number}
     * @memberof MentionRecord
     */
    promptExecutionId: number;
    /**
     * 
     * @type {Date}
     * @memberof MentionRecord
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the MentionRecord interface.
 */
export function instanceOfMentionRecord(value: object): value is MentionRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('promptId' in (value as Record<string, any>)) && !('prompt_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['promptId'] === undefined && (value as Record<string, any>)['prompt_id'] === undefined)) return false;
    if ((!('promptExecutionId' in (value as Record<string, any>)) && !('prompt_execution_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['promptExecutionId'] === undefined && (value as Record<string, any>)['prompt_execution_id'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function MentionRecordFromJSON(json: any): MentionRecord {
    return MentionRecordFromJSONTyped(json, false);
}

export function MentionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'promptId': json['prompt_id'],
        'promptExecutionId': json['prompt_execution_id'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function MentionRecordToJSON(json: any): MentionRecord {
    return MentionRecordToJSONTyped(json, false);
}

export function MentionRecordToJSONTyped(value?: MentionRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'prompt_id': value['promptId'],
        'prompt_execution_id': value['promptExecutionId'],
        'created_at': value['createdAt'].toISOString(),
    };
}

