/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Envelope shared by the paginated listings; each listing adds its own data rows
 * @export
 * @interface PaginatedEnvelope
 */
export interface PaginatedEnvelope {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEnvelope
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedEnvelope
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedEnvelope
     */
    perPage: number;
    /**
     * Rows matching the filters across every page
     * @type {number}
     * @memberof PaginatedEnvelope
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the PaginatedEnvelope interface.
 */
export function instanceOfPaginatedEnvelope(value: object): value is PaginatedEnvelope {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if ((!('perPage' in (value as Record<string, any>)) && !('per_page' in (value as Record<string, any>))) || ((value as Record<string, any>)['perPage'] === undefined && (value as Record<string, any>)['per_page'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    return true;
}

export function PaginatedEnvelopeFromJSON(json: any): PaginatedEnvelope {
    return PaginatedEnvelopeFromJSONTyped(json, false);
}

export function PaginatedEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'page': json['page'],
        'perPage': json['per_page'],
        'total': json['total'],
        'requestId': json['request_id'],
    };
}

export function PaginatedEnvelopeToJSON(json: any): PaginatedEnvelope {
    return PaginatedEnvelopeToJSONTyped(json, false);
}

export function PaginatedEnvelopeToJSONTyped(value?: PaginatedEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'request_id': value['requestId'],
    };
}

