/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDetailsAllOfStatsPromptsByBrandKind } from './ProjectDetailsAllOfStatsPromptsByBrandKind';
import {
    ProjectDetailsAllOfStatsPromptsByBrandKindFromJSON,
    ProjectDetailsAllOfStatsPromptsByBrandKindFromJSONTyped,
    ProjectDetailsAllOfStatsPromptsByBrandKindToJSON,
    ProjectDetailsAllOfStatsPromptsByBrandKindToJSONTyped,
} from './ProjectDetailsAllOfStatsPromptsByBrandKind';

/**
 * 
 * @export
 * @interface ProjectDetailsAllOfStats
 */
export interface ProjectDetailsAllOfStats {
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsAllOfStats
     */
    promptsCount?: number;
    /**
     * 
     * @type {ProjectDetailsAllOfStatsPromptsByBrandKind}
     * @memberof ProjectDetailsAllOfStats
     */
    promptsByBrandKind?: ProjectDetailsAllOfStatsPromptsByBrandKind;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsAllOfStats
     */
    competitorsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsAllOfStats
     */
    collectionsCount?: number;
}

/**
 * Check if a given object implements the ProjectDetailsAllOfStats interface.
 */
export function instanceOfProjectDetailsAllOfStats(value: object): value is ProjectDetailsAllOfStats {
    return true;
}

export function ProjectDetailsAllOfStatsFromJSON(json: any): ProjectDetailsAllOfStats {
    return ProjectDetailsAllOfStatsFromJSONTyped(json, false);
}

export function ProjectDetailsAllOfStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailsAllOfStats {
    if (json == null) {
        return json;
    }
    return {
        
        'promptsCount': json['prompts_count'] == null ? undefined : json['prompts_count'],
        'promptsByBrandKind': json['prompts_by_brand_kind'] == null ? undefined : ProjectDetailsAllOfStatsPromptsByBrandKindFromJSON(json['prompts_by_brand_kind']),
        'competitorsCount': json['competitors_count'] == null ? undefined : json['competitors_count'],
        'collectionsCount': json['collections_count'] == null ? undefined : json['collections_count'],
    };
}

export function ProjectDetailsAllOfStatsToJSON(json: any): ProjectDetailsAllOfStats {
    return ProjectDetailsAllOfStatsToJSONTyped(json, false);
}

export function ProjectDetailsAllOfStatsToJSONTyped(value?: ProjectDetailsAllOfStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompts_count': value['promptsCount'],
        'prompts_by_brand_kind': ProjectDetailsAllOfStatsPromptsByBrandKindToJSON(value['promptsByBrandKind']),
        'competitors_count': value['competitorsCount'],
        'collections_count': value['collectionsCount'],
    };
}

