/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.50.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectCreateResponseSameDomainProjectsInner } from './ProjectCreateResponseSameDomainProjectsInner';
import {
    ProjectCreateResponseSameDomainProjectsInnerFromJSON,
    ProjectCreateResponseSameDomainProjectsInnerFromJSONTyped,
    ProjectCreateResponseSameDomainProjectsInnerToJSON,
    ProjectCreateResponseSameDomainProjectsInnerToJSONTyped,
} from './ProjectCreateResponseSameDomainProjectsInner';
import type { ProjectCreateResponseCollectionsInner } from './ProjectCreateResponseCollectionsInner';
import {
    ProjectCreateResponseCollectionsInnerFromJSON,
    ProjectCreateResponseCollectionsInnerFromJSONTyped,
    ProjectCreateResponseCollectionsInnerToJSON,
    ProjectCreateResponseCollectionsInnerToJSONTyped,
} from './ProjectCreateResponseCollectionsInner';
import type { ProjectCreateResponsePrompts } from './ProjectCreateResponsePrompts';
import {
    ProjectCreateResponsePromptsFromJSON,
    ProjectCreateResponsePromptsFromJSONTyped,
    ProjectCreateResponsePromptsToJSON,
    ProjectCreateResponsePromptsToJSONTyped,
} from './ProjectCreateResponsePrompts';
import type { ProjectCreateResponseLimits } from './ProjectCreateResponseLimits';
import {
    ProjectCreateResponseLimitsFromJSON,
    ProjectCreateResponseLimitsFromJSONTyped,
    ProjectCreateResponseLimitsToJSON,
    ProjectCreateResponseLimitsToJSONTyped,
} from './ProjectCreateResponseLimits';
import type { ProjectCreateResponseCompetitors } from './ProjectCreateResponseCompetitors';
import {
    ProjectCreateResponseCompetitorsFromJSON,
    ProjectCreateResponseCompetitorsFromJSONTyped,
    ProjectCreateResponseCompetitorsToJSON,
    ProjectCreateResponseCompetitorsToJSONTyped,
} from './ProjectCreateResponseCompetitors';
import type { ProjectCreateResponseEmailSubscription } from './ProjectCreateResponseEmailSubscription';
import {
    ProjectCreateResponseEmailSubscriptionFromJSON,
    ProjectCreateResponseEmailSubscriptionFromJSONTyped,
    ProjectCreateResponseEmailSubscriptionToJSON,
    ProjectCreateResponseEmailSubscriptionToJSONTyped,
} from './ProjectCreateResponseEmailSubscription';

/**
 * 
 * @export
 * @interface ProjectCreateResponse
 */
export interface ProjectCreateResponse {
    /**
     * Same shape as GET /dimensions/projects/{id}
     * @type {object}
     * @memberof ProjectCreateResponse
     */
    project?: object;
    /**
     * 
     * @type {ProjectCreateResponsePrompts}
     * @memberof ProjectCreateResponse
     */
    prompts?: ProjectCreateResponsePrompts;
    /**
     * 
     * @type {ProjectCreateResponseCompetitors}
     * @memberof ProjectCreateResponse
     */
    competitors?: ProjectCreateResponseCompetitors;
    /**
     * Collections created from the request's collections field (empty when none were sent; absent on an idempotent replay)
     * @type {Array<ProjectCreateResponseCollectionsInner>}
     * @memberof ProjectCreateResponse
     */
    collections?: Array<ProjectCreateResponseCollectionsInner>;
    /**
     * Projects the caller can already see on the same domain (absent on an idempotent replay). Informational only: the create is never blocked, since one domain tracked per market is a normal setup.
     * @type {Array<ProjectCreateResponseSameDomainProjectsInner>}
     * @memberof ProjectCreateResponse
     */
    sameDomainProjects?: Array<ProjectCreateResponseSameDomainProjectsInner>;
    /**
     * 
     * @type {ProjectCreateResponseEmailSubscription}
     * @memberof ProjectCreateResponse
     */
    emailSubscription?: ProjectCreateResponseEmailSubscription;
    /**
     * 
     * @type {ProjectCreateResponseLimits}
     * @memberof ProjectCreateResponse
     */
    limits?: ProjectCreateResponseLimits;
    /**
     * Present and true only on external_identifier replays
     * @type {boolean}
     * @memberof ProjectCreateResponse
     */
    idempotent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ProjectCreateResponse interface.
 */
export function instanceOfProjectCreateResponse(value: object): value is ProjectCreateResponse {
    return true;
}

export function ProjectCreateResponseFromJSON(json: any): ProjectCreateResponse {
    return ProjectCreateResponseFromJSONTyped(json, false);
}

export function ProjectCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : json['project'],
        'prompts': json['prompts'] == null ? undefined : ProjectCreateResponsePromptsFromJSON(json['prompts']),
        'competitors': json['competitors'] == null ? undefined : ProjectCreateResponseCompetitorsFromJSON(json['competitors']),
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(ProjectCreateResponseCollectionsInnerFromJSON)),
        'sameDomainProjects': json['same_domain_projects'] == null ? undefined : ((json['same_domain_projects'] as Array<any>).map(ProjectCreateResponseSameDomainProjectsInnerFromJSON)),
        'emailSubscription': json['email_subscription'] == null ? undefined : ProjectCreateResponseEmailSubscriptionFromJSON(json['email_subscription']),
        'limits': json['limits'] == null ? undefined : ProjectCreateResponseLimitsFromJSON(json['limits']),
        'idempotent': json['idempotent'] == null ? undefined : json['idempotent'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ProjectCreateResponseToJSON(json: any): ProjectCreateResponse {
    return ProjectCreateResponseToJSONTyped(json, false);
}

export function ProjectCreateResponseToJSONTyped(value?: ProjectCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'prompts': ProjectCreateResponsePromptsToJSON(value['prompts']),
        'competitors': ProjectCreateResponseCompetitorsToJSON(value['competitors']),
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(ProjectCreateResponseCollectionsInnerToJSON)),
        'same_domain_projects': value['sameDomainProjects'] == null ? undefined : ((value['sameDomainProjects'] as Array<any>).map(ProjectCreateResponseSameDomainProjectsInnerToJSON)),
        'email_subscription': ProjectCreateResponseEmailSubscriptionToJSON(value['emailSubscription']),
        'limits': ProjectCreateResponseLimitsToJSON(value['limits']),
        'idempotent': value['idempotent'],
        'request_id': value['requestId'],
    };
}

