/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AI models, countries and languages the project has data for
 * @export
 * @interface ProjectDetailsAllOfDataCoverage
 */
export interface ProjectDetailsAllOfDataCoverage {
    /**
     * 
     * @type {Array<ProjectDetailsAllOfDataCoverageModelsEnum>}
     * @memberof ProjectDetailsAllOfDataCoverage
     */
    models?: Array<ProjectDetailsAllOfDataCoverageModelsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectDetailsAllOfDataCoverage
     */
    countries?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectDetailsAllOfDataCoverage
     */
    languages?: Array<string>;
}


/**
 * @export
 */
export const ProjectDetailsAllOfDataCoverageModelsEnum = {
    Chatgpt: 'chatgpt',
    Perplexity: 'perplexity',
    AiMode: 'ai_mode',
    AiOverview: 'ai_overview',
    Gemini: 'gemini',
    Copilot: 'copilot',
    AmazonRufus: 'amazon_rufus',
    Claude: 'claude',
    Grok: 'grok',
    Deepseek: 'deepseek',
    NaverAi: 'naver_ai',
    BaiduAi: 'baidu_ai',
    MetaAi: 'meta_ai'
} as const;
export type ProjectDetailsAllOfDataCoverageModelsEnum = typeof ProjectDetailsAllOfDataCoverageModelsEnum[keyof typeof ProjectDetailsAllOfDataCoverageModelsEnum];


/**
 * Check if a given object implements the ProjectDetailsAllOfDataCoverage interface.
 */
export function instanceOfProjectDetailsAllOfDataCoverage(value: object): value is ProjectDetailsAllOfDataCoverage {
    return true;
}

export function ProjectDetailsAllOfDataCoverageFromJSON(json: any): ProjectDetailsAllOfDataCoverage {
    return ProjectDetailsAllOfDataCoverageFromJSONTyped(json, false);
}

export function ProjectDetailsAllOfDataCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailsAllOfDataCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'models': json['models'] == null ? undefined : json['models'],
        'countries': json['countries'] == null ? undefined : json['countries'],
        'languages': json['languages'] == null ? undefined : json['languages'],
    };
}

export function ProjectDetailsAllOfDataCoverageToJSON(json: any): ProjectDetailsAllOfDataCoverage {
    return ProjectDetailsAllOfDataCoverageToJSONTyped(json, false);
}

export function ProjectDetailsAllOfDataCoverageToJSONTyped(value?: ProjectDetailsAllOfDataCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': value['models'],
        'countries': value['countries'],
        'languages': value['languages'],
    };
}

