/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreateResponseEmailSubscription
 */
export interface ProjectCreateResponseEmailSubscription {
    /**
     * 
     * @type {boolean}
     * @memberof ProjectCreateResponseEmailSubscription
     */
    weeklyEmailSubscribed?: boolean;
}

/**
 * Check if a given object implements the ProjectCreateResponseEmailSubscription interface.
 */
export function instanceOfProjectCreateResponseEmailSubscription(value: object): value is ProjectCreateResponseEmailSubscription {
    return true;
}

export function ProjectCreateResponseEmailSubscriptionFromJSON(json: any): ProjectCreateResponseEmailSubscription {
    return ProjectCreateResponseEmailSubscriptionFromJSONTyped(json, false);
}

export function ProjectCreateResponseEmailSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponseEmailSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'weeklyEmailSubscribed': json['weekly_email_subscribed'] == null ? undefined : json['weekly_email_subscribed'],
    };
}

export function ProjectCreateResponseEmailSubscriptionToJSON(json: any): ProjectCreateResponseEmailSubscription {
    return ProjectCreateResponseEmailSubscriptionToJSONTyped(json, false);
}

export function ProjectCreateResponseEmailSubscriptionToJSONTyped(value?: ProjectCreateResponseEmailSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekly_email_subscribed': value['weeklyEmailSubscribed'],
    };
}

