/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectCreateRequestOwnedMedia } from './ProjectCreateRequestOwnedMedia';
import {
    ProjectCreateRequestOwnedMediaFromJSON,
    ProjectCreateRequestOwnedMediaFromJSONTyped,
    ProjectCreateRequestOwnedMediaToJSON,
    ProjectCreateRequestOwnedMediaToJSONTyped,
} from './ProjectCreateRequestOwnedMedia';
import type { ProjectCreateRequestCompetitorsInner } from './ProjectCreateRequestCompetitorsInner';
import {
    ProjectCreateRequestCompetitorsInnerFromJSON,
    ProjectCreateRequestCompetitorsInnerFromJSONTyped,
    ProjectCreateRequestCompetitorsInnerToJSON,
    ProjectCreateRequestCompetitorsInnerToJSONTyped,
} from './ProjectCreateRequestCompetitorsInner';

/**
 * 
 * @export
 * @interface ProjectCreateRequest
 */
export interface ProjectCreateRequest {
    /**
     * Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    websiteUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    mainCountry: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    mainLanguage: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    brandName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateRequest
     */
    industry?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateRequest
     */
    matchingNames?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateRequest
     */
    prompts?: Array<string>;
    /**
     * 
     * @type {Array<ProjectCreateRequestCompetitorsInner>}
     * @memberof ProjectCreateRequest
     */
    competitors?: Array<ProjectCreateRequestCompetitorsInner>;
    /**
     * 
     * @type {ProjectCreateRequestOwnedMedia}
     * @memberof ProjectCreateRequest
     */
    ownedMedia?: ProjectCreateRequestOwnedMedia;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectCreateRequest
     */
    useSubdomain?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectCreateRequest
     */
    weeklyEmailSubscribed?: boolean;
    /**
     * Embed-enabled (Enterprise) accounts only; other accounts receive ERR_PLAN_REQUIRED. Idempotency key and embed-session join key, unique per account
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    externalIdentifier?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectCreateRequest
     */
    executePromptsImmediately?: boolean;
}

/**
 * Check if a given object implements the ProjectCreateRequest interface.
 */
export function instanceOfProjectCreateRequest(value: object): value is ProjectCreateRequest {
    if ((!('websiteUrl' in (value as Record<string, any>)) && !('website_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['websiteUrl'] === undefined && (value as Record<string, any>)['website_url'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('mainCountry' in (value as Record<string, any>)) && !('main_country' in (value as Record<string, any>))) || ((value as Record<string, any>)['mainCountry'] === undefined && (value as Record<string, any>)['main_country'] === undefined)) return false;
    if ((!('mainLanguage' in (value as Record<string, any>)) && !('main_language' in (value as Record<string, any>))) || ((value as Record<string, any>)['mainLanguage'] === undefined && (value as Record<string, any>)['main_language'] === undefined)) return false;
    return true;
}

export function ProjectCreateRequestFromJSON(json: any): ProjectCreateRequest {
    return ProjectCreateRequestFromJSONTyped(json, false);
}

export function ProjectCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'websiteUrl': json['website_url'],
        'name': json['name'],
        'mainCountry': json['main_country'],
        'mainLanguage': json['main_language'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'matchingNames': json['matching_names'] == null ? undefined : json['matching_names'],
        'prompts': json['prompts'] == null ? undefined : json['prompts'],
        'competitors': json['competitors'] == null ? undefined : ((json['competitors'] as Array<any>).map(ProjectCreateRequestCompetitorsInnerFromJSON)),
        'ownedMedia': json['owned_media'] == null ? undefined : ProjectCreateRequestOwnedMediaFromJSON(json['owned_media']),
        'useSubdomain': json['use_subdomain'] == null ? undefined : json['use_subdomain'],
        'weeklyEmailSubscribed': json['weekly_email_subscribed'] == null ? undefined : json['weekly_email_subscribed'],
        'externalIdentifier': json['external_identifier'] == null ? undefined : json['external_identifier'],
        'executePromptsImmediately': json['execute_prompts_immediately'] == null ? undefined : json['execute_prompts_immediately'],
    };
}

export function ProjectCreateRequestToJSON(json: any): ProjectCreateRequest {
    return ProjectCreateRequestToJSONTyped(json, false);
}

export function ProjectCreateRequestToJSONTyped(value?: ProjectCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'website_url': value['websiteUrl'],
        'name': value['name'],
        'main_country': value['mainCountry'],
        'main_language': value['mainLanguage'],
        'brand_name': value['brandName'],
        'description': value['description'],
        'industry': value['industry'],
        'matching_names': value['matchingNames'],
        'prompts': value['prompts'],
        'competitors': value['competitors'] == null ? undefined : ((value['competitors'] as Array<any>).map(ProjectCreateRequestCompetitorsInnerToJSON)),
        'owned_media': ProjectCreateRequestOwnedMediaToJSON(value['ownedMedia']),
        'use_subdomain': value['useSubdomain'],
        'weekly_email_subscribed': value['weeklyEmailSubscribed'],
        'external_identifier': value['externalIdentifier'],
        'execute_prompts_immediately': value['executePromptsImmediately'],
    };
}

