/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.50.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreateResponseSameDomainProjectsInner
 */
export interface ProjectCreateResponseSameDomainProjectsInner {
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateResponseSameDomainProjectsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponseSameDomainProjectsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponseSameDomainProjectsInner
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponseSameDomainProjectsInner
     */
    languageCode?: string;
}

/**
 * Check if a given object implements the ProjectCreateResponseSameDomainProjectsInner interface.
 */
export function instanceOfProjectCreateResponseSameDomainProjectsInner(value: object): value is ProjectCreateResponseSameDomainProjectsInner {
    return true;
}

export function ProjectCreateResponseSameDomainProjectsInnerFromJSON(json: any): ProjectCreateResponseSameDomainProjectsInner {
    return ProjectCreateResponseSameDomainProjectsInnerFromJSONTyped(json, false);
}

export function ProjectCreateResponseSameDomainProjectsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponseSameDomainProjectsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'languageCode': json['language_code'] == null ? undefined : json['language_code'],
    };
}

export function ProjectCreateResponseSameDomainProjectsInnerToJSON(json: any): ProjectCreateResponseSameDomainProjectsInner {
    return ProjectCreateResponseSameDomainProjectsInnerToJSONTyped(json, false);
}

export function ProjectCreateResponseSameDomainProjectsInnerToJSONTyped(value?: ProjectCreateResponseSameDomainProjectsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country_code': value['countryCode'],
        'language_code': value['languageCode'],
    };
}

