/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.50.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreateResponseLimits
 */
export interface ProjectCreateResponseLimits {
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateResponseLimits
     */
    projectsRemaining?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateResponseLimits
     */
    promptsAvailable?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateResponseLimits
     */
    competitorsRemaining?: number | null;
}

/**
 * Check if a given object implements the ProjectCreateResponseLimits interface.
 */
export function instanceOfProjectCreateResponseLimits(value: object): value is ProjectCreateResponseLimits {
    return true;
}

export function ProjectCreateResponseLimitsFromJSON(json: any): ProjectCreateResponseLimits {
    return ProjectCreateResponseLimitsFromJSONTyped(json, false);
}

export function ProjectCreateResponseLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponseLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'projectsRemaining': json['projects_remaining'] === undefined ? undefined : json['projects_remaining'] === null ? null : json['projects_remaining'],
        'promptsAvailable': json['prompts_available'] === undefined ? undefined : json['prompts_available'] === null ? null : json['prompts_available'],
        'competitorsRemaining': json['competitors_remaining'] === undefined ? undefined : json['competitors_remaining'] === null ? null : json['competitors_remaining'],
    };
}

export function ProjectCreateResponseLimitsToJSON(json: any): ProjectCreateResponseLimits {
    return ProjectCreateResponseLimitsToJSONTyped(json, false);
}

export function ProjectCreateResponseLimitsToJSONTyped(value?: ProjectCreateResponseLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projects_remaining': value['projectsRemaining'],
        'prompts_available': value['promptsAvailable'],
        'competitors_remaining': value['competitorsRemaining'],
    };
}

