/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Requires Growth plan or above
 * @export
 * @interface ProjectCreateRequestOwnedMedia
 */
export interface ProjectCreateRequestOwnedMedia {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    youtubeChannelUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    instagramProfileUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    facebookPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    tiktokProfileUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    appStoreUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequestOwnedMedia
     */
    googlePlayUrl?: string;
}

/**
 * Check if a given object implements the ProjectCreateRequestOwnedMedia interface.
 */
export function instanceOfProjectCreateRequestOwnedMedia(value: object): value is ProjectCreateRequestOwnedMedia {
    return true;
}

export function ProjectCreateRequestOwnedMediaFromJSON(json: any): ProjectCreateRequestOwnedMedia {
    return ProjectCreateRequestOwnedMediaFromJSONTyped(json, false);
}

export function ProjectCreateRequestOwnedMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateRequestOwnedMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'youtubeChannelUrl': json['youtube_channel_url'] == null ? undefined : json['youtube_channel_url'],
        'instagramProfileUrl': json['instagram_profile_url'] == null ? undefined : json['instagram_profile_url'],
        'facebookPageUrl': json['facebook_page_url'] == null ? undefined : json['facebook_page_url'],
        'tiktokProfileUrl': json['tiktok_profile_url'] == null ? undefined : json['tiktok_profile_url'],
        'appStoreUrl': json['app_store_url'] == null ? undefined : json['app_store_url'],
        'googlePlayUrl': json['google_play_url'] == null ? undefined : json['google_play_url'],
    };
}

export function ProjectCreateRequestOwnedMediaToJSON(json: any): ProjectCreateRequestOwnedMedia {
    return ProjectCreateRequestOwnedMediaToJSONTyped(json, false);
}

export function ProjectCreateRequestOwnedMediaToJSONTyped(value?: ProjectCreateRequestOwnedMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'youtube_channel_url': value['youtubeChannelUrl'],
        'instagram_profile_url': value['instagramProfileUrl'],
        'facebook_page_url': value['facebookPageUrl'],
        'tiktok_profile_url': value['tiktokProfileUrl'],
        'app_store_url': value['appStoreUrl'],
        'google_play_url': value['googlePlayUrl'],
    };
}

