/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromptsCreateResponseDataInner } from './PromptsCreateResponseDataInner';
import {
    PromptsCreateResponseDataInnerFromJSON,
    PromptsCreateResponseDataInnerFromJSONTyped,
    PromptsCreateResponseDataInnerToJSON,
    PromptsCreateResponseDataInnerToJSONTyped,
} from './PromptsCreateResponseDataInner';

/**
 * 
 * @export
 * @interface PromptsCreateResponse
 */
export interface PromptsCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof PromptsCreateResponse
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof PromptsCreateResponse
     */
    created?: number;
    /**
     * 
     * @type {number}
     * @memberof PromptsCreateResponse
     */
    skipped?: number;
    /**
     * 
     * @type {number}
     * @memberof PromptsCreateResponse
     */
    totalAfter?: number;
    /**
     * 
     * @type {number}
     * @memberof PromptsCreateResponse
     */
    promptsAvailable?: number;
    /**
     * 
     * @type {Array<PromptsCreateResponseDataInner>}
     * @memberof PromptsCreateResponse
     */
    data?: Array<PromptsCreateResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof PromptsCreateResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the PromptsCreateResponse interface.
 */
export function instanceOfPromptsCreateResponse(value: object): value is PromptsCreateResponse {
    return true;
}

export function PromptsCreateResponseFromJSON(json: any): PromptsCreateResponse {
    return PromptsCreateResponseFromJSONTyped(json, false);
}

export function PromptsCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptsCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'created': json['created'] == null ? undefined : json['created'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'totalAfter': json['total_after'] == null ? undefined : json['total_after'],
        'promptsAvailable': json['prompts_available'] == null ? undefined : json['prompts_available'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PromptsCreateResponseDataInnerFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function PromptsCreateResponseToJSON(json: any): PromptsCreateResponse {
    return PromptsCreateResponseToJSONTyped(json, false);
}

export function PromptsCreateResponseToJSONTyped(value?: PromptsCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'created': value['created'],
        'skipped': value['skipped'],
        'total_after': value['totalAfter'],
        'prompts_available': value['promptsAvailable'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PromptsCreateResponseDataInnerToJSON)),
        'request_id': value['requestId'],
    };
}

