/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromptExecutionRecord } from './PromptExecutionRecord';
import {
    PromptExecutionRecordFromJSON,
    PromptExecutionRecordFromJSONTyped,
    PromptExecutionRecordToJSON,
    PromptExecutionRecordToJSONTyped,
} from './PromptExecutionRecord';

/**
 * 
 * @export
 * @interface PromptExecutionsResponse
 */
export interface PromptExecutionsResponse {
    /**
     * 
     * @type {number}
     * @memberof PromptExecutionsResponse
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof PromptExecutionsResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PromptExecutionsResponse
     */
    perPage: number;
    /**
     * Rows matching the filters across every page
     * @type {number}
     * @memberof PromptExecutionsResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof PromptExecutionsResponse
     */
    requestId: string;
    /**
     * 
     * @type {Array<PromptExecutionRecord>}
     * @memberof PromptExecutionsResponse
     */
    data: Array<PromptExecutionRecord>;
}

/**
 * Check if a given object implements the PromptExecutionsResponse interface.
 */
export function instanceOfPromptExecutionsResponse(value: object): value is PromptExecutionsResponse {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if ((!('perPage' in (value as Record<string, any>)) && !('per_page' in (value as Record<string, any>))) || ((value as Record<string, any>)['perPage'] === undefined && (value as Record<string, any>)['per_page'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PromptExecutionsResponseFromJSON(json: any): PromptExecutionsResponse {
    return PromptExecutionsResponseFromJSONTyped(json, false);
}

export function PromptExecutionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptExecutionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'page': json['page'],
        'perPage': json['per_page'],
        'total': json['total'],
        'requestId': json['request_id'],
        'data': ((json['data'] as Array<any>).map(PromptExecutionRecordFromJSON)),
    };
}

export function PromptExecutionsResponseToJSON(json: any): PromptExecutionsResponse {
    return PromptExecutionsResponseToJSONTyped(json, false);
}

export function PromptExecutionsResponseToJSONTyped(value?: PromptExecutionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'request_id': value['requestId'],
        'data': ((value['data'] as Array<any>).map(PromptExecutionRecordToJSON)),
    };
}

