/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryWebAnalyticsRequest
 */
export interface QueryWebAnalyticsRequest {
    /**
     * 
     * @type {number}
     * @memberof QueryWebAnalyticsRequest
     */
    projectId: number;
    /**
     * The query in the provider's native format (see GET /web_analytics/schema): a JSON object for GA4, Adobe, Matomo, Plausible and Piano; for PostHog, {"query": "<HogQL>"} or the HogQL string. Deliberately untyped so generated clients accept either shape.
     * @type {any}
     * @memberof QueryWebAnalyticsRequest
     */
    query: any | null;
}

/**
 * Check if a given object implements the QueryWebAnalyticsRequest interface.
 */
export function instanceOfQueryWebAnalyticsRequest(value: object): value is QueryWebAnalyticsRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function QueryWebAnalyticsRequestFromJSON(json: any): QueryWebAnalyticsRequest {
    return QueryWebAnalyticsRequestFromJSONTyped(json, false);
}

export function QueryWebAnalyticsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryWebAnalyticsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'query': json['query'],
    };
}

export function QueryWebAnalyticsRequestToJSON(json: any): QueryWebAnalyticsRequest {
    return QueryWebAnalyticsRequestToJSONTyped(json, false);
}

export function QueryWebAnalyticsRequestToJSONTyped(value?: QueryWebAnalyticsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'query': value['query'],
    };
}

