/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendationSummarySummary } from './RecommendationSummarySummary';
import {
    RecommendationSummarySummaryFromJSON,
    RecommendationSummarySummaryFromJSONTyped,
    RecommendationSummarySummaryToJSON,
    RecommendationSummarySummaryToJSONTyped,
} from './RecommendationSummarySummary';

/**
 * 
 * @export
 * @interface RecommendationSummary
 */
export interface RecommendationSummary {
    /**
     * 
     * @type {number}
     * @memberof RecommendationSummary
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof RecommendationSummary
     */
    projectId: number;
    /**
     * 
     * @type {RecommendationSummaryRecommendationTypeEnum}
     * @memberof RecommendationSummary
     */
    recommendationType: RecommendationSummaryRecommendationTypeEnum;
    /**
     * 
     * @type {RecommendationSummaryStatusEnum}
     * @memberof RecommendationSummary
     */
    status: RecommendationSummaryStatusEnum;
    /**
     * Set only when status is failed
     * @type {string}
     * @memberof RecommendationSummary
     */
    errorMessage: string | null;
    /**
     * Null until the generation completes
     * @type {Date}
     * @memberof RecommendationSummary
     */
    generatedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RecommendationSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecommendationSummary
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof RecommendationSummary
     */
    totalRecommendations: number;
    /**
     * 
     * @type {number}
     * @memberof RecommendationSummary
     */
    highPriorityCount: number;
    /**
     * 
     * @type {RecommendationSummarySummary}
     * @memberof RecommendationSummary
     */
    summary: RecommendationSummarySummary;
    /**
     * Generation context and run diagnostics as stored; empty until the generation completes. Its keys are not a stable contract
     * @type {object}
     * @memberof RecommendationSummary
     */
    context: object;
}


/**
 * @export
 */
export const RecommendationSummaryRecommendationTypeEnum = {
    AiVisibility: 'ai_visibility',
    SocialCommunity: 'social_community',
    BrandBuilding: 'brand_building',
    SentimentReputation: 'sentiment_reputation'
} as const;
export type RecommendationSummaryRecommendationTypeEnum = typeof RecommendationSummaryRecommendationTypeEnum[keyof typeof RecommendationSummaryRecommendationTypeEnum];

/**
 * @export
 */
export const RecommendationSummaryStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type RecommendationSummaryStatusEnum = typeof RecommendationSummaryStatusEnum[keyof typeof RecommendationSummaryStatusEnum];


/**
 * Check if a given object implements the RecommendationSummary interface.
 */
export function instanceOfRecommendationSummary(value: object): value is RecommendationSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('recommendationType' in (value as Record<string, any>)) && !('recommendation_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['recommendationType'] === undefined && (value as Record<string, any>)['recommendation_type'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('errorMessage' in (value as Record<string, any>)) && !('error_message' in (value as Record<string, any>))) || ((value as Record<string, any>)['errorMessage'] === undefined && (value as Record<string, any>)['error_message'] === undefined)) return false;
    if ((!('generatedAt' in (value as Record<string, any>)) && !('generated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['generatedAt'] === undefined && (value as Record<string, any>)['generated_at'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if ((!('totalRecommendations' in (value as Record<string, any>)) && !('total_recommendations' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalRecommendations'] === undefined && (value as Record<string, any>)['total_recommendations'] === undefined)) return false;
    if ((!('highPriorityCount' in (value as Record<string, any>)) && !('high_priority_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['highPriorityCount'] === undefined && (value as Record<string, any>)['high_priority_count'] === undefined)) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    return true;
}

export function RecommendationSummaryFromJSON(json: any): RecommendationSummary {
    return RecommendationSummaryFromJSONTyped(json, false);
}

export function RecommendationSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'recommendationType': json['recommendation_type'],
        'status': json['status'],
        'errorMessage': json['error_message'],
        'generatedAt': (json['generated_at'] == null ? null : new Date(json['generated_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'totalRecommendations': json['total_recommendations'],
        'highPriorityCount': json['high_priority_count'],
        'summary': RecommendationSummarySummaryFromJSON(json['summary']),
        'context': json['context'],
    };
}

export function RecommendationSummaryToJSON(json: any): RecommendationSummary {
    return RecommendationSummaryToJSONTyped(json, false);
}

export function RecommendationSummaryToJSONTyped(value?: RecommendationSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'recommendation_type': value['recommendationType'],
        'status': value['status'],
        'error_message': value['errorMessage'],
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : value['generatedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'total_recommendations': value['totalRecommendations'],
        'high_priority_count': value['highPriorityCount'],
        'summary': RecommendationSummarySummaryToJSON(value['summary']),
        'context': value['context'],
    };
}

