/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.49.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SovResponsePeriodsInner
 */
export interface SovResponsePeriodsInner {
    /**
     * 
     * @type {Date}
     * @memberof SovResponsePeriodsInner
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof SovResponsePeriodsInner
     */
    mentions?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SovResponsePeriodsInner
     */
    partial?: boolean;
}

/**
 * Check if a given object implements the SovResponsePeriodsInner interface.
 */
export function instanceOfSovResponsePeriodsInner(value: object): value is SovResponsePeriodsInner {
    return true;
}

export function SovResponsePeriodsInnerFromJSON(json: any): SovResponsePeriodsInner {
    return SovResponsePeriodsInnerFromJSONTyped(json, false);
}

export function SovResponsePeriodsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SovResponsePeriodsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'mentions': json['mentions'] == null ? undefined : json['mentions'],
        'partial': json['partial'] == null ? undefined : json['partial'],
    };
}

export function SovResponsePeriodsInnerToJSON(json: any): SovResponsePeriodsInner {
    return SovResponsePeriodsInnerToJSONTyped(json, false);
}

export function SovResponsePeriodsInnerToJSONTyped(value?: SovResponsePeriodsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'mentions': value['mentions'],
        'partial': value['partial'],
    };
}

