/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Actor } from './Actor';
import {
    ActorFromJSON,
    ActorFromJSONTyped,
    ActorToJSON,
    ActorToJSONTyped,
} from './Actor';

/**
 * 
 * @export
 * @interface SovResponseCurrentInner
 */
export interface SovResponseCurrentInner {
    /**
     * 
     * @type {Actor}
     * @memberof SovResponseCurrentInner
     */
    actor?: Actor;
    /**
     * 
     * @type {number}
     * @memberof SovResponseCurrentInner
     */
    share?: number;
    /**
     * The actor's share in the last complete bucket before the current one; null without complete history.
     * @type {number}
     * @memberof SovResponseCurrentInner
     */
    previousShare?: number | null;
    /**
     * Mean share across complete buckets with data (partial buckets excluded); null without complete history.
     * @type {number}
     * @memberof SovResponseCurrentInner
     */
    avgShare?: number | null;
}

/**
 * Check if a given object implements the SovResponseCurrentInner interface.
 */
export function instanceOfSovResponseCurrentInner(value: object): value is SovResponseCurrentInner {
    return true;
}

export function SovResponseCurrentInnerFromJSON(json: any): SovResponseCurrentInner {
    return SovResponseCurrentInnerFromJSONTyped(json, false);
}

export function SovResponseCurrentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SovResponseCurrentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': json['actor'] == null ? undefined : ActorFromJSON(json['actor']),
        'share': json['share'] == null ? undefined : json['share'],
        'previousShare': json['previous_share'] === undefined ? undefined : json['previous_share'] === null ? null : json['previous_share'],
        'avgShare': json['avg_share'] === undefined ? undefined : json['avg_share'] === null ? null : json['avg_share'],
    };
}

export function SovResponseCurrentInnerToJSON(json: any): SovResponseCurrentInner {
    return SovResponseCurrentInnerToJSONTyped(json, false);
}

export function SovResponseCurrentInnerToJSONTyped(value?: SovResponseCurrentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': ActorToJSON(value['actor']),
        'share': value['share'],
        'previous_share': value['previousShare'],
        'avg_share': value['avgShare'],
    };
}

