/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The period the current shares were computed on (the last one with mentions), same shape as a periods item; null when the window has no mentions.
 * @export
 * @interface SovResponseSample
 */
export interface SovResponseSample {
    /**
     * 
     * @type {Date}
     * @memberof SovResponseSample
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof SovResponseSample
     */
    mentions?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SovResponseSample
     */
    partial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SovResponseSample
     */
    confidence?: string;
    /**
     * 
     * @type {number}
     * @memberof SovResponseSample
     */
    marginOfError?: number | null;
}

/**
 * Check if a given object implements the SovResponseSample interface.
 */
export function instanceOfSovResponseSample(value: object): value is SovResponseSample {
    return true;
}

export function SovResponseSampleFromJSON(json: any): SovResponseSample {
    return SovResponseSampleFromJSONTyped(json, false);
}

export function SovResponseSampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SovResponseSample {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'mentions': json['mentions'] == null ? undefined : json['mentions'],
        'partial': json['partial'] == null ? undefined : json['partial'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'marginOfError': json['margin_of_error'] === undefined ? undefined : json['margin_of_error'] === null ? null : json['margin_of_error'],
    };
}

export function SovResponseSampleToJSON(json: any): SovResponseSample {
    return SovResponseSampleToJSONTyped(json, false);
}

export function SovResponseSampleToJSONTyped(value?: SovResponseSample | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'mentions': value['mentions'],
        'partial': value['partial'],
        'confidence': value['confidence'],
        'margin_of_error': value['marginOfError'],
    };
}

