/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreConnectionResponseAccount
 */
export interface StoreConnectionResponseAccount {
    /**
     * Internal plan key of the account, e.g. scale or scaleplus; null for a key limited to some projects
     * @type {string}
     * @memberof StoreConnectionResponseAccount
     */
    plan?: string | null;
}

/**
 * Check if a given object implements the StoreConnectionResponseAccount interface.
 */
export function instanceOfStoreConnectionResponseAccount(value: object): value is StoreConnectionResponseAccount {
    return true;
}

export function StoreConnectionResponseAccountFromJSON(json: any): StoreConnectionResponseAccount {
    return StoreConnectionResponseAccountFromJSONTyped(json, false);
}

export function StoreConnectionResponseAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreConnectionResponseAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'plan': json['plan'] === undefined ? undefined : json['plan'] === null ? null : json['plan'],
    };
}

export function StoreConnectionResponseAccountToJSON(json: any): StoreConnectionResponseAccount {
    return StoreConnectionResponseAccountToJSONTyped(json, false);
}

export function StoreConnectionResponseAccountToJSONTyped(value?: StoreConnectionResponseAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan': value['plan'],
    };
}

