/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LlmsTxtTechnicalGeoReportResultData } from './LlmsTxtTechnicalGeoReportResultData';
import {
    LlmsTxtTechnicalGeoReportResultDataFromJSON,
    LlmsTxtTechnicalGeoReportResultDataFromJSONTyped,
    LlmsTxtTechnicalGeoReportResultDataToJSON,
    LlmsTxtTechnicalGeoReportResultDataToJSONTyped,
} from './LlmsTxtTechnicalGeoReportResultData';

/**
 * 
 * @export
 * @interface TechnicalGeoReportContentUpdateResponse
 */
export interface TechnicalGeoReportContentUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    id?: number;
    /**
     * Always llms_txt
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    reportType?: string;
    /**
     * 
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    projectId?: number;
    /**
     * Bundle the report was created in; null for a report created on its own
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    batchId?: number | null;
    /**
     * Always null for llms_txt reports; domain names the website
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    countryCode?: string | null;
    /**
     * ISO 639-1 code the files were requested in; null when they are written in the website's own language
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    outputLanguageCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    resultAvailable?: boolean;
    /**
     * Always null for llms_txt reports
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    overallScore?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {LlmsTxtTechnicalGeoReportResultData}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    resultData?: LlmsTxtTechnicalGeoReportResultData | null;
    /**
     * 
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    errorMessage?: string | null;
    /**
     * Seconds to wait before polling again while the report runs; null once it has finished
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    pollAfterSeconds?: number | null;
    /**
     * Opens this report in the app
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    appUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    requestId?: string;
    /**
     * Files whose text actually changed; empty when every file matched the stored text
     * @type {Array<TechnicalGeoReportContentUpdateResponseChangedFilesEnum>}
     * @memberof TechnicalGeoReportContentUpdateResponse
     */
    changedFiles?: Array<TechnicalGeoReportContentUpdateResponseChangedFilesEnum>;
}


/**
 * @export
 */
export const TechnicalGeoReportContentUpdateResponseChangedFilesEnum = {
    LlmsTxt: 'llms_txt',
    LlmsFullTxt: 'llms_full_txt'
} as const;
export type TechnicalGeoReportContentUpdateResponseChangedFilesEnum = typeof TechnicalGeoReportContentUpdateResponseChangedFilesEnum[keyof typeof TechnicalGeoReportContentUpdateResponseChangedFilesEnum];


/**
 * Check if a given object implements the TechnicalGeoReportContentUpdateResponse interface.
 */
export function instanceOfTechnicalGeoReportContentUpdateResponse(value: object): value is TechnicalGeoReportContentUpdateResponse {
    return true;
}

export function TechnicalGeoReportContentUpdateResponseFromJSON(json: any): TechnicalGeoReportContentUpdateResponse {
    return TechnicalGeoReportContentUpdateResponseFromJSONTyped(json, false);
}

export function TechnicalGeoReportContentUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnicalGeoReportContentUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reportType': json['report_type'] == null ? undefined : json['report_type'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'batchId': json['batch_id'] === undefined ? undefined : json['batch_id'] === null ? null : json['batch_id'],
        'url': json['url'] === undefined ? undefined : json['url'] === null ? null : json['url'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'countryCode': json['country_code'] === undefined ? undefined : json['country_code'] === null ? null : json['country_code'],
        'outputLanguageCode': json['output_language_code'] === undefined ? undefined : json['output_language_code'] === null ? null : json['output_language_code'],
        'status': json['status'] == null ? undefined : json['status'],
        'resultAvailable': json['result_available'] == null ? undefined : json['result_available'],
        'overallScore': json['overall_score'] === undefined ? undefined : json['overall_score'] === null ? null : json['overall_score'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'resultData': json['result_data'] === undefined ? undefined : json['result_data'] === null ? null : LlmsTxtTechnicalGeoReportResultDataFromJSON(json['result_data']),
        'errorMessage': json['error_message'] === undefined ? undefined : json['error_message'] === null ? null : json['error_message'],
        'pollAfterSeconds': json['poll_after_seconds'] === undefined ? undefined : json['poll_after_seconds'] === null ? null : json['poll_after_seconds'],
        'appUrl': json['app_url'] == null ? undefined : json['app_url'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'changedFiles': json['changed_files'] == null ? undefined : json['changed_files'],
    };
}

export function TechnicalGeoReportContentUpdateResponseToJSON(json: any): TechnicalGeoReportContentUpdateResponse {
    return TechnicalGeoReportContentUpdateResponseToJSONTyped(json, false);
}

export function TechnicalGeoReportContentUpdateResponseToJSONTyped(value?: TechnicalGeoReportContentUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'report_type': value['reportType'],
        'project_id': value['projectId'],
        'batch_id': value['batchId'],
        'url': value['url'],
        'domain': value['domain'],
        'country_code': value['countryCode'],
        'output_language_code': value['outputLanguageCode'],
        'status': value['status'],
        'result_available': value['resultAvailable'],
        'overall_score': value['overallScore'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'result_data': LlmsTxtTechnicalGeoReportResultDataToJSON(value['resultData']),
        'error_message': value['errorMessage'],
        'poll_after_seconds': value['pollAfterSeconds'],
        'app_url': value['appUrl'],
        'request_id': value['requestId'],
        'changed_files': value['changedFiles'],
    };
}

