/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TechnicalGeoReportContentUpdateRequestEdits } from './TechnicalGeoReportContentUpdateRequestEdits';
import {
    TechnicalGeoReportContentUpdateRequestEditsFromJSON,
    TechnicalGeoReportContentUpdateRequestEditsFromJSONTyped,
    TechnicalGeoReportContentUpdateRequestEditsToJSON,
    TechnicalGeoReportContentUpdateRequestEditsToJSONTyped,
} from './TechnicalGeoReportContentUpdateRequestEdits';

/**
 * 
 * @export
 * @interface TechnicalGeoReportContentUpdateRequest
 */
export interface TechnicalGeoReportContentUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof TechnicalGeoReportContentUpdateRequest
     */
    projectId: number;
    /**
     * Only llms_txt reports have editable content
     * @type {TechnicalGeoReportContentUpdateRequestReportTypeEnum}
     * @memberof TechnicalGeoReportContentUpdateRequest
     */
    reportType: TechnicalGeoReportContentUpdateRequestReportTypeEnum;
    /**
     * result_data.content_version of the report as last read. It changes on every save; a value that no longer matches is refused as stale
     * @type {string}
     * @memberof TechnicalGeoReportContentUpdateRequest
     */
    contentVersion: string;
    /**
     * 
     * @type {TechnicalGeoReportContentUpdateRequestEdits}
     * @memberof TechnicalGeoReportContentUpdateRequest
     */
    edits: TechnicalGeoReportContentUpdateRequestEdits;
}


/**
 * @export
 */
export const TechnicalGeoReportContentUpdateRequestReportTypeEnum = {
    LlmsTxt: 'llms_txt'
} as const;
export type TechnicalGeoReportContentUpdateRequestReportTypeEnum = typeof TechnicalGeoReportContentUpdateRequestReportTypeEnum[keyof typeof TechnicalGeoReportContentUpdateRequestReportTypeEnum];


/**
 * Check if a given object implements the TechnicalGeoReportContentUpdateRequest interface.
 */
export function instanceOfTechnicalGeoReportContentUpdateRequest(value: object): value is TechnicalGeoReportContentUpdateRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('reportType' in (value as Record<string, any>)) && !('report_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['reportType'] === undefined && (value as Record<string, any>)['report_type'] === undefined)) return false;
    if ((value as Record<string, any>)['reportType'] !== 'llms_txt' && (value as Record<string, any>)['report_type'] !== 'llms_txt') return false;
    
    if ((!('contentVersion' in (value as Record<string, any>)) && !('content_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentVersion'] === undefined && (value as Record<string, any>)['content_version'] === undefined)) return false;
    if (!('edits' in value) || value['edits'] === undefined) return false;
    return true;
}

export function TechnicalGeoReportContentUpdateRequestFromJSON(json: any): TechnicalGeoReportContentUpdateRequest {
    return TechnicalGeoReportContentUpdateRequestFromJSONTyped(json, false);
}

export function TechnicalGeoReportContentUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnicalGeoReportContentUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'reportType': json['report_type'],
        'contentVersion': json['content_version'],
        'edits': TechnicalGeoReportContentUpdateRequestEditsFromJSON(json['edits']),
    };
}

export function TechnicalGeoReportContentUpdateRequestToJSON(json: any): TechnicalGeoReportContentUpdateRequest {
    return TechnicalGeoReportContentUpdateRequestToJSONTyped(json, false);
}

export function TechnicalGeoReportContentUpdateRequestToJSONTyped(value?: TechnicalGeoReportContentUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'report_type': value['reportType'],
        'content_version': value['contentVersion'],
        'edits': TechnicalGeoReportContentUpdateRequestEditsToJSON(value['edits']),
    };
}

