/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeseriesPoint } from './TimeseriesPoint';
import {
    TimeseriesPointFromJSON,
    TimeseriesPointFromJSONTyped,
    TimeseriesPointToJSON,
    TimeseriesPointToJSONTyped,
} from './TimeseriesPoint';
import type { Actor } from './Actor';
import {
    ActorFromJSON,
    ActorFromJSONTyped,
    ActorToJSON,
    ActorToJSONTyped,
} from './Actor';

/**
 * 
 * @export
 * @interface TimeseriesSeries
 */
export interface TimeseriesSeries {
    /**
     * 
     * @type {Actor}
     * @memberof TimeseriesSeries
     */
    actor?: Actor;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesSeries
     */
    metric?: string;
    /**
     * 
     * @type {Array<TimeseriesPoint>}
     * @memberof TimeseriesSeries
     */
    data?: Array<TimeseriesPoint>;
}

/**
 * Check if a given object implements the TimeseriesSeries interface.
 */
export function instanceOfTimeseriesSeries(value: object): value is TimeseriesSeries {
    return true;
}

export function TimeseriesSeriesFromJSON(json: any): TimeseriesSeries {
    return TimeseriesSeriesFromJSONTyped(json, false);
}

export function TimeseriesSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': json['actor'] == null ? undefined : ActorFromJSON(json['actor']),
        'metric': json['metric'] == null ? undefined : json['metric'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TimeseriesPointFromJSON)),
    };
}

export function TimeseriesSeriesToJSON(json: any): TimeseriesSeries {
    return TimeseriesSeriesToJSONTyped(json, false);
}

export function TimeseriesSeriesToJSONTyped(value?: TimeseriesSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': ActorToJSON(value['actor']),
        'metric': value['metric'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TimeseriesPointToJSON)),
    };
}

