/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricsFiltersEcho } from './MetricsFiltersEcho';
import {
    MetricsFiltersEchoFromJSON,
    MetricsFiltersEchoFromJSONTyped,
    MetricsFiltersEchoToJSON,
    MetricsFiltersEchoToJSONTyped,
} from './MetricsFiltersEcho';
import type { TopSourcesResponseDataInner } from './TopSourcesResponseDataInner';
import {
    TopSourcesResponseDataInnerFromJSON,
    TopSourcesResponseDataInnerFromJSONTyped,
    TopSourcesResponseDataInnerToJSON,
    TopSourcesResponseDataInnerToJSONTyped,
} from './TopSourcesResponseDataInner';

/**
 * 
 * @export
 * @interface TopSourcesResponse
 */
export interface TopSourcesResponse {
    /**
     * 
     * @type {number}
     * @memberof TopSourcesResponse
     */
    projectId?: number;
    /**
     * 
     * @type {Date}
     * @memberof TopSourcesResponse
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TopSourcesResponse
     */
    to?: Date;
    /**
     * 
     * @type {MetricsFiltersEcho}
     * @memberof TopSourcesResponse
     */
    filters?: MetricsFiltersEcho;
    /**
     * 
     * @type {string}
     * @memberof TopSourcesResponse
     */
    sort?: string;
    /**
     * 
     * @type {number}
     * @memberof TopSourcesResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TopSourcesResponse
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof TopSourcesResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<TopSourcesResponseDataInner>}
     * @memberof TopSourcesResponse
     */
    data?: Array<TopSourcesResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof TopSourcesResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the TopSourcesResponse interface.
 */
export function instanceOfTopSourcesResponse(value: object): value is TopSourcesResponse {
    return true;
}

export function TopSourcesResponseFromJSON(json: any): TopSourcesResponse {
    return TopSourcesResponseFromJSONTyped(json, false);
}

export function TopSourcesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopSourcesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'filters': json['filters'] == null ? undefined : MetricsFiltersEchoFromJSON(json['filters']),
        'sort': json['sort'] == null ? undefined : json['sort'],
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TopSourcesResponseDataInnerFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function TopSourcesResponseToJSON(json: any): TopSourcesResponse {
    return TopSourcesResponseToJSONTyped(json, false);
}

export function TopSourcesResponseToJSONTyped(value?: TopSourcesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'from': value['from'] == null ? value['from'] : value['from'].toISOString(),
        'to': value['to'] == null ? value['to'] : value['to'].toISOString(),
        'filters': MetricsFiltersEchoToJSON(value['filters']),
        'sort': value['sort'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TopSourcesResponseDataInnerToJSON)),
        'request_id': value['requestId'],
    };
}

