/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectDraftRequest
 */
export interface UpdateProjectDraftRequest {
    /**
     * 
     * @type {UpdateProjectDraftRequestStepEnum}
     * @memberof UpdateProjectDraftRequest
     */
    step: UpdateProjectDraftRequestStepEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    brandName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProjectDraftRequest
     */
    industry?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProjectDraftRequest
     */
    matchingNames?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    externalIdentifier?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProjectDraftRequest
     */
    prompts?: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof UpdateProjectDraftRequest
     */
    competitors?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    youtubeChannelUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    instagramProfileUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    facebookPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    tiktokProfileUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    appStoreUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDraftRequest
     */
    googlePlayUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProjectDraftRequest
     */
    suggest?: boolean;
}


/**
 * @export
 */
export const UpdateProjectDraftRequestStepEnum = {
    Details: 'details',
    Prompts: 'prompts',
    Competitors: 'competitors',
    OwnedMedia: 'owned_media'
} as const;
export type UpdateProjectDraftRequestStepEnum = typeof UpdateProjectDraftRequestStepEnum[keyof typeof UpdateProjectDraftRequestStepEnum];


/**
 * Check if a given object implements the UpdateProjectDraftRequest interface.
 */
export function instanceOfUpdateProjectDraftRequest(value: object): value is UpdateProjectDraftRequest {
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function UpdateProjectDraftRequestFromJSON(json: any): UpdateProjectDraftRequest {
    return UpdateProjectDraftRequestFromJSONTyped(json, false);
}

export function UpdateProjectDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'],
        'name': json['name'] == null ? undefined : json['name'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'matchingNames': json['matching_names'] == null ? undefined : json['matching_names'],
        'externalIdentifier': json['external_identifier'] == null ? undefined : json['external_identifier'],
        'prompts': json['prompts'] == null ? undefined : json['prompts'],
        'competitors': json['competitors'] == null ? undefined : json['competitors'],
        'youtubeChannelUrl': json['youtube_channel_url'] == null ? undefined : json['youtube_channel_url'],
        'instagramProfileUrl': json['instagram_profile_url'] == null ? undefined : json['instagram_profile_url'],
        'facebookPageUrl': json['facebook_page_url'] == null ? undefined : json['facebook_page_url'],
        'tiktokProfileUrl': json['tiktok_profile_url'] == null ? undefined : json['tiktok_profile_url'],
        'appStoreUrl': json['app_store_url'] == null ? undefined : json['app_store_url'],
        'googlePlayUrl': json['google_play_url'] == null ? undefined : json['google_play_url'],
        'suggest': json['suggest'] == null ? undefined : json['suggest'],
    };
}

export function UpdateProjectDraftRequestToJSON(json: any): UpdateProjectDraftRequest {
    return UpdateProjectDraftRequestToJSONTyped(json, false);
}

export function UpdateProjectDraftRequestToJSONTyped(value?: UpdateProjectDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'name': value['name'],
        'brand_name': value['brandName'],
        'description': value['description'],
        'industry': value['industry'],
        'matching_names': value['matchingNames'],
        'external_identifier': value['externalIdentifier'],
        'prompts': value['prompts'],
        'competitors': value['competitors'],
        'youtube_channel_url': value['youtubeChannelUrl'],
        'instagram_profile_url': value['instagramProfileUrl'],
        'facebook_page_url': value['facebookPageUrl'],
        'tiktok_profile_url': value['tiktokProfileUrl'],
        'app_store_url': value['appStoreUrl'],
        'google_play_url': value['googlePlayUrl'],
        'suggest': value['suggest'],
    };
}

