/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCompetitorRequest
 */
export interface UpdateCompetitorRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateCompetitorRequest
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompetitorRequest
     */
    brandName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCompetitorRequest
     */
    matchingNames?: Array<string>;
    /**
     * Hex color, e.g. #1a2b3c
     * @type {string}
     * @memberof UpdateCompetitorRequest
     */
    color?: string;
}

/**
 * Check if a given object implements the UpdateCompetitorRequest interface.
 */
export function instanceOfUpdateCompetitorRequest(value: object): value is UpdateCompetitorRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    return true;
}

export function UpdateCompetitorRequestFromJSON(json: any): UpdateCompetitorRequest {
    return UpdateCompetitorRequestFromJSONTyped(json, false);
}

export function UpdateCompetitorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCompetitorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'matchingNames': json['matching_names'] == null ? undefined : json['matching_names'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function UpdateCompetitorRequestToJSON(json: any): UpdateCompetitorRequest {
    return UpdateCompetitorRequestToJSONTyped(json, false);
}

export function UpdateCompetitorRequestToJSONTyped(value?: UpdateCompetitorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'brand_name': value['brandName'],
        'matching_names': value['matchingNames'],
        'color': value['color'],
    };
}

