/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCollectionRequest
 */
export interface UpdateCollectionRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateCollectionRequest
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateCollectionRequest interface.
 */
export function instanceOfUpdateCollectionRequest(value: object): value is UpdateCollectionRequest {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    return true;
}

export function UpdateCollectionRequestFromJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestFromJSONTyped(json, false);
}

export function UpdateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateCollectionRequestToJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestToJSONTyped(json, false);
}

export function UpdateCollectionRequestToJSONTyped(value?: UpdateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'description': value['description'],
    };
}

