/* tslint:disable */
/* eslint-disable */
/**
 * LLM Pulse API
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebAnalyticsQueryResponseColumnsInner } from './WebAnalyticsQueryResponseColumnsInner';
import {
    WebAnalyticsQueryResponseColumnsInnerFromJSON,
    WebAnalyticsQueryResponseColumnsInnerFromJSONTyped,
    WebAnalyticsQueryResponseColumnsInnerToJSON,
    WebAnalyticsQueryResponseColumnsInnerToJSONTyped,
} from './WebAnalyticsQueryResponseColumnsInner';

/**
 * 
 * @export
 * @interface WebAnalyticsQueryResponse
 */
export interface WebAnalyticsQueryResponse {
    /**
     * 
     * @type {number}
     * @memberof WebAnalyticsQueryResponse
     */
    projectId?: number;
    /**
     * 
     * @type {WebAnalyticsQueryResponseProviderEnum}
     * @memberof WebAnalyticsQueryResponse
     */
    provider?: WebAnalyticsQueryResponseProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof WebAnalyticsQueryResponse
     */
    property?: string;
    /**
     * 
     * @type {Array<WebAnalyticsQueryResponseColumnsInner>}
     * @memberof WebAnalyticsQueryResponse
     */
    columns?: Array<WebAnalyticsQueryResponseColumnsInner>;
    /**
     * One array per row, values in column order: strings, numbers or null.
     * @type {Array<Array<any>>}
     * @memberof WebAnalyticsQueryResponse
     */
    rows?: Array<Array<any>>;
    /**
     * Rows in this response (at most 5,000).
     * @type {number}
     * @memberof WebAnalyticsQueryResponse
     */
    rowCount?: number;
    /**
     * Rows the provider has for the query, when it reports it.
     * @type {number}
     * @memberof WebAnalyticsQueryResponse
     */
    totalRows?: number;
    /**
     * True when the provider has more rows than returned; page with its own offset or page field.
     * @type {boolean}
     * @memberof WebAnalyticsQueryResponse
     */
    truncated?: boolean;
    /**
     * Metric totals by metric name, when the query asked for them.
     * @type {{ [key: string]: any; }}
     * @memberof WebAnalyticsQueryResponse
     */
    totals?: { [key: string]: any; };
    /**
     * Provider caveats: sampling, thresholds, more rows available.
     * @type {Array<string>}
     * @memberof WebAnalyticsQueryResponse
     */
    notes?: Array<string>;
    /**
     * Provider metadata such as GA4 time zone, currency and remaining property quota.
     * @type {{ [key: string]: any; }}
     * @memberof WebAnalyticsQueryResponse
     */
    meta?: { [key: string]: any; };
    /**
     * When the provider answered.
     * @type {Date}
     * @memberof WebAnalyticsQueryResponse
     */
    fetchedAt?: Date;
    /**
     * True when the answer came from the 10-minute cache instead of the provider.
     * @type {boolean}
     * @memberof WebAnalyticsQueryResponse
     */
    cached?: boolean;
    /**
     * The request as sent to the provider, with the connected property forced and limits applied.
     * @type {{ [key: string]: any; }}
     * @memberof WebAnalyticsQueryResponse
     */
    query?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WebAnalyticsQueryResponse
     */
    requestId?: string;
}


/**
 * @export
 */
export const WebAnalyticsQueryResponseProviderEnum = {
    GoogleAnalytics: 'google_analytics',
    AdobeAnalytics: 'adobe_analytics',
    Matomo: 'matomo',
    Posthog: 'posthog',
    Plausible: 'plausible',
    Piano: 'piano'
} as const;
export type WebAnalyticsQueryResponseProviderEnum = typeof WebAnalyticsQueryResponseProviderEnum[keyof typeof WebAnalyticsQueryResponseProviderEnum];


/**
 * Check if a given object implements the WebAnalyticsQueryResponse interface.
 */
export function instanceOfWebAnalyticsQueryResponse(value: object): value is WebAnalyticsQueryResponse {
    return true;
}

export function WebAnalyticsQueryResponseFromJSON(json: any): WebAnalyticsQueryResponse {
    return WebAnalyticsQueryResponseFromJSONTyped(json, false);
}

export function WebAnalyticsQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAnalyticsQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'property': json['property'] == null ? undefined : json['property'],
        'columns': json['columns'] == null ? undefined : ((json['columns'] as Array<any>).map(WebAnalyticsQueryResponseColumnsInnerFromJSON)),
        'rows': json['rows'] == null ? undefined : json['rows'],
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'totalRows': json['total_rows'] == null ? undefined : json['total_rows'],
        'truncated': json['truncated'] == null ? undefined : json['truncated'],
        'totals': json['totals'] == null ? undefined : json['totals'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'meta': json['meta'] == null ? undefined : json['meta'],
        'fetchedAt': json['fetched_at'] == null ? undefined : (new Date(json['fetched_at'])),
        'cached': json['cached'] == null ? undefined : json['cached'],
        'query': json['query'] == null ? undefined : json['query'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function WebAnalyticsQueryResponseToJSON(json: any): WebAnalyticsQueryResponse {
    return WebAnalyticsQueryResponseToJSONTyped(json, false);
}

export function WebAnalyticsQueryResponseToJSONTyped(value?: WebAnalyticsQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'provider': value['provider'],
        'property': value['property'],
        'columns': value['columns'] == null ? undefined : ((value['columns'] as Array<any>).map(WebAnalyticsQueryResponseColumnsInnerToJSON)),
        'rows': value['rows'],
        'row_count': value['rowCount'],
        'total_rows': value['totalRows'],
        'truncated': value['truncated'],
        'totals': value['totals'],
        'notes': value['notes'],
        'meta': value['meta'],
        'fetched_at': value['fetchedAt'] == null ? value['fetchedAt'] : value['fetchedAt'].toISOString(),
        'cached': value['cached'],
        'query': value['query'],
        'request_id': value['requestId'],
    };
}

